C     GL0100A      13 AUG 91                                         MRP
C?IBM/GLD/GBR/VAX/UNX
      PROGRAM GAUSS
C??
C?CDC
C     PROGRAM GAUSS (INPUT,OUTPUT,PUNCH,TAPE1,
C    1 TAPE5=INPUT,TAPE6=OUTPUT,TAPE7=PUNCH,TAPE8,TAPE9=0,
C    2 TAPE10,TAPE11,TAPE12,TAPE13,TAPE14,TAPE15=0,TAPE16=0,TAPE99)
C??
C=GENERAL DESCRIPTION
C CHAPTER 1: GENERAL DESCRIPTION.
C **********
C
C1INTRODUCTION
C     ******************************************************************
C
C     MONSTERGAUSS ... A SERIES OF PROGRAMS DESIGNED TO PERFORM AB
C                      INITIO SELF-CONSISTENT FIELD MOLECULAR
C                      ORBITAL CALCULATIONS ON ORGANIC MOLECULES.
C
C     ******************************************************************
C
C     THIS PROGRAM IS BASED AROUND PARTS OF POPLE'S GAUSSIAN 82
C     (SPECIFICALLY THE INTEGRAL AND DERIVATIVE ROUTINES),
C     AND FEATURES ANALYTIC GRADIENT OPTIMIZATION OF GEOMETRIES,
C     PLUS VARIOUS OTHER OPTIONS SUCH AS RESTRICTED HARTREE-FOCK OPEN
C     SHELL SCF, PAIR-WISE MC-SCF, BOYS LOCALIZATION, ONE ELECTRON
C     PROPERTIES, QUANTITATIVE PMO ANALYSIS, A DIRECT CI AND
C     THE MOROKUMA ENERGY DECOMPOSITION.
C
C     MONSTERGAUSS HAS BEEN DESIGNED TO BE COMPATIBLE, WITH MINIMAL
C     CHANGES, WITH IBM AND CDC MAINFRAMES, GOULD MINICOMPUTERS,
C     THE DEC VAX MINICOMPUTERS, AND ALL UNIX-BASED SYSTEMS.
C
C     VERSION: 13 AUGUST 1991.
C
C     AUTHORS:
C
C     MIKE PETERSON,
C     DEPARTMENT OF CHEMISTRY,
C     UNIVERSITY OF TORONTO,
C     80 ST. GEORGE STREET,
C     TORONTO, ONTARIO, CANADA  M5S 1A1.
C     TELEPHONE: (416) 978-7094.
C
C     RAY POIRIER,
C     DEPARTMENT OF CHEMISTRY,
C     MEMORIAL UNIVERSITY OF NEWFOUNDLAND,
C     ELIZABETH AVENUE,
C     ST. JOHN'S, NEWFOUNDLAND, CANADA  A1B 3X7.
C     TELEPHONE: (709) 737-8609.
C==
C*
C1
C     VARIOUS MACHINE DEPENDENT FEATURES ARE IDENTIFIED BY CARDS LIKE:
C     C?XXX OR C#XXX
C     WHERE XXX IS A MACHINE TYPE (IBM, GLD, GBR, CDC, VAX OR UNX).
C     FOR MORE DETAILS, ESPECIALLY ON THE AUTOMATIC RE-DIMENSIONING
C     FEATURES DENOTED BY C#XXX BLOCKS, SEE PROGRAM CONVRT2.F.
C*
C     ON THE GOULD COMPUTER, THE $OPTION JCL DIRECTIVE MAY BE USED
C     AS FOLLOWS:
C     $OPTION 2 - SETTING OPTION 2 SUPPRESSES ALL PROGRESS MESSAGES
C                 TO THE OPERATORS CONSOLE.
C*
C=GENERAL DESCRIPTION
C1INTRODUCTION
C     CONTROL INPUT ... SPECIFICATION OF THE TYPE OF CALCULATION.
C*
C     THERE ARE 5 CONTROL CARDS (*MOL, *PRT, *PUN, *IOP AND *CON)
C     WHICH MAY BE USED, BUT ONLY THE *MOL CARD IS REQUIRED. THE
C     KEYWORD OCCUPIES COLUMNS 1-4 AND ARE READ IN THE FOLLOWING ORDER:
C
C     *MOL ... THIS CARD MARKS THE START OF A NEW CALCULATION, AND MAY
C              CONTAIN SEVERAL PROGRAM OPTIONS IN COLUMNS 5-72.
C
C     *PRT ... THIS CARD SPECIFIES SOME OF THE PRINT OPTIONS.
C
C     *PUN ... THIS CARD SPECIFIES SOME OF THE PUNCH OPTIONS.
C
C     *IOP ... SETTING OF SPECIFIC IOP'S.
C
C     *CON ... READ A SET OF CONVERSION FACTORS FOR THIS CALCULATION.
C*
C     GENERAL RULES.
C*
C     1  THE CODE WORD OCCUPIES COLUMNS 1-4, AND THE PARAMETERS (IF ANY)
C     MAY APPEAR ANYWHERE IN COLUMNS 5-72.
C
C     2  THE PARAMETERS MAY BE ABBREVIATED TO THEIR 1 (*PRT, AND *PUN
C     CARDS) OR 2 (*MOL CARDS) LETTER CODES - GENERALLY THE FIRST (2)
C     LETTER(S) FOR ONE WORD OPTIONS, OR THE FIRST LETTER OF EACH WORD
C     FOR TWO WORD OPTIONS. SUBPARAMETERS FOLLOW AN = SIGN, AND
C     GENERALLY MAY BE ABBREVIATED TO ONE LETTER.
C
C     3  SEPARATE OPTIONS WITH A COMMA. BLANKS MAY BE INSERTED ANYWHERE
C     ON THE CONTROL CARDS. THE OPTIONS MAY APPEAR IN ANY ORDER.
C
C     4  THE PROGRAM WILL CONVERT LOWER CASE TO UPPER CASE
C     AUTOMATICALLY WHERE NECESSARY.
C*
C=GENERAL DESCRIPTION
C1*MOL
C     ******************************************************************
C     *MOL CARD DETAILS.
C     ******************************************************************
C*
C     THE OPTIONS AVAILABLE WILL BE BROKEN INTO THE ROUGH
C     CLASSIFICATIONS OF GENERAL, GEOMETRY, BASIS SET, INITIAL GUESS,
C     SCF, OPTIMIZATION AND PROPERTIES. THE MINIMUM ABBREVIATON
C     FOLLOWS EACH KEYWORD IN PARENTHESES.
C*
C     GENERAL.
C*
C2CHECK
C     CHECK(CH) ... THIS IS A CHECK RUN - THE GEOMETRY, BASIS SET,
C     VARIATION CARDS FOR OPTIMIZATION, ETC ARE READ IN, AND
C     PRINTED - NO ACTUAL CALCULATION OF INTEGRALS ETC IS PERFORMED.
C     SPECIFYING THE SUBPARAMETER CH=IGUESS(I) CAUSES THE INITIAL
C     GUESS TO BE PERFORMED AND PRINTED ON THE CHECK RUN - FOR
C     PROJECTIONS FROM COEFFICIENT OR DENSITY MATRICES ALREADY ON
C     DISK, ANY FURTHER CH=I RUNS AND THE ACTUAL RUN SHOULD USE
C     GUESS=NONE (SEE BELOW).
C     BE CAREFUL THAT OPTIONS SET BY *IOP CARDS (SEE BELOW) WILL NOT
C     CAUSE PROBLEMS ON CHECK JOBS.
C     THE ONLY CARDS NOT CHECKED ARE PMO/LMO CARDS FOR THE
C     SECOND AND SUBSEQUENT POINTS OF SURFACE SCANS.
C*
C2GEOMETRY
C     GEOMETRY INPUT - DETAILS IN LINKS 0201 AND 0202.
C*
C     GEOM(GE) ... THE METHOD OF GEOMETRY INPUT IS SPECIFIED AS A
C     SUBPARAMETER (THE DEFAULT IS FREE FORMAT Z MATRIX INPUT):
C     GE=ZMAT(Z) ... FIXED FORMAT Z MATRIX INPUT.
C     GE=ANG(A) ... DIRECT COORDINATE INPUT IN ANGSTROMS.
C     GE=BOHR(B) ... DIRECT COORDINATE INPUT IN BOHR (ATOMIC UNITS).
C     GE=STDGEOM(S) ... USE STANDARD GEOMETRY - SEE LINK 0201.
C
C     AMASS(AM) ... ATOMIC MASS SELECTION. THE DEFAULT IS TO SELECT
C     THE MASS NUMBER FOR THE MOST ABUNDANT ISOTOPE. OTHER POSSIBILITIES
C     MAY BE SELECTED BY A SUBPARAMETER:
C     AM=AVERAGE(A) ... USE ABUNDANCE AVERAGED ATOMIC WEIGHTS.
C     AM=ISOTOPIC(I) ... USE MASS NUMBER FOR MOST ABUNDANT ISOTOPE
C     (THIS IS THE DEFAULT IF THE AM OPTION IS NOT SPECIFIED).
C     AM=READ(R) ... SET THE MASS NUMBERS FOR THE MOST ABUNDANT
C     ISOTOPE FOR EACH ATOM, THEN READ CHANGES.
C     AM=DUMP(D) ... DUMP THE CONTENTS OF THE ISOTOPIC MASS TABLES.
C     NOTE: IF AM IS SPECIFIED, A SUBPARAMETER MUST BE SPECIFIED.
C
C     SSCAN(SS) ... SURFACE SCAN. THE DEFAULT IS TO SCAN OVER A SET OF
C     GEOMETRICAL PARAMETERS, BUT A SET OF EXTERNAL ELECTRIC FIELDS
C     MAY ALSO BE SCANNED BY SPECIFYING A SUBPARAMETER:
C     SS=FIELD(F) ... SCAN OVER ELECTRIC FIELD VALUES INSTEAD OF
C     GEOMETRIES.
C*
C2BASIS-SET
C     BASIS SET SPECIFICATION AND INTEGRAL EVALUATION - FOR DETAILS SEE
C     LINKS 0301-0311.
C*
C     BASIS(BA) ... THE BASIS TYPE IS GIVEN BY A SUBPARAMETER AS IN
C     BASIS=TN, TN*, TN**, TN+ OR TN++ WHERE T IS THE BASIS TYPE
C     (ONE OF M, V, E, P, C OR G).
C     N IS USED TO SELECT THE ACTUAL BASIS SET FOR EACH TYPE:
C     MN GIVES THE STO-NG MINIMAL BASIS SET,
C     VN GIVES THE SPLIT VALENCE N-21G BASIS SET,
C     EN GIVES THE EXTENDED N-31G BASIS SET,
C     PN GIVES THE N-21G BASIS SET DEVISED BY PULAY AND CO-WORKERS,
C     CN GIVES THE N-311G BASIS SET DESIGNED FOR POST-SCF CALCULATIONS,
C     G GIVES A GENERAL BASIS SET WHICH IS READ FROM CARDS (N MAY NOT
C     BE USED).
C     THE DEFAULT BASIS SET IS STO-3G (M3).
C     IF T IS SPECIFIED, N MUST ALSO BE GIVEN IF T IS NOT G.
C
C     THE *'S INDICATE THE PRESENCE OF POLARIZATION FUNCTIONS:
C     FOR BASIS M, ONLY MN* IS PERMITTED AND D ORBITALS WILL BE ADDED
C     TO THE ATOMS NA-AR.
C     FOR BASIS V, THE FIRST * ADDS D ORBITALS TO THE ATOMS
C     NA-XE (NOTE THAT THE DEFAULT POLARIZED BASIS DOES NOT PUT
C     POLARIZATION FUNCTIONS ON H/HE, OR LI-NE).
C     FOR BASES E AND C, THE FIRST * ADDS D ORBITALS TO THE ATOMS
C     LI-XE, WHILE THE SECOND * PUTS P ORBITALS ON H/HE.
C
C     THE +'S INDICATE THE PRESENCE OF DIFFUSE FUNCTIONS:
C     FOR BASIS M, NO DIFFUSE FUNCTIONS MAKE ANY SENSE, SO NO MN+
C     BASIS SETS ARE AVAILABLE.
C     FOR BASES V, E AND C, THE FIRST + ADDS DIFFUSE SP ORBITALS TO THE
C     ATOMS LI-XE, WHILE THE SECOND + PUTS DIFFUSE S ORBITALS ON H/HE.
C     FOR BASIS G, G* INDICATES THAT THE BASIS CONTAINS D/F ORBITALS.
C     IF '*' OR '+' IS INCLUDED IN THE BASIS SET DESCRIPTOR, 70
C     ITERATIONS ARE ALLOWED FOR THE FIRST SCF.
C
C     DF ... THE BASIS SET CONTAINS D OR F ORBITALS. THIS OPTION IS
C     NOT REQUIRED FOR MN*, EN*(*) OR G* BASIS SETS, BUT IS REQUIRED
C     IF ATOMS PAST CALCIUM ARE USED FOR MN OR VN BASES. A SUBPARAMETER
C     MAY BE USED TO INDICATE THE TYPE OF D/F FUNCTIONS TO BE USED:
C     DF=CARTESIAN(C) WILL USE CARTESIAN D/F (6D/10F) FUNCTIONS,
C     WHILE DF=PURE(P) USES PURE D/F (5D/7F) FUNCTIONS. THE
C     DEFAULT IS P FOR ALL BASES EXCEPT FOR VN*, VN**, EN* AND EN**,
C     WHICH USE CARTESIAN D/F (6D/10F) FUNCTIONS.
C     THE BASIS FUNCTION ORDER (WITH THE CORRESPONDING PRINT SYMBOL IN
C     PARENTHESES) IS XX, YY, ZZ, XY, XZ AND YZ FOR 6D; 2ZZ-XX-YY (D0),
C     XZ (D1+), YZ (D1-), XX-YY (D2+) AND XY (D2-) FOR 5D. FOR 10F, THE
C     ORDER IS XXX, YYY, ZZZ, XYY, XXY, XXZ, XZZ, YZZ, YYZ AND XYZ; FOR
C     7F IT IS ZZZ-XXZ-YYZ (F0), XZZ-XXX-XYY (F1+), YZZ-YYY-XXY (F1-),
C     XXZ-YYZ (F2+), XYZ (F2-), XXX-XYY (F3+) AND XXY-YYY (F3-).
C
C     1POLARIZE(1P) ... PUT P POLARIZATION FUNCTIONS ON ROW 1 (H-HE).
C     SUBPARAMETER:
C     1P=YES(Y) ... YES.
C     1P=NO(N) ... NO.
C
C     2POLARIZE(2P) ... PUT D POLARIZATION FUNCTIONS ON ROW 2 (LI-NE).
C     SUBPARAMETER:
C     2P=YES(Y) ... YES.
C     2P=NO(N) ... NO.
C
C     3POLARIZE(3P) ... PUT D POLARIZATION FUNCTIONS ON ROW 3 (NA-AR).
C     SUBPARAMETER:
C     3P=YES(Y) ... YES.
C     3P=NO(N) ... NO.
C
C     4POLARIZE(4P) ... PUT D POLARIZATION FUNCTIONS ON ROW 4 (K-KR).
C     SUBPARAMETER:
C     4P=YES(Y) ... YES.
C     4P=NO(N) ... NO.
C
C     5POLARIZE(5P) ... PUT D POLARIZATION FUNCTIONS ON ROW 5 (RB-XE).
C     SUBPARAMETER:
C     5P=YES(Y) ... YES.
C     5P=NO(N) ... NO.
C
C     NOTE: FOR OPTIONS 1P THROUGH 5P TO BE RECOGNIZED, EITHER '*'
C     MUST HAVE BEEN SPECIFIED WITH THE BA OPTION, OR THE DF OPTION
C     WAS SPECIFIED. THERE ARE NO DEFAULTS FOR ANY OF THE OPTIONS,
C     SO A SUBPARAMETER MUST ALWAYS BE GIVEN.
C
C     1DIFFUSE(1D) ... PUT S DIFFUSE FUNCTIONS ON ROW 1 (H-HE).
C     SUBPARAMETER:
C     1D=YES(Y) ... YES.
C     1D=NO(N) ... NO.
C
C     2DIFFUSE(2D) ... PUT P DIFFUSE FUNCTIONS ON ROW 2 (LI-NE).
C     SUBPARAMETER:
C     2D=YES(Y) ... YES.
C     2D=NO(N) ... NO.
C
C     3DIFFUSE(3D) ... PUT P DIFFUSE FUNCTIONS ON ROW 3 (NA-AR).
C     SUBPARAMETER:
C     3D=YES(Y) ... YES.
C     3D=NO(N) ... NO.
C
C     4DIFFUSE(4D) ... PUT P DIFFUSE FUNCTIONS ON ROW 4 (K-KR).
C     SUBPARAMETER:
C     4D=YES(Y) ... YES.
C     4D=NO(N) ... NO.
C
C     5DIFFUSE(5D) ... PUT P DIFFUSE FUNCTIONS ON ROW 5 (RB-XE).
C     SUBPARAMETER:
C     5D=YES(Y) ... YES.
C     5D=NO(N) ... NO.
C
C     NOTE: FOR OPTIONS 1D THROUGH 5D TO BE RECOGNIZED, '+'
C     MUST HAVE BEEN SPECIFIED WITH THE BA OPTION.
C     THERE ARE NO DEFAULTS FOR ANY OF THE OPTIONS,
C     SO A SUBPARAMETER MUST ALWAYS BE GIVEN.
C     TO USE A BASIS SET WITH BOTH POLARIZATION AND DIFFUSE FUNCTIONS,
C     USE BASIS=TN+ (OR BASIS=TN++ IF DESIRED) AND DF; THEN ALL THE
C     POLARIZATION/DIFFUSE CONTROL OPTIONS 1POL-5POL AND 1DIF-5DIF
C     ARE AVAILABLE TO CUSTOMIZE THE BASIS SET.
C*
C2INITIAL-GUESS
C     INITIAL GUESS - SEE LINK 0402 FOR DETAILS.
C*
C     GUESS(GU) ... THE TYPE OF INITIAL GUESS IS GIVEN BY A
C     SUBPARAMETER:
C     GU=EH(E) ... EXTENDED HUCKEL GUESS (USE ONLY FOR THE INTERNAL
C     BASIS SET TYPE M).
C     GU=PH(P) ... PROJECTED HUCKEL GUESS FROM STO-3G TO BASIS USED.
C     GU=HDIAG(H) ... DIAGONALIZE THE CORE HAMILTONIAN MATRIX.
C     GU=DIN(D) ... READ DENSITY MATRIX.
C     GU=CIN(C) ... READ COEFFICIENT MATRIX.
C     GU=STO3G(S) ... READ THE STO-3G COEFFICIENT MATRIX AND PROJECT
C     THOSE COEFFICIENTS TO THE ACTUAL BASIS USED.
C     GU=V321G(V) ... READ THE 3-21G COEFFICIENT MATRIX AND PROJECT
C     THOSE COEFFICIENTS TO THE ACTUAL BASIS USED.
C     GU=GENERAL(G) ... READ THE GENERAL BASIS COEFFICIENT MATRIX AND
C     PROJECT THOSE COEFFICIENTS TO THE ACTUAL BASIS USED.
C     GU=NONE(N) ... NO INITIAL GUESS - ALREADY ON DISK FROM A PREVIOUS
C     CALCULATION.
C     THE DEFAULT IS AN EXTENDED HUCKEL GUESS FOR THE STO-NG BASES
C     (TYPE M), AND A PROJECTED HUCKEL GUESS FOR THE OTHER INTERNAL
C     BASES (TYPES V, E, P AND C) AND GENERAL BASES.
C     FOR PROJECTED GUESSES, THE BASIS SET PROJECTED FROM IS ALWAYS
C     ASSUMED TO BE DF=P (5D, NOT 6D).
C     NOTE: IF ANY MATRICES ARE READ IN, THEY WILL BE READ FROM
C     LOGICAL FILE CODE 1 (IBM UNIT FT01F001), NOT THE REGULAR
C     INPUT STREAM (LOGICAL FILE CODE 5, IBM UNIT FT05F001).
C
C     ACONFIG(AC) ... ALTERATION OF CONFIGURATION. THIS OPTION ALLOWS
C     THE USER TO CHANGE THE OCCUPANCY SCHEME OF THE INITIAL GUESS MO -
C     SEE LINK 0402 FOR DETAILS.  THE INITIAL GUESS COEFFICIENTS ARE
C     ALSO PRINTED AUTOMATICALLY UNLESS THE I=N OPTION IS USED ON THE
C     *PRT CARD. THIS OPTION IS NOT POSSIBLE FOR RHF RUNS.
C*
C2SCF
C     SCF EQUATIONS - SEE LINKS 0501, 0502 AND 0503 FOR DETAILS.
C     THE DEFAULT IS CLOSED SHELL RHF.
C*
C     UHF(UH) ... USE UHF OPEN SHELL (SPIN-UNRESTRICTED SCF).
C
C     RHF(RH) ... USE RHF OPEN SHELL / PAIR EXCITATION MC-SCF.
C     A SUBPARAMETER ALLOWS THE SPECIFICATION OF A CONVERGENCE OPTION:
C     RH=RESET(R) ... RESET AN INTERNAL SCALE FACTOR BEFORE EVERY CYCLE
C     OF THE SCF. THIS MAY CAUSE NON-CONVERGENCE IN SOME CASES,
C     ESPECIALLY LARGE BASIS SETS, BUT IS USUALLY THE FASTEST MODE
C     OF OPERATION. THIS IS THE DEFAULT MODE (NO SUBPARAMETER GIVEN).
C     RH=NORESET(N) ... TURN OFF THE RESET SWITCH - THIS MAY
C     HELP OR HINDER CONVERGENCE, SO GOOD LUCK. IF THE SCF CONVERGES
C     IN NORESET MODE, IT IS RESTARTED IN RESET MODE TO ENSURE THE
C     COEFFICIENTS ARE REALLY CONVERGED.
C     RH=INCREMENT(I) ... USE NORESET MODE UNTIL THE DENSITY
C     CONVERGES WITHIN A CERTAIN VALUE, THEN START INCREMENTING THE
C     SCALE FACTOR FOR SUCCESSIVE SCF ITERATIONS.
C     RH=OMIT(O) ... SIMPLY OMIT COEFFICIENT CHANGES THAT ARE TOO
C     LARGE, AND PRINT A MESSAGE.
C     SUBSEQUENT RHF'S (FOR OPTIMIZATION OR SURFACE SCAN RUNS) ALWAYS
C     USE THE DEFAULT MODE (RESET MODE).
C     SEE LINK 0401 FOR DETAILS OF THE RHF INPUT REQUIRED.
C
C     CONV(CO) ... THE CONVERGENCE OPTIONS DESIRED ARE SPECIFIED BY A
C     MAXIMUM OF 2 ONE LETTER SUBPARAMETERS:
C     CO=I ... I REPRESENTS ONE OF THE NUMBERS 5 THROUGH 9 INCLUSIVE,
C     AND SETS THE DENSITY CONVERGENCE TO 10**(-I). THE DEFAULT
C     CONVERGENCE IS 10**(-9) FOR CLOSED SHELL OR UHF SCF,
C     AND 10**(-6) FOR THE RHF SCF.
C     CO=M ... ALLOW 190 SCF ITERATIONS (THE MAXIMUM NUMBER).
C     CO=C ... ALLOW 190 SCF ITERATIONS, AND CONTINUE THE RUN
C     EVEN IF THE SCF IS STILL NOT CONVERGED PROVIDED THE ENERGY CHANGE
C     BETWEEN SUCCESSIVE ITERATIONS IS LESS THAN 10**(-6) HARTREES.
C     CO=D ... USE THE DEWAR EXTRAPOLATION TECHNIQUE.
C     CO=N ... NO SCF EXTRAPOLATION.
C     NOTE: TWO SUBPARAMETERS MAY BE SPECIFIED BY COMBINING THE ONE
C     LETTER CODES: CO=D6, CO=8N, CO=CN FOR EXAMPLE. THE COMBINATIONS
C     CO=CM, CO=DN AND CO=IJ (WHERE I AND J ARE 5, 6, 7, 8, OR 9) ARE
C     ILLEGAL.
C*
C2OPTIMIZATION
C     OPTIMIZATION - SEE LINKS 0202, 0301 AND 0701-0711 FOR DETAILS.
C*
C     GOPT(GO) ... OPTIMIZE THE GEOMETRY. THE USE OF INTERNAL
C     COORDINATES IS THE DEFAULT. THE SUBPARAMETER GO=CC(C) INDICATES
C     THE USE OF CARTESIAN COORDINATES (NOT RECOMMENDED) - THIS IS
C     AUTOMATICALLY FORCED IF THE GEOMETRY IS INPUT IN ANGSTROMS OR
C     BOHR. FOR FREE FORMAT Z MATRIX RUNS USING SIMULTANEOUS
C     OPTIMIZATION METHODS (IE. NOT METHOD=Z), THE DEFAULT IS TO
C     OPTIMIZE ONLY THE Z MATRIX PARAMETERS SPECIFIED AS VARIABLES,
C     FIXING THOSE SUPPLIED AS CONSTANTS. THE SUBPARAMETER GO=READ(R)
C     WILL READ THE OPTIMIZATON CONSTRAINTS FROM CARDS WHEN THE FREE
C     FORMAT Z MATRIX GEOMETRY INPUT IS USED. NOTE THAT IF NO
C     VARIABLES ARE USED, OR THE FIXED FORMAT IS USED, OR THE STANDARD
C     GEOMETRY IS USED, THE CONSTRAINT CARDS MUST BE SUPPLIED.
C     VARIATION CARDS MUST ALWAYS BE SUPPLIED FOR THE Z MATRIX
C     OPTIMIZATION METHOD.
C     FOR FORCE OPTIMIZATIONS, THE BASIS SET FORCE IS NOT CALCULATED
C     UNLESS BOPT IS ALSO SPECIFIED.
C
C     BOPT(BO) ... OPTIMIZE THE BASIS SET.
C
C     METHOD(ME) ... THE OPTIMIZATION METHOD IS GIVEN BY A
C     SUBPARAMETER:
C     ME=BFGS(B) ... BFGS OPTIMIZATION WITH THE GRADIENT.
C     ME=OC(O) ... OPTIMALLY CONDITIONED OPTIMIZATION WITH THE GRADIENT.
C     THIS IS THE DEFAULT OPTIMIZATION METHOD IF THE ME= OPTION IS NOT
C     SPECIFIED.
C     ME=VA05(V) ... SOLUTION OF THE GRADIENT EQUATIONS USING THE
C     VA05AD ROUTINE.
C     ME=DOC(D) ... OPTIMALLY CONDITIONED OPTIMIZATION WITHOUT THE
C     GRADIENT (DERIVATIVE-FREE).
C     ME=ZM(Z) ... DERIVATIVE-FREE METHOD OF OPTIMIZING THE Z MATRIX
C     PARAMETERS FROM GAUSSIAN 70 USING PARABOLIC INTERPOLATION.
C
C     RING(RI) ... THE STRUCTURE TO BE OPTIMIZED CONTAINS A RING. SINCE
C     THE PRESENCE OF A RING IMPOSES SEVERE CONSTRAINTS ON THE BOND
C     LENGTHS, BOND ANGLES AND DIHEDRAL ANGLES THAT ARE PHYSICALLY
C     REASONABLE, THIS OPTION CAUSES THE FOLLOWING CHANGES IN THE
C     OPTIMIZATION ROUTINES TO HELP SUCH STRUCTURES BE OPTIMIZED
C     SUCCESSFULLY:
C     THE BOND STRETCH FORCE CONSTANT GUESSES ARE SET TO AT LEAST 7.5,
C     THE BOND ANGLE AND DIHEDRAL ANGLE INITIAL FORCE CONSTANT
C     GUESSES ARE CHANGED TO 5.0 (FROM 1.0 AND 0.5 RESPECTIVELY),
C     THE OC OPTIMIZATION METHOD EXTRAPOLATION LIMIT IS CHANGED TO
C     3.0 (FROM 10.0),
C     AND THE VA05 OPTIMIZATION METHOD STEP SIZE (DSTEP) IS CHANGED TO
C     0.01 (FROM 0.02).
C
C     RESTART(RE) ... RESTART OF A FORCE OPTIMIZATION. FOR GOPT RUNS,
C     THE ORIGINAL STARTING GEOMETRY IS READ IN AS USUAL, THEN UPDATED
C     BY THE VALUES SAVED IN FILE 1 OF UNIT IMAT - THIS UNIT MUST HAVE
C     BEEN SAVED TO USE THIS OPTION SUCCESSFULLY. FOR BOPT RUNS, THE
C     BASIS SET IS READ IN AS USUAL, THEN UPDATED BY THE VALUES IN THE
C     BASIS SET FILES OF UNIT IMAT - THIS UNIT MUST HAVE BEEN SAVED TO
C     USE THIS OPTION SUCCESSFULLY.
C     GUESS=NONE CAN BE SPECIFIED TO RE-USE THE PREVIOUS COEFFICIENT /
C     DENSITY MATRICES. NOTE THAT THE GEOMETRY AND/OR BASIS SET
C     VARIATION CARDS ARE NOT READ AGAIN, BUT THE OPTIMIZATION CONTROL
C     CARDS ARE READ AGAIN.
C     GUESS=NONE IS ALWAYS ASSUMED FOR BOPT RESTARTS.
C     RE=GEOMETRY(G) ... FOR OTHER THAN FORCE OPTIMIZATION RUNS, THE
C     ORIGINAL GEOMETRY IS READ IN AS USUAL, THEN JUST THE GEOMETRY
C     IS UPDATED FROM UNIT IMAT - THIS UNIT MUST HAVE BEEN SAVED TO
C     USE THIS OPTION SUCCESSFULLY. BE CAREFUL ON CHECK RUNS WHERE
C     THE RESTART FILE MAY NOT HAVE BEEN CREATED YET, FOR EXAMPLE IN
C     A PREVIOUS STEP OF THE SAME JOB.
C     RE=BASIS(B) ... FOR OTHER THAN FORCE OPTIMIZATION RUNS, THE
C     BASIS SET IS READ IN AS USUAL, THEN UPDATED BY THE VALUES IN THE
C     BASIS SET FILES OF UNIT IMAT - THIS UNIT MUST HAVE BEEN SAVED TO
C     USE THIS OPTION SUCCESSFULLY.
C
C     NPRINT(NP) ... NO PRINT OPTION FOR Z MATRIX OPTIMIZATION (ME=Z)
C     RUNS - MOST INTERMEDIATE PRINTING IS TURNED OFF, BUT THE FIRST
C     AND LAST POINTS ARE PRINTED FULLY.
C*
C2PROPERTIES
C     PROPERTIES - SEE LINKS 0508, 0601, 0602, 0801-0803 AND 0901-0907.
C     NOTE: LMO, SIZE AND OEP SHOULD NOT BE USED WITH THE RHF SCF,
C     EXCEPT FOR THE SPECIAL CASES DETAILED IN LINK 0401.
C*
C     DMOMENT(DM) ... CALCULATE THE DIPOLE MOMENT.
C
C     LMO(LM) ... LOCALIZE THE MOLECULAR ORBITALS. AN OPTIONAL
C     SUBPARAMETER MAY BE USED FOR RESEARCH INTO LMO POLARIZABILITIES:
C     LM=1 ... COMPUTE AND SAVE THE ZERO FIELD LMO ROTATIONS.
C     LM=2 ... APPLY THE ZERO FIELD LMO ROTATIONS TO A FINITE FIELD
C     CASE (SEE LINKS 0601 AND 0801 FOR MORE DETAILS ON THE LMO -
C     FINITE FIELD PROBLEM).
C
C     SIZE(SI) ... LOCALIZE THE MOLECULAR ORBITALS AND CALCULATE THEIR
C     SIZES.
C
C     OEP(OE) ... EVALUATION OF ONE-ELECTRON PROPERTIES. THE ORBITALS
C     TO USE ARE GIVEN BY A SUBPARAMETER:
C     OE=LMO(L) ... PROPERTIES OVER LMO.
C     OE=CMO(C) ... PROPERTIES OVER CMO.
C     THE DEFAULT IS OVER LMO IF ORBITALS WERE LOCALIZED, ELSE OVER CMO.
C     FOR OPTIMIZATIONS WITH THE FP OPTION, OR FOR SURFACE SCANS, THE
C     OEP INPUT IS READ ONLY ONCE AND SAVED ON DISK, RESULTING IN THE
C     SAME SET OF PROPERTIES BEING REPEATED AUTOMATICALLY.
C
C     POLARIZABILITY(PO) ... ESTIMATE DIPOLE POLARIZABILITY.
C
C     FORCE(FO) ... CALCULATE THE FORCE (GRADIENT), IN INTERNAL
C     COORDINATES BY DEFAULT. SPECIFYING FO=CC(C) CALCULATES THE FORCES
C     IN CARTESIAN COORDINATES. THIS OPTION MUST NOT BE USED FOR
C     FORCE OPTIMIZATION RUNS.
C
C     FREQUENCIES(FR) ... CALCULATE THE FORCE CONSTANTS (HESSIAN).
C     FOR GEOMETRY OPTIMIZATION RUNS (GOPT), A SUBPARAMETER MAY BE
C     USED:
C     FR=FIRST(F) WILL EVALUATE THE HESSIAN AT THE FIRST POINT OF THE
C     OPTIMIZATION ONLY. THIS IS USEFUL TO START AN OPTIMIZATION
C     OF A DIFFICULT STRUCTURE, OR FOR TRANSITION STATE OPTIMIZATIONS.
C     FR=BOTH(B) WILL EVALUATE THE HESSIAN AT THE FIRST AND LAST
C     POINTS OF THE OPTIMIZATION ONLY.
C     FR=LAST(L) WILL EVALUATE THE HESSIAN AT THE LAST POINT OF THE
C     OPTIMIZATION ONLY (I.E. AT THE CONVERGED GEOMETRY). THIS IS
C     USEFUL FOR PERFORMING AN "ORDER CHECK" ON A GEOMETRY.
C
C     FPOINT(FP) ... CALCULATE ANY MOLECULAR PROPERTIES FOR THE FIRST
C     POINT OF GEOMETRY/BASIS SET OPTIMIZATIONS, AS WELL AS AT THE END
C     (THEY ARE USUALLY ONLY CALCULATED AT THE END).
C
C     FIELD(FI) ... THE TYPE OF FIELD TO BE APPLIED IS GIVEN BY A
C     SUBPARAMETER:
C     FI=ELECTRIC(E) ... CALCULATION TO BE PERFORMED IN THE PRESENCE
C     OF A UNIFORM EXTERNAL ELECTRIC FIELD.
C     FI=SCRF(S) ... CALCULATION TO BE PERFORMED USING SELF CONSISTENT
C     REACTION FIELD THEORY, TO EVALUATE SOLVENT EFFECTS.
C     REFERENCES: J.L. RIVAIL AND D. RINALDI, CHEM. PHYS., 18, 233
C     (1976); R. CIMIRAGLIA, S. MIERTUS AND J. TOMASI, CHEM. PHYS.
C     LETT., 80, 286 (1981).
C     THE SCRF IS ONLY AVAILABLE FOR CLOSED SHELL WAVEFUNCTIONS.
C
C     PMO(PM) ... PERFORM A PMO ANALYSIS. THE SUBPARAMETER PM=SAVE(S)
C     PUNCHES THE SAVE DATA (S, H, F AND C MATRICES) IN LINK 0601, WHILE
C     PM=RESTART(R) WILL READ IN THE SAVE DATA AND GO DIRECTLY TO THE
C     PMO ANALYSIS - NO PROPERTIES MAY BE REQUESTED IN A PMO RESTART.
C     THE INITIAL GUESS(GU) OPTION IS IGNORED FOR A PMO RESTART.
C     FOR OPTIMIZATION RUNS THE ANALYSIS IS PERFORMED FOR THE LAST
C     POINT, UNLESS THE FP OPTION IS SPECIFIED. THE PMO ANALYSIS IS
C     POSSIBLE ONLY FOR CLOSED SHELL MOLECULES.
C     REFERENCE: M.-H. WHANGBO, H.B. SCHLEGEL AND S. WOLFE, J. AMER.
C     CHEM. SOC., 99, 1296 (1977).
C
C     EDECOMPOSITION(ED) ... PERFORM THE MOROKUMA ENERGY DECOMPOSITION.
C     THIS OPTION MAY BE COMBINED WITH THE BSSE OPTION.
C     THIS OPTION IS NOT COMPATABLE WITH MOST OTHER OPTIONS (E.G.
C     SSCAN, GOPT, DM, LMO/SIZE, PMO, CI).
C
C     BSSE(BS) ... PERFORM A BASIS SET SUPERPOSITION ERROR (BSSE)
C     CORRECTION ("COUNTER-POISE" CORRECTION).
C     THIS OPTION MAY BE COMBINED WITH THE EDECOMPOSITION OPTION.
C     THIS OPTION IS NOT COMPATABLE WITH MOST OTHER OPTIONS (E.G.
C     SSCAN, GOPT, DM, LMO/SIZE, PMO, CI).
C
C2CI
C     CI ... DIRECT CI FOR THE LOWEST ROOT (STATE) OF A GIVEN SYMMETRY
C     AND MULTIPLICITY (POSSIBILITIES ARE CLOSED SHELL SINGLETS AND RHF
C     OPEN SHELL SINGLETS, DOUBLETS, TRIPLETS AND QUARTETS). THIS OPTION
C     REQUIRES 6 ADDITIONAL I/O UNITS.
C     THE NORMAL MODE OF OPERATION REQUIRES TWO RUNS:
C     THE FIRST SPECIFYING THE SUBPARAMETER CI=SETUP(S) FOR
C     COMPLETE PRINTING OF THE SCF COEFFICIENTS, BUT NO ATTEMPT IS
C     MADE TO ENTER THE CI PROGRAMS (LINKS 0901-0906). THE MO VECTOR
C     SYMMETRIES SHOULD BE DETERMINED BY INSPECTION (THE VALID POINT
C     GROUPS ARE C1, CS, C2V AND D2H), THEN THE SECOND RUN SPECIFYING
C     CI=RESTART(R) IS MADE. THIS ASSUMES THE DIRECT ACCESS FILE AND
C     2-ELECTRON INTEGRALS HAVE BEEN SAVED FROM THE SETUP RUN, AS NO
C     INTEGRALS ARE RECALCULATED. THE INITIAL GUESS(GU) OPTION IS
C     IGNORED FOR CI RESTARTS, AND NO OTHER PROPERTIES MAY BE REQUESTED.
C     SPECIFY JUST CI TO DO THE INTEGRALS, SCF AND CI IN ONE SHOT (EG
C     FOR SURFACE SCANS OR CASES WITH NO SYMMETRY). THE CI IS PERFORMED
C     AT THE LAST POINT OF OPTIMIZATION RUNS UNLESS THE FP OPTION IS
C     SPECIFIED. FOR SURFACE SCANS, OR OPTIMIZATIONS RUNS WITH THE FP
C     OPTION, THE INTEGRAL TRANSFORMATION AND CI CONTROL CARDS ARE READ
C     ONLY ONCE AND SAVED ON DISK - THUS ALL POINTS MUST HAVE THE SAME
C     MO ORDER AND SYMMETRY. THE UHF SCF MAY NOT BE USED.
C     REFERENCE: N.C. HANDY, J.D. GODDARD AND H.F. SCHAEFER, J. CHEM.
C     PHYS., 71, 426 (1979).
C
C     MRDCI(MR) ... PREPARE THE FILES NECESSARY FOR BUENKER'S MRD-CI
C     PROGRAM SYSTEM. THE COORDINATES, ONE ELECTRON INTEGRALS AND MO
C     MO COEFFICIENTS ARE WRITTEN TO UNIT 11 (THE SECOND CI FILE), AND
C     THE TWO ELECTRON INTEGRALS TO UNIT 9 AS USUAL. THE SUBPARAMETER
C     MR=SCF(S) SPECIFIES THAT MONSTERGAUSS PERFORM THE SCF CALCULATION
C     AND WRITE THOSE FINAL MO COEFFICIENTS RATHER THAN THE INITIAL
C     GUESS COEFFICIENTS. THIS OPTION IS NOT COMPATIBLE WITH
C     OPTIMIZATION RUNS, THE DIRECT CI, SURFACE SCANS OR PMO RESTARTS.
C*
C=GENERAL DESCRIPTION
C1*PRT
C     ******************************************************************
C     *PRT OPTIONS.
C     ******************************************************************
C*
C     ANY OF THE FOLLOWING CODE WORDS (LETTERS) MUST BE FOLLOWED BY
C     =YES(Y) OR =NO(N) TO TURN THE OPTIONS ON OR OFF RESPECTIVELY.
C     *PRT OPTIONS ARE USED ON EVERY ROUTE CARD WHERE THEY ARE
C     APPLICABLE.
C
C     BASIS(B) ... PRINT THE BASIS SET. THE DEFAULT IS B=NO(N) EXCEPT
C     FOR GENERAL BASIS OR BOPT RUNS.
C
C     IGC(I) ... PRINT THE INITIAL GUESS COEFFICIENTS. THE DEFAULT IS
C     I=NO(N) UNLESS THE AC OPTION ON THE *MOL CARD WAS USED.
C
C     C ... PRINT THE COEFFICIENTS AND ORBITAL ENERGIES (DEFAULT=YES).
C     SPECIFYING C=Y WILL FORCE PRINTING OF ALL THE MO COEFFICIENTS
C     AS ONLY THE LOWEST TEN VIRTUALS ARE PRINTED BY DEFAULT.
C
C     D ... PRINT THE DENSITY MATRIX (DEFAULT=NO).
C
C     GEOM(G) ... PRINT FULL GEOMETRY CHECK, INCLUDING REQUESTED BOND
C     AND TORSIONAL ANGLES - SEE LINK 0601 (DEFAULT=NO).
C
C     POP(P) ... PRINT CONTROL IN THE MULLIKEN POPULATION ANALYSIS -
C     THE DEFAULT PRINTING IS ONLY RESULTS CONDENSED TO ATOMS.
C     SPECIFYING P=YES(Y) TURNS ON ALL PRINTING, WHILE P=NO(N) TURNS
C     ALL PRINTING OFF.
C
C     MOINTS(M) ... PRINT THE INTEGRALS OVER MO IN THE SIZE AND/OR
C     ONE-ELECTRON PROPERTIES PACKAGES (DEFAULT=NO).
C
C     TIME(T) ... PRINT THE TIMING INFORMATION AND A MESSAGE FOR EACH
C     NEW LINK (DEFAULT=NO).
C     TIMING INFORMATION IS NOT AVAILABLE ON IBM/VAX/UNX COMPUTERS,
C     SO ONLY THE MESSAGE FOR EACH NEW LINK IS PRINTED.
C*
C=GENERAL DESCRIPTION
C1*PUN
C     ******************************************************************
C     *PUN OPTIONS.
C     ******************************************************************
C*
C     THE PRESENCE OF ANY OF THE FOLLOWING CODE LETTERS WILL CAUSE
C     PUNCHING OF THAT ITEM. THE DEFAULT IS NO PUNCHING OF ANYTHING.
C     PUNCHING OCCURS AT THE FIRST POINT OF SURFACE SCANS, AND THE
C     LAST POINT OF GEOMETRY/BASIS SET OPTIMIZATIONS.
C     THE FIRST 40 LETTERS ON THE TITLE CARD (SEE LINK 0202) WILL BE
C     USED TO IDENTIFY PUNCHED OUTPUT DECKS.
C
C     C ... PUNCH THE COEFFICIENTS AND ORBITAL ENERGIES.
C
C     D ... PUNCH THE DENSITY MATRIX.
C
C     LMO(L) ... PUNCH THE LMO COEFFICIENTS.
C
C     Z ... PUNCH THE FINAL Z MATRIX FOR GOPT RUNS.
C*
C=GENERAL DESCRIPTION
C1*IOP
C     ******************************************************************
C     *IOP - SETTING SPECIFIC IOP'S.
C     ******************************************************************
C*
C     THIS CONTROL CARD IS USED TO SET SPECIFIC IOP'S ON SPECIFIC ROUTE
C     CARDS. VALUES OF ISEQ, IOP AND IVAL ARE READ FROM A CARD (3I4
C     FORMAT). ISEQ IS THE NUMBER OF THE BASIC ROUTE CARD (SEE ROUTINE
C     ROUTE), IOP IS THE IOP NUMBER (13-92) AND IVAL IS THE
C     VALUE TO INSERT (0-7). TERMINATE THE LIST OF CHANGES WITH A
C     BLANK CARD. COMMENTS MAY BE PLACED IN COLUMNS 13 TO 72.
C     FOR EXAMPLE, TO TURN ON FULL PRINTING OF THE GRADIENT COMPONENTS
C     IT IS NECESSARY TO SET IOP(21)=2 ON THE ROUTE CARDS CALLING
C     GROUP 7, THE GRADIENT LINKS. FROM ROUTINE ROUTE (BELOW),
C     GROUP 7 IS USED THREE TIMES IN THE COMPLETE ROUTE - AS
C     SEQUENCE NUMBERS 8, 15 AND 21. FOR FULL PRINTING AT ONLY THE
C     THE FIRST POINT OF SINGLE POINT, GRADIENT OPTIMIZATION OR SURFACE
C     SCAN RUNS, THE *IOP CARD
C        8  21   2  GRADIENT COMPONENTS
C     WOULD BE USED. FOR COMPLETE PRINTING AT EACH POINT OF GRADIENT
C     OPTIMIZATIONS OR SURFACE SCANS (USING THE FORCE OPTION) THE CARD
C       15  21   2  GRADIENT COMPONENTS DURING OPTS/SCANS
C     WOULD DO THE TRICK. FOR Z MATRIX OPTIMIZATIONS NOT USING THE
C     FIRST POINT (FP) OPTION, THE CARD
C       21  21   2  GRADIENT COMPONENTS AT FINAL POINT OF Z MATRIX OPTS
C     WOULD PRINT THE GRADIENT COMPONENTS AT THE OPTIMUM GEOMETRY.
C     NOTE THAT LINKS MAY BE ADDED OR DELETED FROM THE ROUTE BY
C     SPECIFYING IOP'S BETWEEN 61 AND 92. FOR EXAMPLE, THE CARD
C        2  66   0  DELETE 2-ELECTRON SP INTEGRAL ROUTINE (SHELL)
C     WOULD DELETE LINK 0306 FROM THE ROUTE. BE CAREFUL DURING CHECK
C     JOBS THAT LINKS ADDED/DELETED WILL NOT CAUSE TROUBLE.
C*
C=GENERAL DESCRIPTION
C1*CON
C     ******************************************************************
C     *CON - SETTING NEW CONVERSION FACTORS.
C     ******************************************************************
C*
C     THE FOLLOWING CARD, IN 5F12.6 FORMAT, GIVES THE VALUES TO USE FOR
C     AUTOAN (CONVERSION OF BOHR TO ANGSTROMS), DCONST (CONVERSION OF
C     DIPOLE MOMENT TO DEBYE), FCONV (CONVERSION OF FORCES FROM
C     HARTREE/BOHR TO MDYNE), FCCONV (CONVERSION OF FORCE CONSTANTS
C     FROM HARTREE/ANGSTROM**2 TO MDYNE/ANGSTROM), AND VCM (CONVERSION
C     OF ELECTRIC FIELD FROM ATOMIC UNITS TO VOLTS/CM). ALL FIVE VALUES
C     MUST BE GIVEN. THE CURRENT VALUES ARE BASED ON THE 1973 REVISED
C     FUNDAMENTAL CONSTANTS (THE VALUES FROM GAUSSIAN 70 WERE
C     0.529167165, 2.54158059, 8.2380, 4.3593 AND 0.0 (UNKNOWN)).
C*
C=GENERAL DESCRIPTION
C1INTRODUCTION
C     *****************************************************************
C     THE FOLLOWING RESTRICTIONS MUST BE TAKEN INTO CONSIDERATION
C     *****************************************************************
C*
C     1  INTERNAL MINIMAL STO-NG BASES ARE AVAILABLE FOR THE ATOMS H-XE
C     (EXCEPT Y-CD) FOR N BETWEEN 2 AND 6.
C     INTERNAL SPLIT VALENCE N-21G BASES ARE AVAILABLE FOR THE ATOMS
C     H-XE (MAIN GROUP ONLY, N = 3), H-AR (N = 6),
C     AND THE ATOMS H-NE (N = 4).
C     INTERNAL EXTENDED N-31G BASES ARE AVAILABLE FOR THE ATOMS H-NE,
C     AND P-CL (N = 4), FOR H, HE, C-F (N = 5), AND FOR H-AR (N = 6).
C     NOTE THAT THE 4-31G BASIS FOR LI AND BE IS ACTUALLY A 5-21G BASIS.
C     INTERNAL PULAY N-21G BASES ARE AVAILBLE FOR H, B-F (N = 4 ONLY).
C     THE INTERNAL N-311G BASES, INTENDED FOR USE WITH CORRELATED
C     WAVEFUNCTIONS, ARE AVAILBLE FOR THE ATOMS H-NE (N = 6 ONLY).
C     FOR FURTHER DETAILS CONSULT PROGRAM GINPUT ... LINK 0301.
C     POLARIZED BASIS SETS ARE NOT AVAILABLE FOR ALL THE ATOMS
C     AND BASIS SETS LISTED ABOVE.
C
C     2  CI IS POSSIBLE ONLY FOR CLOSED SHELLS, AND FOR OPEN SHELL
C     SINGLETS, DOUBLETS, TRIPLETS AND QUARTETS WHERE EACH OPEN SHELL
C     OCCUPIED BY BY ONE ALPHA SPIN ELECTRON. CASES WITH PARTIALLY
C     OCCUPIED OPEN SHELLS (I.E. DEGENERATE OPEN SHELL ORBITALS) CAN
C     NOT BE HANDLED.
C
C     3  GEOMETRY GRADIENTS ARE AVAILABLE FOR SPD BASIS SETS, BUT BASIS
C     SET GRADIENTS ONLY FOR SP BASIS SETS. FOR PURE 5D FUNCTIONS, THE
C     NUMBER OF ATOMIC ORBITALS MUST BE #NB OR LESS WHEN EACH 5D SET IS
C     IS REPLACED BY A 6D SET OF FUNCTIONS FOR THE GRADIENT EVALUATION.
C*
C     ******************************************************************
C     THE ABOVE CARDS ARE SUFFICIENT TO COMPLETELY DEFINE THE ROUTING
C     ******************************************************************
C*
C     SOME INPUT EXAMPLES
C     ASSUME CARD COLUMNS ARE
C     123...
C*
C     SINGLE STO-3G CALCULATION ON A CLOSED SHELL MOLECULE  Z-MATRIX
C     SPECIFICATION OF GEOMETRY  CALCULATE DIPOLE MOMENT
C     *MOL GEOM=ZMAT, BASIS=M3, DM
C*
C     GEOMETRY OPTIMIZATION RUN  STO-3G BASIS  OPEN SHELL
C     *MOL BASIS=M3, UHF, GOPT, METHOD=ZM
C*
C     4-31G OPTIMIZATION OF THE GEOMETRY AND BASIS SET  Z MATRIX INPUT
C     OF THE GEOMETRY  CLOSED SHELL  LOCALIZE THE ORBITALS WITH SIZES
C     USE THE BFGS METHOD  PRINT THE FULL POPULATION ANALYSIS AND
C     PUNCH THE DENSITY MATRIX AT THE END OF THE OPTIMIZATION.
C     *MOL BASIS=E4, GOPT, BOPT, METHOD = BFGS, S I Z E
C     *PRT POP=YES
C     *PUN DENSITY
C*
C     USING THE DEFAULT OPTIONS WHERE APPLICABLE THE ABOVE THREE
C     EXAMPLES MAY ALSO BE WRITTEN (USING MINIMUM ABBREVIATIONS)
C*
C     *MOLGE=Z,DM
C*
C     *MOLUH,GO,ME=Z
C*
C     *MOLBA=E4,GO,BO,ME=B,SI
C     *PRTP=Y
C     *PUND
C*
C     FOR THOSE USING THE INTERNAL BASIS SETS VERY LITTLE IN THE
C     WAY OF INPUT REMAINS
C     THIS IS BUT THE INPUT OF GEOMETRY THROUGH THE
C     COORDINATE GENERATION ROUTINES ... LINK 0201 OR LINK 0202,
C     AND
C     FOR OPTIMIZATION RUNS
C     THE INPUT OF PARAMETERS TO BE VARIED
C     SEE ROUTINES VGEOM (LINK 0202), GINPUT (LINK 0301), AND GBOPT
C     (LINK 0711) FOR DETAILS ON GEOMETRY AND BASIS SET OPTIMIZATION.
C     FOR INPUT OF AN EXTERNAL BASIS SET DETAILS ARE GIVEN IN ROUTINE
C     GBASIS (LINK 0301).
C*
C     ******************************************************************
C1
C=ROUTE GENERATION
C CHAPTER 2: ROUTE GENERATION.
C **********
C
C1ROUTE-GENERATION
C     FOR THOSE WHO LIKE TO KNOW WHAT'S GOING ON,
C     THE METHOD OF GENERATING ROUTES IS DESCRIBED IN DETAIL.
C*
C     IMAGINE THAT THE ROUTE WAS PUNCHED ON CARDS - THEN EACH CARD
C     WOULD LOOK LIKE:
C     GROUP  OPTIONS  LINKS  JUMP
C     WHERE THE GROUP NUMBER OCCUPIES COLUMNS 1-4, THE OPTIONS 5-60,
C     THE LINKS 61-92, AND A JUMP FIELD.
C*
C     ******************************************************************
C*
C     TO UNDERSTAND THE MEANING OF THE FIELDS A BIT OF GENERAL
C     DESCRIPTION OF THE METHOD OF OVERLAYING IS ESSENTIAL.
C*
C     NOTE THAT THESE INTERNAL LINKS OFTEN RESEMBLE THE
C     EXTERNAL OVERLAY STRUCTURE AS SET UP BY THE LINKAGE EDITOR ...
C     AND THEY ARE SIMILAR IN THAT INFORMATION IS PASSED BETWEEN
C     LINKS ONLY THROUGH COMMON OR ON DISK.
C*
C     EACH PROGRAM RETURNS TO THE CONTROL ROUTINE 'CHAIN' WHICH CALLS
C     THE NEXT PROGRAM IN THE SEQUENCE GIVEN BY THE USER.
C*
C     THE GROUPS ARE NOT IN THEMSELVES PROGRAMS BUT JUST CONVENIENT
C     HEADINGS FOR A SET OF PROGRAMS CALLED LINKS.
C     HERE THE NONEXISTANT GROUPS ARE LABELED
C     100  200  300  400  500  600  700  800  900
C     WHERE IN GENERAL TERMS:
C     GROUP 100 DEALS WITH INITIALIZATION AND ROUTE GENERATION,
C     200 DEALS WITH COORDINATE GENERATION,
C     300 WITH INTEGRAL EVALUATION,
C     400 WITH INITIAL GUESS,
C     500 WITH THE SELF-CONSISTENT FIELD EQUATIONS,
C     600 WITH POPULATION ANALYSIS, PMO ANALYSIS, AND ED/BSSE,
C     700 WITH DERIVATIVES AND SIMULTANEOUS OPTIMIZATION,
C     800 WITH BOYS LOCALIZATION PROCEDURE AND ONE ELECTRON PROPERTIES,
C     900 WITH INTEGRAL TRANSFORMATION AND CI.
C*
C     WITH EACH GROUP MAY BE ASSOCIATED FROM 1 TO 32 LINKS
C     NUMBERED ... FOR EXAMPLE
C     301  302  AND  303
C     MEANING LINKS 1 2 AND 3 OF GROUP 3 ( OR 0300 )
C     HAPPILY THE LINKS ACTUALLY EXIST AND ARE IN REALITY THE
C     LINKS OF OUR CHAIN.
C*
C     TO SET UP A ROUTE THROUGH MONSTERGAUSS IT IS FIRST NECESSARY
C     TO KNOW WHICH LINKS OF WHICH GROUPS ARE REQUIRED AND
C     IN WHAT ORDER THEY ARE TO BE EXECUTED.
C     THE DICTIONARY OF LINKS GIVEN BELOW SHOULD AID IN THE
C     FORMER TASK.
C*
C     THE FIRST FIELD IS THE GROUP NUMBER, BEING ONE OF
C     2, 3, 4, 5, 6, 7, 8 OR 9 (SHORT FOR 200, 300, 400, 500, 600,
C     700, 800 OR 900).
C     THE USER NEVER SPECIFIES GROUP 0100 LINKS, AS THESE LINKS ARE
C     INSERTED INTO THE ROUTE AUTOMATICALLY BY THE ROUTE GENERATOR.
C*
C     SPECIFICATION OF THE LINK NUMBERS IS A BIT LESS OBVIOUS -
C     PLACING A NON-ZERO VALUE (1 FOR EXAMPLE) IN THE FIRST LINK
C     FIELD (COLUMN 61) SIGNIFIES A CALL TO LINK 1,
C     THAT IN THE SECOND FIELD (COLUMN 62) A CALL TO LINK 2 AND
C     SO ON.
C     NOTE THAT MORE THAN ONE LINK MAY BE CALLED FROM A SINGLE
C     GROUP CARD,
C     AND THAT THE LINKS WILL ALWAYS BE CALLED IN NUMERICAL ORDER.
C     IN ORDER TO CALL THE LINKS OF AN GROUP OUT OF ORDER,
C     MULTIPLE GROUP CALLS ARE REQUIRED.
C*
C     ASSOCIATED WITH EACH GROUP ... AND HENCE WITH EACH SET OF
C     LINKS ... IS A SET OF OPTIONS.
C     THESE ARE LISTED WITH EACH MAJOR PROGRAM AND IT WILL BE
C     NECESSARY TO CONSULT THE INDIVIDUAL LINKS FOR DETAILED
C     DESCRIPTIONS.
C     THESE OPTIONS ... TERMED IOP(5) TO IOP(60) ... ARE FOUND
C     IN COLUMNS 5 TO 60 RESPECTIVELY OF THE GROUP CARDS.
C*
C     NORMALLY THE GROUP CARDS ARE EXECUTED IN THE ORDER IN WHICH
C     THEY WERE GENERATED,
C     HOWEVER PROVISION HAS BEEN MADE FOR JUMPING ... ONLY BACKWARDS ...
C     SO AS TO BE ABLE TO CREATE LOOPS
C     FOR EXAMPLE THE GROUP STRUCTURE FOR THE OPTIMIZATION OF THE
C     GEOMETRY OF A MOLECULE MIGHT BE SOMETHING LIKE THE FOLLOWING
C*
C     GENERATE INITIAL GEOMETRY
C     NEXT
C     EVALUATE INTEGRALS
C     NEXT
C     TAKE AN INITIAL GUESS AT THE WAVEFUNCTION
C     NEXT
C     EXECUTE SCF PROCEDURE
C     NEXT
C     PERFORM A POPULATION ANALYSIS ... AS THIS IS THE FIRST
C     CALCULATION IN THE OPTIMIZATION SOME PRINTING MIGHT BE DONE TO
C     MAKE CERTAIN THAT ALL IS GOING WELL
C     NEXT
C     ALTER INITIAL GEOMETRY
C     NEXT
C     AND THIS MARKS THE BEGINNING OF OUR PROGRAMMED LOOP
C     ..................................................................
C     AGAIN EVALUATE INTEGRALS
C     NEXT
C     PERFORM SCF CALCULATION ... THE DENSITY MATRIX FROM THE
C     PREVIOUS CALCULATION WILL AUTOMATICALLY BE USED AS AN INITIAL
C     GUESS TO THIS CALCULATION
C     NEXT
C     AGAIN ALTER GEOMETRY
C     NOW  JUMPBACK TWO CARDS  TO CALCULATE INTEGRALS
C     VOILA ... WE HAVE A LOOP
C     ..................................................................
C     WHEN THE OPTIMIZATION IS COMPLETE THIS JUMP WILL AUTOMATICALLY
C     BE BYPASSED SO AS TO ALLOW US TO GO ON TO OTHER GROUP CARDS
C     FOR EXAMPLE
C     CALCULATE DIPOLE MOMENT INTEGRALS FOR BOYS LOCALIZATION
C     DO A POPULATION ANALYSIS
C     AND FINALLY
C     DO A BOYS LOCALIZATION.
C     A JUMP AFTER EXECUTION OF ALL THE LINKS IN A GIVEN GROUP
C     IS SIGNALED BY A NEGATIVE NUMBER ON THE GROUP CARD (JUMP FIELD).
C*
C     FOR FURTHER UNDERSTANDING, STUDY THE STANDARD ROUTES AND THEIR
C     VARIANTS GENERATED BY MONSTERGAUSS.
C*
C     ******************************************************************
C*
C=ROUTE GENERATION
C     DICTIONARY OF LINKS AND ASSOCIATED ROUTINES.
C     NOTE THAT ONLY ONE SOURCE COPY OF EACH
C     ROUTINE APPEARS IN THE ENTIRE SYSTEM -
C     WHERE A ROUTINE IS NEEDED IN SEVERAL LINKS THIS LONE COPY WILL
C     EITHER BE FOUND WITH THE EARLIEST ... LOWEST NUMBERED ... LINK
C     WHICH USES IT, OR IN ONE OF THE UTILITY LINKS.
C     OTHER LINKS USING THE SAME ROUTINE HAVE THE NAME ENCLOSED IN
C     PARENTHESES. THE ONLY ROUTINE WRITTEN IN ASSEMBLER IS UNPACK.
C     ROUTINES DUMMYI ALLOW SECOND LEVEL OVERLAYS
C     IN THE INTEGRAL PROGRAMS.
C     THE CODES (FMTGEN), (RPOLX), (F0INIT) AND (F1DA) MEAN THAT
C     NUMEROUS ROUTINES FOR INTEGRAL/DERIVATIVE EVALUATION ARE USED.
C     MOST ROUTINES FROM LINK 9990 ARE USED IN ALL INTEGRAL/DERIVATIVE
C     LINKS, AND MOST ROUTINES FROM LINK 9991 ARE USED IN ALL FIRST
C     DERIVATIVE LINKS.
C     ROUTINES FROM LINK 9999 ARE USED THROUGHOUT THE PROGRAM.
C     ******************************************************************
C     THE FOLLOWING ROUTINES ARE USED BY MANY LINKS, AND ARE LOCATED
C     IN THE ROOT SEGMENT OF MONSTERGAUSS: GAUSS, CHAIN, TREAD, TWRITE.
C     ..................................................................
C     LINK 0100
C     PROGRAM SETUP ... DEFINES MATRIX FILE, INITIATES CALCULATION.
C     ASSOCIATED SUBROUTINES:
C     CRITIC,GAMGEN,(FMTGEN)
C     ..................................................................
C     LINK 0101
C     PROGRAM LNK1 ... DEFINES THE ROUTE FOR THE CALCULATION.
C     ASSOCIATED SUBROUTINES:
C     FINDC,ROUTE
C     ..................................................................
C     LINK 0201
C     PROGRAM STDGEO ... MOLECULAR GEOMETRY FROM A STANDARD MODEL.
C     ASSOCIATED SUBROUTINES:
C     GETCHR,GETBL,SGDUMP,BD201
C     ..................................................................
C     LINK 0202
C     PROGRAM VGEOM ... INPUT OF THE MOLECULAR GEOMETRY.
C     ASSOCIATED SUBROUTINES:
C     ZPARAM,BUILDZ,VEC,VPROD,SINCOS,ZSCALE,FREEZ,ZPRINT,FILMAS,(FREEFM)
C     ..................................................................
C     LINK 0301
C     PROGRAM GINPUT ... SETUP PROGRAM FOR GAUSSIAN INTEGRAL PACKAGE.
C     ASSOCIATED SUBROUTINES:
C     STO,NM1G,GBASIS,S1S,S2S,S2P,S2SP,S3S,S3P,S3SP,S3D,S3SPD1,S3SPD2,
C     S4S,S4P,S4SP,S4SPD1,S4SPD2,S5SP,EZERO,EONE,ETWO,ETHREE,EFOUR,
C     BERROR
C     ..................................................................
C     LINK 0302
C     PROGRAM STVINT ... OVERLAP AND CORE HAMILTONIAN INTEGRALS (T+V).
C     ASSOCIATED SUBROUTINES:
C     OVRLAP,(RPOLX),(FILMAT),(PUREDF)
C     ..................................................................
C     LINK 0303
C     PROGRAM DIPOLE ... CALCULATION OF X, Y AND Z DIPOLE INTEGRALS.
C     ASSOCIATED SUBROUTINES:
C     (GETCC1),(GET1CS),(GET2CS),(FILMAT),(PUREDF)
C     ..................................................................
C     LINK 0306
C     PROGRAM SHELL ... GAUSSIAN SP TWO ELECTRON INTEGRAL PACKAGE.
C     ASSOCIATED SUBROUTINES:
C     FILMAX,SINFO,SGEOM,PINF,SP0000,SP0001,SP0011,SP0101,SP0111,SP1111,
C     ROT2,TQ0011,TQ0101,TQ0111,TQ1111,R30001,R30011,R30101,R30111,
C     R31111,SHLOUT,(FMTGEN)
C     ..................................................................
C     LINK 0307
C     PROGRAM UNCON ... 2-ELECTRON INTEGRALS FOR (SP)D FUNCTIONS.
C     ASSOCIATED SUBROUTINES:
C     UFILLC,URD65,FORMP,FORMQ,FABCD,ROTATE,FORMS,(FMTGEN),(SHLOUT)
C     ..................................................................
C     LINK 0308
C     PROGRAM PHOENX ... 2-ELECTRON INTEGRALS FOR (SP)DF FUNCTIONS.
C     ASSOCIATED SUBROUTINES:
C     AOSUMF,CNTPRM,MTGET,F0ROOT,F0SUM,(RPOLX),(FMTGEN),(F0INIT),
C     (PURDF2),(SHLOUT)
C     ..................................................................
C     LINK 0309
C     PROGRAM DSTVWT ... ONE ELECTRON DERIVATIVE PACKAGE.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0310
C     PROGRAM DPHNXW ... 2-ELECTRON DERIVATIVES FOR SPD FUNCTIONS.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0311
C     PROGRAM SECINT ... INTEGRAL SELECTION FOR ENERGY DECOMPOSITION.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0401
C     PROGRAM RHFIN ... RHF PARAMETER INPUT.
C     ASSOCIATED SUBROUTINES:
C     AKLBKL,ICOMB,IFACT
C     ..................................................................
C     LINK 0402
C     PROGRAM GUESS ... INITIAL GUESS ROUTINE.
C     ASSOCIATED SUBROUTINES:
C     HUCKEL,BLOCK,ORTHOC,DENSTY,NVSQRT,READER,MATREC,FGUESS,KSTO,KM1G,
C     KM11G,(TRED12),(FREEFM)
C     ..................................................................
C     LINK 0403
C     PROGRAM SECORT ... INITIAL GUESS FOR ENERGY DECOMPOSITION.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0501
C     PROGRAM CLOSED ... ROOTHAAN CLOSED SHELL SCF.
C     ASSOCIATED SUBROUTINES:
C     FORMV,CYCCLO,FOFCLO,CONCLO,TRACLO,SQUARE,LINEAR,SCRFT,
C     (UNPACK),(TRED12)
C     ..................................................................
C     LINK 0502
C     PROGRAM UHFOPN ... SOLUTION OF THE POPLE-NESBET EQUATIONS.
C     ASSOCIATED SUBROUTINES:
C     (FORMV),CYCOPN,FOFOPN,CONOPN,SPIN,TRAOPN,(SCRFT),(SQUARE),
C     (UNPACK),(TRED12)
C     ..................................................................
C     LINK 0503
C     PROGRAM GSCF ... GENERAL RESTRICTED HARTREE-FOCK OPEN SHELL SCF.
C     ASSOCIATED SUBROUTINES:
C     JKMATX,MCCI,VCOEF,MCFOCK,PAIRS,ROTSCF,CONRHF,CSD,LAGRNG,SCHMDT,
C     CALDEN,CALENG,TRARHF,RSCRFT,(SQUARE),(TRACLO),(SPIN),(TRED12),
C     (UNPACK)
C     ..................................................................
C     LINK 0505
C     PROGRAM ZCLOSE ... CLOSED SHELL SCF WITH ENERGY DECOMPOSITION.
C     ASSOCIATED SUBROUTINES:
C     ZFORMV,ZCYCCL,ZSELCT,EFLD,(FOFCLO),(CONCLO),(TRACLO),
C     (SQUARE),(LINEAR),(UNPACK),(TRED12)
C     ..................................................................
C     LINK 0506
C     PROGRAM ZUHF ... UHF WITH ENERGY DECOMPOSITION.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0507
C     PROGRAM ZRHF ... RHF WITH ENERGY DECOMPOSITION.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0601
C     PROGRAM POPGEN ... POPULATION ANALYSIS.
C     ASSOCIATED SUBROUTINES:
C     DISMAT,CROSS,BORDER,DQ,PUNCH,MRDCI,(MAPRO1)
C     ..................................................................
C     LINK 0602
C     PROGRAM PMO ... PERTURBATIONAL MO ANALYSIS.
C     ASSOCIATED SUBROUTINES:
C     FRGMNT,PARTS,PARTSE,TRUNCA,FRGTRS,TRANSF,VD01A,(TRED12)
C     ..................................................................
C     LINK 0603
C     PROGRAM ZMOROK ... ENERGY DECOMPOSITION / BSSE DRIVER.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0701
C     PROGRAM FORCEB ... GEOMETRY AND BASIS SET FORCES FOR SP BASES.
C     ASSOCIATED SUBROUTINES:
C     ONELB,TWOLB,FPPPPB,(FMTGEN)
C     ..................................................................
C     LINK 0702
C     PROGRAM FORCE ... 1-ELECTRON GEOMETRY GRADIENT.
C     ASSOCIATED SUBROUTINES:
C     REDOD,DSTVNT,(DRVIP1),(RPOLX),(FMTGEN)
C     ..................................................................
C     LINK 0703
C     PROGRAM DTWOL ... 2-ELECTRON GEOMETRY GRADIENT FOR SP FUNCTIONS.
C     ASSOCIATED SUBROUTINES:
C     FPPPP,(FMTGEN)
C     ..................................................................
C     LINK 0704
C     PROGRAM DPHNIX ... 2-E GEOMETRY GRADIENT FOR (SP)DF FUNCTIONS.
C     ASSOCIATED SUBROUTINES:
C     REDODD,D2AO,F1ROOT,F1SUM,(RPOLX),(FMTGEN),(F0INIT),(F1DA)
C     ..................................................................
C     LINK 0708
C     PROGRAM CPHF ... COUPLED PERTURBED HARTREE-FOCK CALCUATION.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0709
C     PROGRAM DD1E ... 1-ELECTRON GEOMETRY SECOND DERIVATIVES.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0710
C     PROGRAM DD2E ... 2-ELECTRON GEOMETRY SECOND DERIVATIVES.
C     ASSOCIATED SUBROUTINES:
C     ..................................................................
C     LINK 0711
C     PROGRAM GBOPT ... SIMULTANEOUS GEOMETRY / BASIS SET OPTIMIZATION.
C     ASSOCIATED SUBROUTINES:
C     GBPRNT,GBSET,BFGS,MC11AD,MC11BD,MC11ED,OC,DSRCH,FORMPQ,LTOLSP,
C     LSPTOL,MODCON,LTMVEC,LTTRVC,SETLT,VA05MP,MB11MP,FCPRNT,BOST,BEND,
C     TORS,LIBE,INVERT,DOC,SEARCH,LSPVEC,PICK,
C     (TRED12),(BUILDZ),(VEC),(VPROD),(SINCOS),(ZPARAM),(ZPRINT)
C     ..................................................................
C     LINK 0801
C     PROGRAM BOYLOC ... BOYS LOCALIZED ORBITALS AND SIZES.
C     ASSOCIATED SUBROUTINES:
C     LOCAL,SUBSET,LSHFT,SIM,ROTAT,FBOND,MOSIZE,PROPB,SIZES,
C     (SHFT71),(PRODS1),(PRODF1),(OLAP1),(OPAB4),(TRED12),(MAPRO1)
C     ..................................................................
C     LINK 0802
C     PROGRAM OEPROP ... ONE ELECTRON PROPERTIES.
C     ASSOCIATED SUBROUTINES:
C     BCONV,DINTFM,PROPB1,SHFT71,PRODS1,PRODF1,ANONUC,DIPNUC,
C     AMGNUC,QUDNUC,OCTNUC,FLDNUC,GRDNUC,SLDNUC,OLAP1,
C     OPAA1,OPAA2,OPAA3,OPAB1,OPAB2,OPAB3,OPAB4,OPAB5,OPAC1,OPAC2,
C     OPAC3,OPAD1,FMC,AAINER,PRNT,PAXIS,RSQ,MABAT,DIAG70
C     ..................................................................
C     LINK 0803
C     PROGRAM DIPSQ ... ESTIMATE DIPOLE POLARIZABILITIES.
C     ASSOCIATED SUBROUTINES:
C     TRACE4,(MAPRO1)
C     ..................................................................
C     LINK 0901
C     PROGRAM INTRAN ... INTEGRAL TRANSFORMATION.
C     ASSOCIATED SUBROUTINES:
C     TR1,GF1,TR2,SET,INTPRT,(UNPACK)
C     ..................................................................
C     LINK 0902
C     PROGRAM COUPLE ... CI COUPLING COEFFICIENTS.
C     ASSOCIATED SUBROUTINES:
C     SETUP1,SETUP2,SETUP3,SETUP4,SETUP5,LHSRHS,TYPDD1,TYPDD2,TYPDD3,
C     TYPDD4,TYPDD5,CODED1,CODED2,CODED3,CODED4,CODED5,SUBR1,SUBR2,
C     SUBR3,TYPES1,TYPES2,TYPES3,TYPES4,TYPES5,CODES1,CODES2,CODES3,
C     CODES4,CODES5,MATRG,MATR,ZERO3,INTER,INTERS,INTESS,INT0,
C     LIST1,LIST2,FIND1,FIND12,FIND3,FINDS,ENTER2,ENTF12,ENTF3,ENTS,
C     OUTPUT,WRTOUT
C     ..................................................................
C     LINK 0903
C     PROGRAM CONFIG ... CI CONFIGURATION GENERATOR.
C     ASSOCIATED SUBROUTINES:
C     OPCODE,ITYPD,ITYPS
C     ..................................................................
C     LINK 0904
C     PROGRAM INTSRT ... CI INTEGRAL SORT.
C     ASSOCIATED SUBROUTINES:
C     CONSTS,COUL,EXCH,MOIN,REORDR,(UNPACK)
C     ..................................................................
C     LINK 0905
C     PROGRAM FORMTP ... CI FORMULA TAPE GENERATOR.
C     ASSOCIATED SUBROUTINES:
C     FNOPEN,OPENO1,OPENO2,OPENO3,OPENO4,OPENO5,OPENO6,WRT,WRT3,
C     WST,WST3,ICUP,(UNPACK)
C     ..................................................................
C     LINK 0906
C     PROGRAM CIROOT ... DIRECT CI FOR LOWEST ROOT.
C     ASSOCIATED SUBROUTINES:
C     OPQUE,SFOPEN,CIUNPK,(TRED12)
C     ..................................................................
C     LINK 0907
C     PROGRAM OEPMO ... ONE ELECTRON PROPERTIES OVER MOLECULAR ORBITALS.
C     ASSOCIATED SUBROUTINES:
C     ATMUL
C     ..................................................................
C     LINK 9990
C     INTEGRAL EVALUATION UTILITY ROUTINES:
C     FILLC,(FILLST),FILLCP,(SETCP),FILMAT,GET1CS,GET2C,GET2CS,GET3C,
C     GETA1,GETA2,GETCC1,GETCC2,GETIP2,PUREDF,(PURSET),PURDF2,QINF,
C     TWOD2C,TWOD3C,TWOD4C
C     CMPLTC,DINT2E,FMTGEN,FMTSET,FORMFN,FPX,FX,RFPX,RFX,RPOLX,
C     RYSPOL,RYSROT,RYSSET,BDT2W2,
C     F02CTR,F03CTR,F04CTR,F0CFIL,F0CLD1,F0CLD2,F0INIT
C     WHERE INITIALIZATION ENTRY POINTS ARE ENCLOSED IN PARENTHESES.
C     ..................................................................
C     LINK 9991
C     FIRST DERIVATIVE EVALUATION UTILITY ROUTINES:
C     D2ZER,DIPA,DIPAB,DIPABI,DIPABC,DIPAC,DIPACI,DRVIP1,
C     F1DA,F1DAB1,F1DAB2,F1DABC,F1DAC1,F1DAC2,RAWST
C     ..................................................................
C     LINK 9999
C     GENERAL UTILITY ROUTINES:
C     NWIORD,NWIOWR,NWIOWT,FREEFM,TRED12,TQL12,MATPAC,MAPRO1,GBSOUT,
C     MATOUT,UPPER
C     ******************************************************************
C*
C=ROUTE GENERATION
C     ******************************************************************
C     SOME GENERAL COMMENTS ABOUT ADDING PROGRAMS TO MONSTERGAUSS
C     ******************************************************************
C*
C     1  THE LAST OR TERMINAL EXECUTABLE STATEMENT IN ANY PROGRAM
C     SHOULD BE ... RETURN ... NEVER STOP.
C     THIS RESULTS IN THE LOADING OF THE NEXT LINK TO BE EXECUTED
C     IF IOP(1)=0 ... THE ROUTE CONTINUES NORMALLY INCLUDING THE
C     EXECUTION OF ANY LOOPS
C     IF IOP(1)=1 ... BYPASS ANY LOOP JUMP AFTER THIS LINK.
C     IF IOP(1)=2 ... BYPASS ALL LINKS IN THE ROUTE UNTIL AFTER THE
C     NEXT LOOP JUMP (THE JUMP IS ALSO BYPASSED).
C     IF IOP(1)=999 ... THIS IS THE FIRST ENTRY INTO LNK1.
C     IF IOP(1) IS SET TO A NEGATIVE NUMBER, THE ROUTE WILL BE
C     TERMINATED IMMEDIATELY - IF IOP(1)=-1, THE CURRENT DENSITY
C     MATRIX WILL BE PUNCHED OUT BEFORE STARTING A NEW CALCULATION.
C     IF IOP(1)=-3, THE CURRENT BASIS SET IS PRINTED BEFORE TERMINATING
C     THE RUN.
C*
C     2  CHAIN MUST BE EXTENDED WHEN A NEW LINK IS ADDED.
C*
C     3  CHECK THE DICTIONARY OF PROGRAM AND SUBROUTINE NAMES
C     SO AS TO AVOID DUPLICATIONS ... AND MUCH TROUBLE.
C*
C     4  EACH LINK SHOULD CHECK IOP(10) WHEN IT IS ENTERED, AND RETURN
C     IMMEDIATELY IF NOTHING IS TO BE DONE ON CHECK RUNS (IOP(10)=0).
C     THIS ALLOWS EVEN CHECK RUNS TO ACTIVATE EACH DESIRED LINK AT
C     LEAST ONCE.
C*
C     ******************************************************************
C==
C*
C/
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C#
C     PARAMETER (NA=#NA, NB=#NB)
C     PARAMETER (NS=#NS, NP=#NP)
C##
      PARAMETER (NA= 36, NB=200)
      PARAMETER (NS=120, NP=300)
C###
      PARAMETER (NA3=3*NA, NZ=NA3-6)
C
      CHARACTER TITLE*72, IELEM*4, NAMES*8
      CHARACTER NSH*2, LAO*4, LABEL*4, LSHELL*2, BLABEL*200
      CHARACTER LABSAV*4, LABSYM*4
C
C     FOR THE GOULD BASE REGISTER VERSION, THESE COMMONS ARE REPEATED
C     IN SUBROUTINE SHLOUT (LINK 0306).
C
C     GENERAL COMMON BLOCK WITH BASIC INFORMATION.
      COMMON /A/ IOP(99),IC1(NA),IC2(7),C(NA,3),FCON(4),IC3(401)
C     Z MATRIX GEOMETRY COMMON BLOCKS.
      COMMON /ZMAT/ IZ1(NA,4),Z1(NA,3),
     1 IPAR(15,3),NIPAR(3),NPAR,NSTEP,DX(3),NUM,NUMB,
     2 IZ2(NA,3),IZMASS(NA),ZMASS(NA)
      COMMON /ZMATC/ TITLE,IELEM(NA),NAMES(NZ)
C     BASIS SET.
      COMMON /B/ IB1(NS,6),NSHELL,MAXTYP,B2(NP,3)
      COMMON /BSINFO/ NVO(NA), IAOFF(NA)
      COMMON /BSINFC/ NSH(NB), LAO(NB), LABEL(NS), LSHELL(NS), BLABEL
C     I/O UNITS, DIRECT ACCESS FILE PARTITION DATA.
      COMMON /IO/ IODUM(17),NFILE(100,2)
C     GENERAL RESULTS.
      COMMON /GEN/ E(6),DCONV,SPIN(2),FIELD(3),FE,EMOL,ESOL,DPOLE(4),VCM
C     INTEGRAL LABEL UNPACK AREA.
      COMMON /PACKED/ INTLAB(5)
C     SAVE SOME DATA FROM THE PMO PACKAGE.
      COMMON /NFRAG/ NN(6)
C     SAVE CHARACTER DATA FROM ONE ELECTRON PROPERTIES PACKAGE.
      COMMON /OEPLAB/ LABSAV(90)
C     SAVE CHARACTER DATA FROM CI SYMMETRY LABELS.
      COMMON /CILAB/ LABSYM(8)
C?GLD/GBR THIS CARD IDENTIFIES GOULD FORT77/FORTX32 SPECIAL FEATURES.
C     COMMON /GLDDATA/ MYID(12)
C??
      CALL CHAIN
      STOP
      END
