C     GL0202A      04 MAY 89                                         MRP
C?IBM/GLD/GBR/VAX/UNX
      SUBROUTINE VGEOM
C??
C?CDC
C     PROGRAM VGEOM
C??
C=GEOMETRY INPUT
C Z MATRIX GEOMETRY INPUT.
C ************************
C
C1INTRODUCTION
C     LINK 0202
C*
C     --------------
C     U OF T VERSION
C     JULY 1988
C     --------------
C*
C     DETERMINATION AND OPTIMIZATION OF THE GEOMETRY OF ANY MOLECULE
C     WHICH MAY BE SPECIFIED BY A Z MATRIX, AND
C     DIRECT INPUT OF ATOMIC COORDINATES.
C*
C1Z-MATRIX
C     *****************************************************************
C     EXPLANATION OF REQUIRED INPUT FOR Z MATRIX GEOMETRY
C     *****************************************************************
C     SINGLE CALCULATION OR INITIAL POINT IN AN OPTIMIZATION OR
C     POTENTIAL SURFACE SCAN RUN
C     *****************************************************************
C*
C     TITLE  (FREE FIELD)
C     THE FIRST 40 LETTERS OF THE TITLE ARE USED TO IDENTIFY PUNCHED
C     OUTPUT DECKS (68 LETTERS ARE USED FOR Z MATRICES).
C     CHARGE AND MULTIPLICITY  (2I2)
C     CONVENTION FOR MULTIPLICITY ... 1=SINGLET  2=DOUBLET  AND SO ON
C     Z MATRIX ELEMENTS
C     NUMBER OF ATOMS ... NATOMS ... CARDS OF THE ABOVE FORMAT
C     THE LIST IS TERMINATED BY A BLANK CARD
C*
C     USERS NOT FAMILIAR WITH THE Z MATRIX GEOMETRY INPUT ARE
C     ENCOURAGED TO READ THE FREE FORMAT DESCRIPTION FOR MORE DETAILS.
C*
C     DETAILS OF Z MATRIX INPUT (STANDARD FORMAT)
C     I4, I4, F12.6, I4, F12.4, I4, F12.4, I4
C     A   B   C      D   E      F   G      H
C     WHERE:
C     A: ATOMIC NUMBER OF ATOM
C     B: NUMBER OF ATOM IT IS ATTACHED TO
C     C: DISTANCE (IN ANGSTROMS) TO ATOM IN B
C     IF H=0 (PLANE AND DIHEDRAL ANGLE)
C       D AND E: E IS THE ANGLE THIS ATOM - ATOM B - ATOM D
C       F: LOOKING ALONG BOND FROM B TO D, F IS ATOM THAT DIHEDRAL ANGLE
C         IS MEASURED FROM (IN COUNTERCLOCKWISE DIRECTION)
C       G: DIHEDRAL ANGLE OF THIS ATOM WITH RESPECT TO F (IN DEGREES)
C     IF H=+1 OR -1 (TWO EULER ANGLES)
C       D AND E: E IS THE ANGLE THIS ATOM - ATOM B - ATOM D
C       F AND G: G IS THE ANGLE THIS ATOM - ATOM B - ATOM F
C       H: SPECIFIES WHETHER THIS ATOM IS ABOVE OR BELOW PLANE B-D-F -
C         TAKE ATOMS IN ORDER B-D-F, A RIGHT HAND SCREW HAS THUMB IN +1
C         DIRECTION
C*
C     IF THE ATOM NUMBER D (OR F) IS NEGATIVE, THE ANGLE E (OR G) WILL
C     BE REPLACED BY THE EXACT TETRAHEDRAL ANGLE, AND D (OR F)
C     REPLACED BY ITS ABSOLUTE VALUE.
C*
C     SOME INPUT EXAMPLES WILL HELP TO CLARIFY MATTERS
C     ASSUME CARD COLUMNS ARE
C     123456789012345678901234567890123456789012345678901234567890123456
C*
C     WATER MOLECULE
C*
C     H2O
C      0 1
C        8
C        1   1 0.96
C        1   1 0.96          2 105.
C     BLANK CARD
C*
C     THE TITLE IS 'H2O'
C     THE CHARGE IS ZERO AND THE MULTIPLICITY 1
C     AFTER THE TITLE AND CHARGE AND MULTIPLICITY CARDS THE FIRST
C     Z MATRIX CARD NEEDS ONLY THE ATOMIC NUMBER
C        8
C     TO DEFINE THE POSITION OF ATOM 1
C     THE SECOND
C        1   1 0.96
C     SPECIFIES THAT AN ATOM ... ATOM NUMBER 2 ... OF ATOMIC NUMBER 1
C     IS BONDED TO ATOM NUMBER 1 WITH A CONNECTING BOND LENGTH OF 0.96
C     ANGSTROMS
C     THE NEXT ... AND LAST ... Z MATRIX CARD
C        1   1 0.96          2 105.
C     SPECIFIES THAT ANOTHER ... ATOM NUMBER 3 ... HYDROGEN IS BONDED
C     TO ATOM 1 WITH A BONDLENGTH OF 0.96 ANGSTROMS
C     AND FORMS AN ANGLE OF 105 DEGREES WITH ATOM NUMBER 2
C*
C     CONSIDER NOW THE METHANOL MOLECULE IN A STAGGERED CONFORMATION
C     AS A SECOND AND MORE DIFFICULT EXAMPLE
C*
C     CH3OH
C      0 1
C        6
C        8   1 1.43
C        1   2 0.96          1 105.
C        1   1 1.09          2 109.5         3 180.          0
C        1   1 1.09          2 109.5         4 109.5        +1
C        1   1 1.09          2 109.5         4 109.5        -1
C     BLANK CARD
C*
C     THE FIRST THREE Z MATRIX CARDS ARE SIMILIAR TO THOSE OF THE H2O
C     EXAMPLE AND NEED NO FURTHER EXPLANATION
C     THE FOURTH CARD
C        1   1 1.09          2 109.5         3 180.          0
C     SPECIFIES THAT A HYDROGEN IS BONDED TO THE FIRST ATOM ... THE
C     CARBON ... WITH A BOND LENGTH OF 1.09 ANGSTROMS AND THAT IT FORMS
C     AN ANGLE WITH ATOM NUMBER 2 ... THE OXYGEN ... OF 109.5 DEGREES
C     ALSO ... AS SIGNIFIED BY A VALUE OF ZERO FOR THE H PARAMETER ...
C     IT FORMS A DIHEDRAL ANGLE WITH ATOM 3 OF 180 DEGREES INDICATING A
C     TRANS CONFORMATION
C     THE FIFTH AND SIXTH CARDS
C        1   1 1.09          2 109.5         4 109.5        +1
C        1   1 1.09          2 109.5         4 109.5        -1
C     ARE IDENTICAL EXCEPT FOR THE SIGN OF THE H PARAMETER
C     THESE HYDROGENS ARE BONDED TO ATOM 1 ... THE CARBON ... AND BOTH
C     MAKE AN ANGLE OF 109.5 DEGREES WITH ATOM 2 ... THE OXYGEN
C     IN ADDITION ... AS SIGNIFIED BY VALUES OF + AND - 1 FOR THE H
C     PARAMETER ... THEY MAKE 109.5 DEGREE ANGLES WITH ATOM 4 ... THE
C     OTHER METHYL HYDROGEN
C     A +1 VALUE FOR H SIGNIFIES THAT ATOM NUMBER 5 LIES ABOVE THE
C     PLANE FORMED BY ATOMS 1 2 AND 4
C     WHILE
C     A -1 ASSIGNS ATOM 6 TO LIE BELOW THIS PLANE
C*
C     A NEGATIVE ATOMIC NUMBER SIGNIFIES THE POSITION OF FLOATING
C     GAUSSIAN FUNCTIONS ('BOND' FUNCTIONS, THAT IS THEY ARE NOT
C     LOCATED ON AN ATOMIC CENTER LIKE THE USUAL MONSTERGAUSS ORBITALS).
C*
C     THE GEOMETRY BUILDING ROUTINE, BUILDZ, PLACES THE FIRST ATOM AT
C     THE ORIGIN AND THE SECOND ALONG THE Z AXIS. NORMALLY THE
C     THIRD ATOM DEFINES THE XZ PLANE (IE. IT MAY NOT LIE ON THE Z
C     AXIS). THE SOLE EXCEPTION IS FOR 3 ATOM MOLECULES, WHICH MAY BE
C     LINEAR.
C     ALL THE REMAINING ATOMS FOLLOW A RIGHT HANDED COORDINATE
C     SYSTEM.
C*
C     IN ORDER TO AID IN THE CONSTRUCTION OF DIFFICULT STRUCTURES
C     THE USE OF DUMMY ATOMS IS ENCOURAGED.
C     A 0 IN THE ATOMIC NUMBER FIELD SIGNIFIES THAT THE ATOM IS ONLY A
C     DUMMY ATOM. ALTHOUGH NEITHER DUMMY ATOMS NOR FLOATING ATOMS ARE
C     ACTUALLY USED IN THE CALCULATION, ONLY FLOATING ATOMS MAY HAVE
C     BASIS FUNCTIONS ASSOCIATED WITH THEM. BOTH ATOM TYPES ARE
C     RETAINED IN THE GEOMETRY SO THAT THE INPUT ATOM NUMBERS ARE USED
C     THROUGHOUT THE PROGRAM, AND TO FACILITATE THE TRANSFORMATION OF
C     THE FORCES TO INTERNAL COORDINATES. THEY ARE IDENTIFIED IN THE
C     OUTPUT AS 'X' AND 'BQ' RESPECTIVELY.
C     THERE MAY BE TROUBLE WITH THE FORCE OPTIMIZATION OF THE GEOMETRY
C     IF 2 'ATOMS' HAVE THE SAME INTERNAL COORDINATES - THIS WOULD
C     RESULT IF A DUMMY ATOM OR FLOATING FUNCTION WAS PLACED ON TOP
C     OF AN EXISTING ATOM, DUMMY ATOM OR FLOATING FUNCTION.
C     THE LAST ATOM IN THE Z MATRIX CANNOT BE A DUMMY ATOM.
C*
C     ONE FURTHER EXAMPLE ... WITHOUT MUCH EXPLANATION ... TO ILLUSTRATE
C     THIS FEATURE
C     THIS EXAMPLE WILL ALSO SERVE TO ILLUSTRATE THE PROCEDURE FOR THE
C     Z MATRIX OPTIMIZATION OF MOLECULAR GEOMETRY
C*
C     ETHYL CATION  H-BRIDGED STRUCTURE
C      1 1
C        6
C        6   1 1.5
C        0   1 1.0           2 170.
C        0   2 1.0           1 170.          3 0.            0
C        0   1 1.0           3 90.           2 180.          0
C        0   2 1.0           4 90.           1 180.          0
C        1   1 1.08          3 60.           5 90.          +1
C        1   1 1.08          3 60.           5 90.          -1
C        1   2 1.08          4 60.           6 90.          +1
C        1   2 1.08          4 60.           6 90.          -1
C        0   1 0.75          3 170.          2 0.            0
C        1  11 1.2           1 90.           3 180.          0
C     BLANK CARD
C*
C=GEOMETRY INPUT
C2FREE-FORMAT
C     ******************************************************************
C     FREE FORMAT Z MATRIX INPUT.
C     ******************************************************************
C*
C     THE TITLE AND CHARGE/MULTIPLICITY CARDS ARE READ AS DESCRIBED
C     ABOVE. EACH Z MATRIX CARD HAS THE SAME STRUCTURE AS DESCRIBED
C     ABOVE FOR THE FIXED FORMAT INPUT:
C
C     ELEMENT, N1, BL, N2, ALPHA, N3, BETA, N4
C
C     ELEMENT MAY BE THE ONE OR TWO CHARACTER CHEMICAL SYMBOL (E.G. C,
C     CL), THE ONE OR TWO CHARACTER CHEMICAL SYMBOL FOLLOWED
C     IMMEDIATELY BY AN IDENTIFYING INTEGER (E.G. C1, CL11), OR SIMPLY
C     THE ATOMIC NUMBER (E.G. 6, 17). DUMMY ATOMS ARE IDENTIFIED BY THE
C     SYMBOL 'X', FLOATING ATOMS BY 'BQ' (FLOATING ATOMS ARE GIVEN THE
C     ATOMIC NUMBER -1). A MAXIMUM OF 4 ALPHANUMERIC DIGITS IS
C     PERMITTED. IF A NUCLEUS IS TO REFERENCED BY LATER ATOMS, IT IS
C     NECESSARY THAT THE ALPHANUMERIC STRINGS BE UNIQUE - ONE WAY TO
C     ENSURE THIS IS TO APPEND THE ATOM NUMBER TO EACH CHEMICAL SYMBOL.
C     FOR COMPATIBILITY REASONS, THE CODE 'D*' MAY BE USED FOR
C     A DUMMY ATOM, AND THE CODE 'F*' MAY BE USED FOR A FLOATING ATOM,
C     ALTHOUGH MONSTERGAUSS WILL REFER TO SUCH ATOMS INTERNALLY AND
C     ON SOME OUTPUT AS 'X' AND 'BQ' RESPECTIVELY, SO THE USE OF
C     THE LATTER SYMBOLS IS STRONGLY RECOMMENDED.
C
C     N1 SPECIFIES THE (PREVIOUSLY DEFINED) NUCLEUS TO WHICH THE
C     CURRENT ATOM (N) IS CONSIDERED TO BE ATTACHED. N1 MAY BE EITHER
C     AN ALPHANUMERIC STRING MATCHING THE ELEMENT FIELD OF A PREVIOUS
C     Z MATRIX CARD, OR SIMPLY THE NUMBER OF THE ATOM.
C
C     BL IS THE BOND LENGTH IN ANGSTROMS FROM N TO N1, EXPRESSED AS
C     EITHER A STRING OF UP TO 8 ALPHANUMERIC CHARACTERS (CALLED A
C     VARIABLE), OR A FLOATING POINT NUMBER CONTAINING A DECIMAL POINT.
C
C     N2 SPECIFIES THE (PREVIOUSLY DEFINED) NUCLEUS FOR WHICH THE BOND
C     ANGLE N-N1-N2 WILL BE GIVEN. N2 MAY BE EITHER AN ALPHANUMERIC
C     STRING MATCHING THE ELEMENT FIELD OF A PREVIOUS Z MATRIX CARD, OR
C     SIMPLY THE NUMBER OF THE ATOM.
C
C     ALPHA IS THE N-N1-N2 BOND ANGLE IN DEGREES, EXPRESSED AS EITHER
C     A STRING OF UP TO 8 ALPHANUMERIC CHARACTERS (CALLED A VARIABLE),
C     OR A FLOATING POINT NUMBER CONTAINING A DECIMAL POINT.
C*
C     THE INTERPRETATION OF THE REMAINING THREE FIELDS DEPENDS ON THE
C     VALUE OF N4, WHICH MUST BE AN INTEGER (NOT A VARIABLE).
C*
C     N4 IS 0 OR OMITTED:
C
C     N3 SPECIFIES THE (PREVIOUSLY DEFINED) NUCLEUS FOR WHICH THE
C     DIHEDRAL ANGLE N-N1-N2-N3 WILL BE GIVEN. N3 MAY BE EITHER AN
C     ALPHANUMERIC STRING MATCHING THE ELEMENT FIELD OF A PREVIOUS
C     Z MATRIX CARD, OR SIMPLY THE NUMBER OF THE ATOM.
C
C     BETA IS THE N-N1-N2-N3 DIHEDRAL ANGLE IN DEGREES, EXPRESSED AS
C     EITHER A STRING OF UP TO 8 ALPHANUMERIC CHARACTERS (CALLED A
C     VARIABLE), OR A FLOATING POINT NUMBER CONTAINING A DECIMAL POINT.
C     THE CONVENTION FOR THE SIGN OF BETA IS TO LOOK ALONG THE N1-N2
C     BOND FROM THE N1 END, WITH A POSITIVE DIHEDRAL ANGLE BEING A
C     COUNTERCLOCKWISE ROTATION OF N AWAY FROM N3.
C*
C     N4 IS +1 OR -1:
C
C     N3 SPECIFIES THE (PREVIOUSLY DEFINED) NUCLEUS FOR WHICH THE BOND
C     ANGLE N-N1-N3 WILL BE GIVEN. N3 MAY BE EITHER AN ALPHANUMERIC
C     STRING MATCHING THE ELEMENT FIELD OF A PREVIOUS Z MATRIX CARD, OR
C     SIMPLY THE NUMBER OF THE ATOM.
C
C     BETA IS THE N-N1-N3 BOND ANGLE IN DEGREES, EXPRESSED AS EITHER A
C     STRING OF UP TO 8 ALPHANUMERIC CHARACTERS (CALLED A VARIABLE), OR
C     A FLOATING POINT NUMBER CONTAINING A DECIMAL POINT. IN THIS CASE,
C     THERE ARE TWO POSSIBILITIES FOR N4, +1 AND -1, WHICH SERVE TO
C     PLACE THE NEW ATOM ABOVE OR BELOW THE N1-N2-N3 PLANE. THE
C     CONVENTION IS TO WRAP THE FINGERS OF THE RIGHT HAND AROUND THE
C     ATOMS IN THE ORDER N1 TO N2 TO N3 - THE THUMB DEFINES THE +1
C     SIDE OF THE PLANE.
C*
C     IF NO VARIABLES HAVE BEEN USED IN THE BL, ALPHA OR BETA FIELDS,
C     THE Z MATRIX IS CONVERTED TO THE STANDARD FORM ABOVE. ALL FURTHER
C     LINKS WILL TREAT THIS EXACTLY AS A FIXED FORMAT INPUT RUN.
C
C     THE VALUES OF THE VARIABLES ARE GIVEN AFTER THE BLANK CARD IN TWO
C     SECTIONS ('OPTIMIZED VARIABLES' AND 'CONSTANTS'), IN THE FORM:
C     VARIABLE = VALUE
C     WHERE VARIABLE IS AN UP TO 8 CHARACTER STRING USED IN THE BL,
C     ALPHA OR BETA FIELDS, AND VALUE IS A FLOATING POINT NUMBER.
C     ALTERNATIVELY, VALUE MAY BE THE STRING 'TETRA' TO INDICATE THAT
C     THE TETRAHEDRAL ANGLE IS TO BE SUBSTITUTED. THE LIST OF VARIABLES
C     TO BE OPTIMIZED IS TERMINATED BY A BLANK CARD, THEN THE LIST OF
C     VARIABLES TO BE HELD CONSTANT IS GIVEN, ALSO TERMINATED BY A
C     BLANK CARD. IF THERE ARE NO 'CONSTANTS', I.E. ALL THE VARIABLES
C     ARE TO BE OPTIMIZED, THEN THE BLANK CARD FOLLOWING THE LIST
C     OF CONSTANTS IS ALSO OMITTED (THIS MEANS THAT ALL THE VARIABLES
C     WERE SPECIFIED IN THE 'OPTIMIZE' SECTION).
C     FOR NON-OPTIMIZATION RUNS, THE VARIABLES MAY STILL BE SPLIT
C     INTO 'OPTIMIZE' AND 'CONSTANT' SECTIONS, OR ALL THE VARIABLES
C     MUST BE SPECIFIED IN THE 'OPTIMIZE' SECTION (EVEN THOUGH THERE
C     IS NO OPTIMIZATION TO BE PERFORMED).
C*
C     THE WATER AND METHANOL EXAMPLES MAY THUS BE WRITTEN:
C*
C     H2O
C      0 1
C     O1
C     H2  O1  ROH
C     H3  O1  ROH  H2  ALPHA
C     (BLANK)
C     ROH = 0.96
C     ALPHA = 105.0
C     (BLANK)
C*
C     CH3OH
C      0 1
C     C1
C     O2 C1 RCO
C     H3 O2 ROH C1 COH
C     H4 C1 RCH O2 OCH H3 180.0 0
C     H  C1 RCH O2 OCH H4 HCH   1
C     H  C1 RCH O2 OCH H4 HCH  -1
C     (BLANK)
C     RCO = 1.43
C     ROH = 0.96
C     RCH = 1.09
C     COH = 105.0
C     OCH = TETRA
C     HCH = TETRA
C     (BLANK)
C*
C     CH3OH
C      0 1
C     C1
C     O2 C1 RCO
C     H3 O2 ROH C1 COH
C     H4 C1 RCH O2 OCH H3 TAUH4 0
C     H  C1 RCH O2 OCH H4 HCH   1
C     H  C1 RCH O2 OCH H4 HCH  -1
C     (BLANK)
C     RCO = 1.43
C     ROH = 0.96
C     RCH = 1.09
C     COH = 105.0
C     OCH = TETRA
C     HCH = TETRA
C     (BLANK)
C     TAUH4 = 180.0
C     (BLANK)
C*
C     ADDITIONAL NOTES:
C
C     1) VARIABLES USED IN ALPHA AND BETA FIELDS MAY BE PRECEEDED BY A
C     NEGATIVE SIGN TO INDICATE THAT THE NEGATIVE OF THE VALUE IS TO BE
C     USED. FOR EXAMPLE -TAU, WITH TAU=60.0, WOULD USE -60.0 FOR THAT
C     Z MATRIX PARAMETER.
C
C     2) THE FREE FORMAT ENTRIES ARE NORMALLY SEPARATED BY ONE OR MORE
C     BLANKS, AND MAY CONTAIN NO IMBEDDED BLANKS. A COMMA MAY ALSO BE
C     USED TO SEPARATE THE Z MATRIX FIELDS, BUT IT MUST IMMEDIATELY
C     FOLLOW THE PARAMETER WITH NO INTERVENING BLANKS. FOR EXAMPLE 'C1,'
C     IS CORRECT, BUT 'C1 ,' IS NOT. LEADING BLANKS ARE ALWAYS IGNORED.
C     THE VARIABLE NAMES SHOULD BEGIN WITH A LETTER TO AVOID POSSIBLE
C     DIFFICULTIES.
C
C     3) FOR GEOMETRY OPTIMIZATION RUNS, THE Z MATRIX CANNOT BE
C     PRINTED OR PUNCHED IN THE FREE FORMAT MODE IF THE OPTIMIZATION
C     CONSTRAINTS DO NOT AGREE WITH THE USE OF THE VARIABLES IN THE Z
C     MATRIX. CONSIDERING THE METHANOL CASE ABOVE, IF THE THREE CH
C     BOND LENGTHS (OR THE THREE OCH ANGLES, OR THE TWO HCH ANGLES) ARE
C     ALLOWED TO VARY INDEPENDENTLY, THE RCH (OR OCH OR HCH) VARIABLE
C     MAY END UP TRYING TO REPRESENT SEVERAL DIFFERENT VALUES
C     SIMULTANEOUSLY. IF THE OPTIMIZATION CONSTRAINTS DO NOT AGREE WITH
C     THE Z MATRIX VARIABLES, THE FINAL Z MATRIX IS NOT PRINTED/PUNCHED
C     IN FREE FORMAT. FOR THE METHANOL CASE, IF A COMPLETE OPTIMIZATION
C     IS DESIRED, THE LAST TWO CARDS COULD BE CHANGED TO:
C     H C1 RCH56 O2 OCH56 H4 HCH  1
C     H C1 RCH56 O2 OCH56 H4 HCH -1
C     WHICH WOULD RECOGNIZE THAT THE LATTER TWO H ATOMS ARE EQUIVALENT,
C     BUT DIFFERENT FROM H4. THIS SHOULD BE REFLECTED IN THE
C     OPTIMIZATION CONSTRAINTS GIVEN TO THE OPTIMIZATION LINKS. HOWEVER,
C     IF THE INTENTION IS TO OPTIMIZE THE METHYL GROUP MAINTAINING THE
C     LOCAL C3V SYMMETRY, THEN THE ORIGINAL Z MATRIX IS ACCEPTABLE.
C     NOTE THAT THE DEFAULT MODE OF OPERATION IS TO CONSTRAIN ALL THOSE
C     PARAMETERS USING THE SAME VARIABLE NAME TO BE OPTIMIZED TOGETHER,
C     AND TO FIX ALL PARAMETERS NOT USING A VARIABLE (IE. CONSTANTS).
C     THUS THE METHANOL EXAMPLE ABOVE WOULD GIVE A C3V CONSTRAINED
C     METHYL GROUP, WHILE THE MODIFIED VERSION WOULD GIVE THE ABSOLUTE
C     MINIMUM CS STRUCTURE, IF THE DEFAULT OPTIMIZATION CONSTRAINTS ARE
C     USED. THE DEFAULT CONSTRAINTS CAN ALWAYS BE OVER-RIDDEN BY USING
C     THE GOPT=READ OPTION ON THE *MOL CARD, AND SUPPLYING THE
C     OPTIMIZATION CONSTRAINT CARDS.
C
C     4) FOR THE FIRST ATOM, ONLY THE ELEMENT FIELD IS NEEDED. FOR THE
C     SECOND ATOM, THE ELEMENT, N1 AND BL FIELDS ARE REQUIRED. FOR THE
C     THIRD ATOM, THE ELEMENT, N1, BL, N2 AND ALPHA FIELDS ARE REQUIRED.
C     FOR THE REMAINING ATOMS, ALL FIELDS ARE REQUIRED, ALTHOUGH N4 MAY
C     BE OMITTED IF A 0 VALUE IS DESIRED.
C
C     5) ALTHOUGH IT IS NOT STRICTLY NECESSARY, THE INTERPRETATION OF
C     THE MOLECULAR ORBITAL SYMMETRIES IS SIMPLIFIED GREATLY IF
C     THE ORIGIN IS CHOSEN AS THE CENTER OF INVERSION (IF THE
C     MOLECULE POSSESSES ONE), THE Z (OR X OR Y) AXIS IS CHOSEN
C     AS THE PRINCIPAL AXIS OF ROTATION (IF THE MOLECULE POSSESSES
C     ONE), AND/OR ONE OF THE CARTESIAN PLANES (XY, XZ OR YZ) IS
C     USED AS THE MOLECULAR PLANE (IF THE MOLECULE POSSESSES ONE).
C     THUS THE WATER EXAMPLE (ABOVE) WOULD BE BETTER BUILT AS:
C
C     H2O
C      0 1
C     O1
C     X2  O1  1.0
C     H2  O1  ROH  X2  ALPHA
C     H3  O1  ROH  X2  ALPHA  H3  180.0
C     (BLANK)
C     ROH = 0.96
C     ALPHA = 127.5
C     (BLANK)
C
C     WHERE THE Z AXIS IS NOW ONE OF THE C2 AXES (OTHERWISE THE
C     C2 AXIS WOULD HAVE POINTED OFF IN THE XZ PLANE).
C*
C=GEOMETRY INPUT
C1OPTIMIZATION
C1CONSTRAINTS
C1VARIATION-CARDS
C     *****************************************************************
C     Z MATRIX OPTIMIZATION OF MOLECULAR GEOMETRY
C     *****************************************************************
C*
C     IN THE ETHYL CATION EXAMPLE ABOVE, THE GEOMETRICAL PARAMETERS ARE
C     THE BOND LENGTHS 1.5 TO 1.2  PARAMETER NUMBERS 1 TO 11
C     THE FIRST SET OF ANGLES 170. TO 90.  PARAMETER NUMBERS 12 TO 21
C     AND
C     THE LATTER SET 0. TO 180.  PARAMETER NUMBERS 22 TO 30
C     OR
C     3 * NATOMS - 6 PARAMETERS IN ALL ... COUNTING DUMMY ATOMS THAT IS.
C     TO COMPLETELY DEFINE THE GEOMETRY OF THE SYMMETRICALLY BRIDGED
C     ... C2V SYMMETRY ... ETHYL CATION WE NEED ONLY THE FOLLOWING
C     PARAMETER SETS:
C     1 AND 10
C     6 7 8 AND 9
C     11
C     12 13 AND 20
C     AND
C     16 17 18 AND 19
C*
C     FOLLOWING THE SPECIFICATION OF THE INITIAL Z MATRIX VARIATIONS
C     MAY BE INTRODUCED IN THE FOLLOWING MANNER
C     THERE ARE THREE POSSIBLE CASES
C*
C     1  VARY A SINGLE PARAMETER
C     FOR EXAMPLE THE DISTANCE BETWEEN THE BRIDGING HYDROGEN AND THE
C     CARBON CARBON BOND
C     PARAMETER NUMBER 11
C     VARY BY 0.05 ANGSTROMS
C     REMEMBER THE CARD COLUMNS ARE NUMBERED
C     123456789012345678901234567890123456789012345678901234567890123456
C      11                                          0.05
C     THE PROGRAM WILL CALCULATE TWO ADDITIONAL POINTS ... THE ENERGY
C     CORRESPONDING TO THE ORIGINAL Z MATRIX HAS ALREADY BEEN EVALUATED
C     AND STORED ... AND FIT THEM TO A PARABOLA
C     IF THE PROJECTED MINIMUM DOES NOT LIE INSIDE THE INTERVAL COVERED
C     BY THE THREE POINTS, THE PROGRAM WILL CONTINUE TO TRY TO BRACKET
C     THE PROJECTED MINIMUM BY CALCULATING MORE POINTS, SAVING AS MANY
C     PREVIOUS VALUES AS POSSIBLE, UP TO THE LIMIT GIVEN BY IOP(16).
C     IN THIS EXAMPLE THE FIRST POINT WILL BE 1.2+0.05 OR 1.25
C     IF THIS GIVES A BETTER ENERGY THAN THE ORIGINAL Z MATRIX THEN THE
C     NEXT ALTERATION TO THE Z MATRIX WILL BE IN THE SAME DIRECTION
C     1.2+0.05+0.05 OR 1.30
C     IF HOWEVER IT GIVES A POORER ENERGY THEN THE PROCEDURE WILL
C     STEP BACKWARDS
C     1.2-0.05 OR 1.15
C     WHICHEVER HAPPENS ... A MINIMUM WILL BE PROJECTED AND IF THE
C     MINIMUM LIES WITHIN THE RANGE COVERED (EITHER 1.20-1.30 OR
C     1.15-1.25), THE ENERGY CORRESPONDING TO IT WILL BE CALCULATED.
C     IF NOT, EXTRA POINTS WILL BE CALCULATED UNTIL THE PROJECTED
C     MINIMUM DOES LIE WITHIN THE INTERVAL COVERED.
C     THE PROGRAM IS THEN READY TO READ IN ADDITIONAL VARIATION CARDS
C*
C     2  VARY A SET OF PARAMETERS SIMULTANEOUSLY ALL BY THE SAME AMOUNT
C     FOR EXAMPLE THE TWO HCH ANGLES ... OR IN PRACTICE THE FOUR
C     H-C-DUMMY ATOM ANGLES
C      16 17 18 19                                 1.0
C     THE SAME PROCEDURE AS ABOVE WILL BE FOLLOWED
C     THIS TIME HOWEVER THE FOUR GEOMETRICAL PARAMETERS WILL BE
C     DEALT WITH SIMULTANEOUSLY
C*
C     3  VARY A SET OF PARAMETERS TOGETHER BUT BY DIFFERENT AMOUNTS
C     FOR EXAMPLE VARY THE CARBON CARBON BOND LENGTH MAKING CERTAIN AT
C     THE SAME TIME THAT THE BRIDGING HYDROGEN REMAINS IN THE MIDDLE
C       1999                                       0.02
C      10                                          0.01
C     IN THIS CASE PARAMETER 1 IS VARIED BY 0.02 AND AT THE SAME
C     TIME ... THE FACT THAT ADDITIONAL SIMULTANEOUS VARIATION CARDS
C     FOLLOW IS GIVEN BY THE 999 ... PARAMETER 10 IS TO BE VARIED BY
C     HALF OF THAT OR 0.01 ANGSTROMS THUS ASSURING THAT IT REMAINS IN
C     THE MIDDLE.  CAUTION ... ONLY 3 PARAMETER CARDS FOR SIMULTANEOUS
C     VARIATION ARE ALLOWED.
C*
C     AS MANY VARIATION CARDS AS NEEDED MAY BE USED THE LIST BEING
C     TERMINATED BY A BLANK CARD (CARD FORMAT IS 15I3,F10.4).
C     THE VARIATION CARDS MUST BE SUPPLIED, EVEN FOR THE FREE FORMAT
C     Z MATRIX INPUT.
C*
C     THE Z MATRIX FOR THE FINAL OPTIMIZED GEOMETRY MAY BE PUNCHED IN
C     EITHER FREE FORMAT OR STANDARD FORMAT - SEE IOP(15).
C*
C=GEOMETRY INPUT
C1OPTIMIZATION
C2RESTART
C     ******************************************************************
C     RESTART OF Z MATRIX GEOMETRY OPTIMIZATION
C     ******************************************************************
C
C     CONSIDER THE FOLLOWING JOB ... AN STO-3G OPTIMIZATION OF THE
C     METHYL RADICAL BY THE Z MATRIX METHOD:
C
C     CARD COLUMNS
C             1234567890123456789012345678901234567890123456789012345678
C
C    (1)      *MOLGOPT,METHOD=ZM,UHF
C    (2)      METHYL RADICAL
C    (3)       0 2
C    (4)         6
C    (5)         1   1 1.09
C    (6)         1   1 1.09          2 118.
C    (7)         1   1 1.09          2 118.          3 118.          1
C    (8)      (BLANK)
C    (9)        1  2  3                                    0.01
C   (10)        4  5  6                                    0.5
C   (11)      (BLANK)
C
C     THIS JOB COULD PRODUCE THE FOLLOWING DECK AS PUNCHED OUTPUT ...
C     BUT ONLY IF RUN USING THE *IOP OPTION TO SET IOP(15)=2.
C
C     CARD COLUMNS
C             1234567890123456789012345678901234567890123456789012345678
C*
C    (1)                -39.0767558518
C    (2)        1  2  3                                        0.0100
C    (3)                -39.0760215884
C    (4)                -39.0770013045
C    (5)         6
C    (6)         1   1    1.080000
C    (7)         1   1    1.080000   2    118.0000
C    (8)         1   1    1.080000   2    118.0000   3    118.0000   1
C    (9)
C   (10)      ****
C   (11)                -39.0770013534
C   (12)        4  5  6                                        0.5000
C   (13)                -39.0770048638
C   (14)                -39.0769567591
C   (15)         6
C   (16)         1   1    1.080000
C   (17)         1   1    1.080000   2    118.2840
C   (18)         1   1    1.080000   2    118.2840   3    118.2840   1
C   (19)
C   (20)      ****
C   (21)                -39.0770096299
C
C     NOTE THE INFORMATION THAT WAS PUNCHED ... THE TOTAL ENERGY OF
C     EACH POINT, THE VARIATION CARDS USED, AND AT THE CONCLUSION
C     OF A PARAMETER OPTIMIZATION ... A NEW Z MATRIX WITH THE OPTIMUM
C     VALUE OF THAT PARAMETER INCLUDED, IN THE SAME FORMAT AS IT WAS
C     READ IN (SEE IOP(5)).
C
C     NOW SUPPOSE THE HCH ANGLE OPTIMIZATION WAS CLOBBERED AFTER
C     THE FIRST POINT WAS CALCULATED ... SUCH THAT RESTART CARDS 1-13
C     WERE PUNCHED.
C     A RESTART DECK WOULD LOOK LIKE THIS ...
C
C     CARD COLUMNS
C             1234567890123456789012345678901234567890123456789012345678
C
C    (1)      *MOLGOPT,METHOD=ZM,UHF
C             *IOP
C                1  14   1 RESTART OF Z MATRIX OPTIMIZATION
C                0   0   0
C    (2)      METHYL RADICAL   RESTART OF GEOMETRY OPTIMIZATION
C    (3)       0 2
C    (4)         6
C    (5)         1   1    1.080000
C    (6)         1   1    1.080000   2    118.0000
C    (7)         1   1    1.080000   2    118.0000   3    118.0000   1
C    (8)
C    (9)                -39.0770013534
C   (10)        4  5  6                                        0.5000
C   (11)                -39.0770048638
C   (12)      ****
C   (13)      (BLANK)
C
C     EXPLANATION OF CARDS
C
C     CARDS 1      CONTROL CARDS FOR RESTART.
C     CARDS 4-8    RESTART CARDS 5-9
C     CARDS 9-11   RESTART CARDS 11-13
C     CARD 12      RESTART CARD 10 ... INDICATES THAT NO MORE ENERGY
C                  VALUES ARE TO BE EXPECTED ... THIS CARD IS USED AS
C                  A SEPARATOR IN THE PUNCHED RESTART CARDS FOR USER
C                  CONVENIENCE
C     CARD 13      IF ADDITIONAL VARIATION CARDS ARE DESIRED AS A
C                  CONTINUATION OF THE INTERRUPTED OPTIMIZATION RUN,
C                  INSERT THEM HERE BEFORE THE BLANK CARD.
C
C     NOTE: FOR A RESTART UP TO 3 PREVIOUS ENERGIES MAY BE GIVEN.
C     SINCE THE OPTIMIZATION OF A SET OF PARAMETERS MAY USE MORE THAN
C     3 POINTS TO AVOID EXTRAPOLATION, READ IN ONLY THE POINTS
C     INDICATED BY THE OUTPUT AS BEING USEFUL.
C     THE FORMAT FOR THE ENERGY RESTART CARDS IS (A4,F20.10).
C
C=GEOMETRY INPUT
C1SURFACE-SCAN
C2GEOMETRY
C     ******************************************************************
C     POTENTIAL SURFACE SCAN
C     ******************************************************************
C
C     AS AN EXAMPLE OF THIS FEATURE, CONSIDER THE FOLLOWING ... WE
C     DESIRE A GRID ON THE METHYLENE SURFACE FOR 3 DIFFERENT BOND
C     LENGTHS, AT 2 ANGLES.
C
C     CARD COLUMNS
C             1234567890123456789012345678901234567890123456789012345678
C
C    (1)      *MOLSS,UHF
C    (2)      CH2   POTENTIAL SURFACE SCAN
C    (3)       0 3
C    (4)         6
C    (5)         1   1 1.09
C    (6)         1   1 1.09          2 100.
C    (7)      (BLANK)
C    (8)       3 2
C    (9)        1  2                                       0.01
C   (10)        3                                          2.0
C
C     EXPLANATION OF CARDS
C
C     CARDS 2-7    Z MATRIX INPUT (ORIGINAL FORMAT)
C     CARD 8       NUMBER OF POINTS DESIRED FOR EACH PARAMETER SET - IN
C                  THIS CASE, 3 POINTS FOR PARAMETER SET 1, 2 FOR SET 2.
C                  THE CARD FORMAT IS (4I2).
C     CARD 9       VARIATION CARD FOR FIRST PARAMETER SET.
C     CARD 10      VARIATION CARD FOR SECOND PARAMETER SET.
C
C     NOTE THAT THERE IS NO BLANK CARD FOLLOWING THE VARIATION CARDS.
C
C     THE SIX CALCULATED POINTS WILL HAVE (CH,HCH) = (1.09,100.),
C     (1.10,100.),(1.11,100.),(1.09,102.),(1.10,102.),(1.11,102.).
C
C     UP TO 4 PARAMETER SETS MAY BE SCANNED.
C     EACH PARAMETER SET MAY CONTAIN UP TO 3 VARIATION CARDS - SEE
C     ABOVE FOR DETAILS CONCERNING VARIATION CARD TYPES.
C*
C2ELECTRIC FIELD
C2FIELD
C     ******************************************************************
C     ELECTRIC FIELD SCAN
C     ******************************************************************
C
C     TO IMPLEMENT THIS FEATURE, BOTH SS=F AND FI=E MUST BE SPECIFIED
C     ON THE *MOL CARD. THE SCAN IS OVER THE POLAR COORDINATES PHI
C     ( THE ANGLE FROM THE Z AXIS TO THE FIELD VECTOR ) , THETA ( THE
C     ANGLE FROM THE X AXIS TO THE PROJECTION OF THE FIELD VECTOR IN
C     THE X-Y PLANE ) AND R ( THE MAGNITUDE OF THE FIELD VECTOR ) .
C
C     INPUT REQUIRED
C     CARD 1      NUMBER OF VALUES OF PHI, THETA , R FOR WHICH THE
C                 SCAN IS TO BE PERFORMED, AND IFILE (IN 4I2 FORMAT).
C                 IFILE IS THE UNIT NUMBER TO WHICH THE DATA MAY BE
C                 PUNCHED.  FOR EXAMPLE, IF IFILE IS 7 THE DATA WILL
C                 BE PUNCHED TO UNIT 7.  THE FILE SHOULD BE BLOCKED AND
C                 FORMATTED AS WITH UNIT "IPUNCH".  IF IFILE IS NOT
C                 SPECIFIED, OR GIVEN A VALUE OF ZERO, DATA WILL NOT BE
C                 PUNCHED TO ANY FILE.
C     CARD 2      INITIAL VALUES OF THE POLAR COORDINATES. PHI AND
C                 THETA SHOULD BE IN DEGREES, WITH R IN VOLTS/CM .
C                 ( IN 3F12.0 FORMAT ).
C     CARD 3      INCREMENTS FOR PHI, THETA AND R. ( SAME UNITS AND
C                 FORMAT AS CARD 2 ).
C
C     FOR EXAMPLE
C
C   (1)      *MOL SS=F,FI=E
C   (2)      H2 ELECTRIC FIELD SCAN
C   (3)       0 1
C   (4)      1
C   (5)      1 1 1.00
C   (6)
C   (7)       3 2 2
C   (8)      0.00         0.00        5.142251E8
C   (9)      45.0         90.0        5.142251E8
C
C     IF CARD (7) IS SPECIFIED AS   3 2 2 7 THEN THE DATA IS PUNCHED
C     TO UNIT 7.
C
C     NOTES: TO EVERY CARTESIAN POINT THERE MAY NOT BE A UNIQUE SET OF
C            POLAR COORDINATES. THUS, IT IS POSSIBLE THAT THE SAME
C            POINT IS CALCULATED MORE THAN ONCE. THIS IS LEFT TO THE
C            USERS DISCRETION. HOWEVER, RECURSIVE POINTS FROM PHI=0.00
C            OR 180.00 AT ANY VALUE OF THETA ARE REMOVED BY THE PROGRAM.
C            ALSO REMOVED ARE POINTS WITH R LESS THAN OR EQUAL TO ZERO.
C
C     RESULTS IN IFILE HAVE THE FOLLOWING FORMAT:
C
C     CARD 1      HAS THE X, Y AND Z COMPONENTS OF THE ELECTRIC FIELD
C                 IN ATOMIC UNITS, AS WELL AS PHI (IN DEGREES), THETA
C                 (IN DEGREES), AND R (IN VOLTS/CM).
C     CARD 2      HAS THE TOTAL ENERGY (IN HARTREES), EDIFF (IN
C                 HARTREES) WHICH IS THE DIFFERENCE BETWEEN THE
C                 ENERGY IN THE FIELD AND THE ZERO FIELD ENERGY, THE X,
C                 Y AND Z COMPONENTS OF THE DIPOLE MOMENTS (IN DEBYES),
C                 AND THE TOTAL DIPOLE MOMENT (IN DEBYES).
C*
C2SCRFT
C     ******************************************************************
C     SCRFT SCAN
C     ******************************************************************
C
C     TO IMPLEMENT THIS OPTION, BOTH SS=F AND FI=S MUST BE SPECIFIED ON
C     THE *MOL CARD. THE SCAN IS OVER THE RADIUS ( IN ANGSTROMS )
C     AND THE DIELECTRIC CONSTANT.
C
C     INPUT REQUIRED
C
C     CARD 1      NUMBER OF VALUES FOR THE RADIUS AND THE DIELECTRIC
C                 CONSTANT ( IN 2I2 ).
C     CARD 2      INITIAL VALUES FOR THE RADIUS AND THE DIELECTRIC
C                 CONSTANT ( IN 2F12.0 )
C     CARD 3      INCREMENT FOR THE RADIUS AND THE DIELECTRIC CONSTANT
C                 ( IN 2F12.0 ).
C
C     FOR EXAMPLE
C
C   (1)      *MOL SS=F,FI=S
C   (2)      H2 SCRFT SCAN
C   (3)       0 1
C   (4)      1
C   (5)      1 1 1.00
C   (6)
C   (7)       3 2
C   (8)      0.500        1.00
C   (9)      0.100        1.00
C*
C=GEOMETRY INPUT
C1ANGSTROMS
C1BOHR
C     ******************************************************************
C     DIRECT COORDINATE INPUT.
C     ******************************************************************
C
C     TITLE (FREE FIELD).
C     CHARGE AND MULTIPLICITY (2I2) ... SEE CONVENTION ABOVE.
C     IAN,X,Y,Z (I4,3F20.10).
C     IAN IS THE ATOMIC NUMBER. X, Y AND Z ARE THE COORDINATES FOR THIS
C     ATOM. FLOATING ATOMS (SEE ABOVE) ARE PERMITTED, AND THE END OF
C     COORDINATE INPUT IS INDICATED BY AN ATOMIC NUMBER OF 0.
C
C     ******************************************************************
C*
C=GEOMETRY INPUT
C1ELECTRIC-FIELD
C1FIELD
C     ******************************************************************
C     APPLY AN EXTERNAL ELECTRIC FIELD
C     ******************************************************************
C
C     THE EXTERNAL FIELD TO BE APPLIED IS READ IN AFTER THE BLANK CARD
C     FOR THE GEOMETRY SPECIFICATION, AND CONSISTS OF ONE CARD WITH
C     THE X, Y AND Z COMPONENTS OF THE FIELD (IN VOLTS/CM), IN 3F12.0
C     FORMAT.
C
C     FOR EXAMPLE, TO APPLY A FIELD OF 1000.0 V/CM IN THE +Y DIRECTION,
C     THE CARD
C     0.0         1000.0      0.0
C     WOULD DO THE JOB.
C
C     NOTE: THIS OPTION CAN NOT BE APPLIED TO A CHARGED SYSTEM.
C           IF THE OPTION SSCAN=FIELD IS USED, THIS INPUT IS NOT
C           USED. SEE ELECTRIC FIELD SCAN FOR DETAILS.
C
C=GEOMETRY INPUT
C1SCRFT
C1SOLVENT-FIELD
C     ******************************************************************
C     SELF-CONSISTENT REACTION FIELD THEORY:
C     CALCULATION OF A MOLECULE IN A SOLVENT
C     ******************************************************************
C
C     TO APPLY THE SELF-CONSISTENT REACTION FIELD THEORY (SCRFT),
C     THE RADIUS OF THE CAVITY TO CONTAIN THE MOLECULE (IN ANGSTROMS),
C     AND THE DIELECTRIC CONSTANT OF THE SOLVENT ARE REQUIRED. THESE
C     VALUES ARE READ IN 2F12.0 FORMAT FROM A CARD WHICH FOLLOWS THE
C     BLANK CARD AT THE END OF THE GEOMETRY INPUT.
C
C     FOR EXAMPLE, FOR A CAVITY OF RADIUS 5.0 ANGSTROMS AND DIELECTRIC
C     CONSTANT OF 15.0, THE FOLLOWING CARD WOULD BE REQUIRED:
C     5.0         15.0
C
C     NOTE: THIS THEORY CAN NOT BE APPLIED TO A CHARGED SYSTEM.
C           IF THE OPTION SSCAN=FIELD IS USED, THIS INPUT IS NOT USED.
C           SEE SCRFT SCAN FOR DETAILS.
C
C=GEOMETRY INPUT
C1ATOMIC-MASSES
C1ATOMIC-WEIGHTS
C     ******************************************************************
C     REPLACEMENT ATOMIC MASSES.
C     ******************************************************************
C
C     THERE ARE TWO METHODS OF SPECIFYING REPLACEMENT ATOMIC MASSES:
C
C     1) SELECT A REPLACEMENT MASS NUMBER FOR ONLY A SPECIFIC ATOM
C        NUMBER. THIS IS DONE BY GIVING THE ATOM NUMBER FOLLOWED BY THE
C        DESIRED MASS NUMBER ON ONE INPUT LINE (FREE FORMAT). FOR
C        EXAMPLE, TO SELECT MASS NUMBER 2 FOR THE 7'TH ATOM, ENTER:
C        7 2
C
C     2) SELECT A REPLACEMENT MASS NUMBER FOR ALL ATOMS WITH THE SAME
C        ATOMIC NUMBER SIMULTANEOUSLY. THIS IS DONE BY GIVING THE ATOM
C        SYMBOL FOLLOWED BY THE DESIRED MASS NUMBER ON ONE INPUT LINE
C        (FREE FORMAT). FOR EXAMPLE, TO SELECT MASS NUMBER 2 FOR
C        ALL HYDROGEN ATOMS, ENTER:
C        H 2
C
C     THESE INPUT LINES IMMEDIATELY FOLLOW THE BLANK CARD AFTER THE
C     Z-MATRIX (AFTER THE VARIABLE VALUES IF ANY), OR AFTER THE
C     BLANK CARD FOR DIRECT COORDINATE INPUT.
C
C     AS MANY REPLACEMENT LINES AS NEEDED MAY BE GIVEN, ENDING THE
C     LIST OF REPLACEMENTS WITH A BLANK CARD. THE LAST REPLACEMENT
C     MASS NUMBER GIVEN FOR EACH ATOM WILL BE USED.
C
C=GEOMETRY INPUT
C1OPTIONS
C     ******************************************************************
C     OPTIONS ... IOP( )
C     ******************************************************************
C     IOP(13) ... INITIAL ENTRY OR CONTINUATION
C     0  FIRST ENTRY (SINGLE CALCULATION, GEOMETRY OPT OR SURFACE SCAN)
C     1  CONTINUATION OF Z MATRIX GEOMETRY OPTIMIZATION RUN
C     2  CONTINUATION OF POTENTIAL SURFACE SCAN
C     3  FIRST ENTRY AFTER CALL TO STANDARD GEOMETRY.
C
C     IOP(14) ... RESTART OF A Z MATRIX OPTIMIZATION.
C     0  NORMAL RUN
C     1  RESTART - IOP(18) MAY ALSO BE USED TO RECOVER THE OPTIMUM
C     GEOMETRY FOR THE LAST PARAMETER SET THAT WAS COMPLETED.
C
C     IOP(15) ... SHALL WE PUNCH RESTART CARDS
C     0  NO (THIS IS USED FOR THE STANDARD ROUTE).
C     1  PUNCH THE FINAL Z MATRIX ONLY.
C     2  YES.
C
C     IOP(16) ... MAXIMUM NUMBER OF POINTS FOR THE OPTIMIZATION OF ONE
C                 SET OF PARAMETERS
C     N  ALLOW 2*N+6 POINTS TO BRACKET THE MINIMUM (IF N>6, N IS SET
C        TO 100000)
C
C     IOP(17) ... READ INPUT GEOMETRY FORMAT FROM A CARD.
C     0  NO - USE THE STANDARD FORMAT.
C     1  YES - READ A FORMAT STATEMENT FROM ONE CARD, INCLUDING THE
C     LEFT AND RIGHT PARENTHESES. FOR EXAMPLE, THE GAUSSIAN 70/76
C     Z MATRIX FORMAT CARD WOULD BE:
C     (I3,I4,F7.4,I4,F11.4,I4,F11.4,I4)
C     THIS FORMAT CARD IS INSERTED AFTER THE CHARGE/MULTIPLICITY CARD.
C     THIS OPTION IS NOT APPLICABLE TO FREE FORMAT OR STANDARD GEOMETRY
C     RUNS.
C
C     IOP(18) ... RESTART THE GEOMETRY FROM THE DISK FILE.
C     0  NO.
C     1  YES - THE GEOMETRY FOR THE ORIGINAL STARTING POINT IS READ AS
C     USUAL, THEN UPDATED FROM THE RESTART FILE (FILE 1) OF UNIT IMAT.
C     FOR Z MATRIX OPTIMIZATIONS, THE OPTIMUM GEOMETRY FROM THE LAST
C     PARAMETER SET COMPLETED IS RESTORED; FOR OTHER OPTIMIZATION
C     METHODS, THE LATEST GEOMETRY IS RESTORED.
C
C     IOP(19) ... TYPE OF SURFACE SCAN TO BE PERFORMED.
C     0  GEOMETRY SURFACE SCAN.
C     1  FIELD SCAN.
C
C     IOP(20) ... NOT USED.
C
C     IOP(21) ... PRINT CONTROL.
C     0  NORMAL PRINTING.
C     1  ONLY PRINT INITIAL AND FINAL POINTS OF EACH PARAMETER
C     OPTIMIZATION. THIS IOP IS ALSO USED FROM GBOPT (LINK 0711) FOR
C     PRINT CONTROL IN BUILDZ.
C
C     IOP(22) ... CHOICE OF ATOMIC MASSES.
C     0  USE MASS OF MOST ABUNDANT ISOTOPE FOR EACH ATOM.
C     1  USE ABUNDANCE-AVERAGED ATOMIC WEIGHTS FOR EACH ATOM.
C     2  SET MASS OF MOST ABUNDANT ISOTOPE FOR EACH ATOM, THEN READ
C        REPLACEMENT VALUES.
C
C     IOP(23) ... DUMP ATOMIC MASS TABLES (ROUTINE FILMAS).
C     0  NO.
C     1  YES.
C
C     IOP(24) ... PERMIT ELECTRIC FIELD CALCS ON CHARGED SYSTEMS.
C     0  NO.
C     1  YES - IN THIS CASE, BOTH THE TOTAL ENERGY AND DIPOLE MOMENT
C        THAT ARE COMPUTED ARE NOT INVARIANT TO THE POSITION OF THE
C        MOLECULE IN 3D SPACE, BUT SOME DERIVED PROPERTIES (E.G.
C        THE POLARIZABILITY) ARE INVARIANT EVEN FOR CHARGED SYSTEMS.
C
C     IOP(25) TO IOP(60) ... NOT USED
C     ******************************************************************
C*
C     NOTE THAT THE TITLE AND MULTIPLICITY WERE ACTUALLY READ IN LNK1.
C     THE MAXIMUM NUMBER OF ATOMS IS #NA.
C==
C
C/
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C#
C     PARAMETER (NA=#NA)
C     PARAMETER (NS=#NS)
C     PARAMETER (NO=#NO)
C##
      PARAMETER (NA= 36)
      PARAMETER (NS=120)
      PARAMETER (NO=125)
C###
      PARAMETER (NA3=3*NA, NZ=NA3-6)
      PARAMETER (ZERO=0.0D0, ONE=1.0D0, TWO=2.0D0)
C
      CHARACTER TITLE*72,IELEM*4,NAMES*8
C
      COMMON /A/ IOP(99)
      COMMON /A/ NATOMS,ICHARG,MULTIP,IAN(NA),NAE,NBE,NE,NBASIS,C(NA,3)
      COMMON /A/ ANTOAU,FCONST(2),FCCONV,ICDUM(401)
C
      COMMON/ZMAT/IZ(NA,4),BL(NA),ALPHA(NA),BETA(NA),
     1 IPAR(15,3),NIPAR(3),NPAR,NSTEP,DX(3),NUM,NUMB,
     2 LBL(NA),LALPHA(NA),LBETA(NA),IZMASS(NA),ZMASS(NA)
      COMMON/ZMATC/TITLE,IELEM(NA),NAMES(NZ)
C?IBM/CDC/VAX/UNX
      COMMON/C706C/IGOPT(NZ),CGOPT(NZ),IBOPT(NS,5),RESTRT(NA3,2)
C??
C?GLD/GBR
C     COMMON/C202B/IGOPT(NZ),CGOPT(NZ),IBOPT(NS,5),RESTRT(NA3,2)
C??
      COMMON/SSCAN/NUMSS(4),NSSTEP(4),NUMSET(4),NSSPAR(3,4),
     1 ISSPAR(15,3,4),SSDX(3,4)
      COMMON/GEN/EDUM(2),ENERGY,ENERGP,ENERGM,ENERG0,DCONV,SPIN(2),
     1 FXAU,FYAU,FZAU,FE,EMOL,ESOL,DPOLE(4),VCM
      COMMON/IO/IN,IOUT,IPUNCH,IODUM(14),NFILE(100,2)
C
      CHARACTER*4 ISTAR,IWORD,IBLANK,IZ2
      CHARACTER*72 IFMT,IFMT1,IFMT2
C
      DIMENSION ENER(3)
      DIMENSION IZZ(3),Z(3)
      DIMENSION FILLB(NO,2)
C
      EQUIVALENCE (IGOPT(1),GOPT), (NUMSS(1),ANUMSS),
     1 (RESTRT(1,1),FILLB(1,1))
C
C     DTOR2 CONVERTS DEG**-2 TO RADIANS**-2
      DATA THRESH/1.0D-7/
      DATA TORAD/1.74532925199433D-2/
      DATA DTOR2/3282.80635D0/
      DATA ISTAR/'****'/, IBLANK/'    '/, IZ2/'*Z  '/
      DATA THREE/3.0D0/, EIGHT/8.0D0/
      DATA MAXPAR/15/
      DATA IFMT1/'(2I4,F12.6,2(I4,F12.4),I4,T73,A2,I6)'/
      DATA IFMT2/'(I4,3F20.10)'/
C
 1000 FORMAT (/'0ENERGY COMPONENTS:   NUCLEAR:',F17.9,',   ELECTRONIC:',
     1 F17.9)
 1010 FORMAT(' FORCE CONSTANT =',1PD16.8,' MDYNE*ANGSTROM/RADIAN**2'/)
 1020 FORMAT('0INSUFFICIENT VARIATION CARDS FOR GEOMETRY OPTIMIZATION ',
     1 'RESTART OR POTENTIAL SURFACE SCAN')
 1030 FORMAT(4X,F20.10)
 1040 FORMAT(15I3,F10.4)
 1050 FORMAT(/'0OPTIMIZATION TERMINATED'/'0FINAL ENERGY IS',
     1 F14.6,' HARTREES')
 1060 FORMAT(/'0RESTART ERROR - ENERGY CARD',I2,' IS NOT CORRECT')
 1070 FORMAT(A4,F20.10)
 1080 FORMAT('0SECOND DERIVATIVE INDICATES MAXIMUM FOUND')
 1090 FORMAT(' INTERVAL',F10.4,6X,'VARIABLES ... ',15I4)
 1100 FORMAT(' FORCE CONSTANT =',1PD16.8,' MDYNE/ANGSTROM'/)
 1110 FORMAT(1X)
 1120 FORMAT(/'0END OF POTENTIAL SURFACE SCAN')
 1130 FORMAT('1POTENTIAL SURFACE SCAN',5X,'(',3(I2,','),I2,') POINTS')
 1140 FORMAT('1POINT',I3,' OF GEOMETRY OPTIMIZATION (SECOND POINT ',
     1 'ON PARABOLA)'//)
 1150 FORMAT('1POINT',I3,' OF GEOMETRY OPTIMIZATION - POSITION OF ',
     1 'PROJECTED MINIMUM RELATIVE TO CENTRAL POINT (POINT',I3,')'/)
 1160 FORMAT(1X)
 1170 FORMAT('1POINT',I3,' OF GEOMETRY OPTIMIZATION (THIRD POINT ON ',
     1 'PARABOLA)'/)
 1180 FORMAT(1X,F10.4,'   FOR INTERVAL',F10.4,6X,'VARIABLES ... ',15I4)
 1190 FORMAT('1')
 1200 FORMAT(/'0MINIMUM STILL LIES OUTSIDE INTERVAL AFTER',I8,
     1 ' POINTS')
 1210 FORMAT('0PROJECTED MINIMUM IS OUTSIDE OPTIMIZATION RANGE ... ',
     1 'DO 1 MORE POINT'/' POINT',I3,' IS NOW INITIAL POINT AND POINT',
     2 I3,' IS SECOND POINT'/)
 1220 FORMAT('0PROJECTED MINIMUM IS OUTSIDE OPTIMIZATION RANGE ... ',
     1 'DO 2 MORE POINTS'/' POINT',I3,' IS NOW INITIAL POINT'/)
 1230 FORMAT('0PROJECTED MINIMUM IS OUTSIDE OPTIMIZATION RANGE ... ',
     1 'START AGAIN FROM PROJECTED MINIMUM')
 1240 FORMAT('0PROJECTED MINIMUM IS OUTSIDE OPTIMIZATION RANGE ... ',
     1 'DO 2 MORE POINTS'/' POINT',I3,' IS NOW INITIAL POINT'/
     2 ' DIRECTION OF OPTIMIZATION VECTOR REVERSED'/)
 1250 FORMAT('0PROJECTED MINIMUM IS OUTSIDE OPTIMIZATION RANGE ... ',
     1 'START AGAIN FROM PROJECTED MINIMUM'/
     2 ' DIRECTION OF OPTIMIZATION VECTOR REVERSED')
 1260 FORMAT(/'0PREDICTED ENERGY AT MINIMUM IS',F16.6,' HARTREES'//)
 1270 FORMAT(/'0RESTART OF GEOMETRY OPTIMIZATION ... ENERGY OF INITIAL',
     1 ' POINT IS',F19.9//)
 1280 FORMAT('0ENERGY AT POINT',I2,' IS',F19.9)
 1290 FORMAT('1GEOMETRY OPTIMIZATION CHECK RUN'/'0PARAMETER SETS TO ',
     1 'OPTIMIZE:'//)
 1300 FORMAT('0POTENTIAL SCAN CHECK RUN'//)
 1310 FORMAT('0PROJECTED MINIMUM IS OUTSIDE OPTIMIZATION RANGE ... ',
     1 'DO 1 MORE POINT'/' POINT',I3,' IS NOW INITIAL POINT AND POINT',
     2 I3,' IS SECOND POINT'/' DIRECTION OF OPTIMIZATION VECTOR ',
     3 'REVERSED'/)
 1320 FORMAT(/'0TOO MANY ATOMS (MAXIMUM IS',I4,').')
 1330 FORMAT('0LAST ATOM IS A DUMMY ATOM - REMOVE IT')
 1340 FORMAT('0ERROR: SURFACE SCAN REQUIRES NO POINTS')
 1350 FORMAT('***Z',A68,'*Z     0')
 1360 FORMAT(/'0PARAMETER SET',I2/)
 1370 FORMAT(' GEOMETRY RESTARTED FROM DISK FILE'/)
 1380 FORMAT('0Z MATRIX PUNCHED TO UNIT',I4)
 1390 FORMAT(A72)
 1400 FORMAT('0*** THE ABOVE SET OF CONSTRAINTS DOES NOT PERMIT FREE ',
     1 'FORMAT Z MATRIX OUTPUT WITH THE PRESENT SET OF Z MATRIX ',
     2 'VARIABLES'/)
 1410 FORMAT('0REPLACEMENT GEOMETRY INPUT FORMAT: ',A72/)
 1420 FORMAT(4I2)
 1430 FORMAT(3F12.0)
 1440 FORMAT(//'0AN EXTERNAL ELECTRIC FIELD IS PRESENT IN THIS ',
     1 'CALCULATION:'//17X,'FIELD COMPONENTS IN VOLTS/CM',27X,
     2 'FIELD COMPONENTS IN ATOMIC UNITS'//16X,'X',14X,'Y',14X,
     3 'Z',25X,'X',14X,'Y',14X,'Z'//7X,3(1PD15.5),10X,3(0PF15.6))
 1450 FORMAT(/'0THIS CALCULATION INCLUDES SOLVENT EFFECTS. PARAMETERS',
     1 ' ARE:'/'0RADIUS IN ANGSTROMS =',F8.4,5X,'DIELECTRIC CONSTANT =',
     2 F9.4,5X,'CALCULATED COUPLING CONSTANT =',1PD12.5)
 1460 FORMAT(/'0INVALID PARAMETER IN SCRFT. RADIUS =',1PD12.5,
     1 'DIELECTIC CONSTANT =',D12.5)
 1470 FORMAT ('0CHARGED MOLECULES CAN NOT BE HANDLED WITH EITHER THE ',
     1 'EXTERNAL FIELD OR SCRFT OPTIONS.')
 1480 FORMAT ('0SCRFT ENERGIES:   EMOL:',F17.9,',   ESOL:',F17.9/
     1 ' DIPOLE MOMENT:   (X)',1PD13.5,'   (Y)',D13.5,'   (Z)',
     2 D13.5,'   (TOTAL)',D13.5,'  DEBYE')
 1490 FORMAT ('0*** INVALID COMBINATION: IOP(5) =',I3,' AND IOP(13) =',
     1 I3)
 1500 FORMAT('0THE VALUE OF',I4,' FOR PARAMETER',I4,' IN THE SCAN',
     1 ' INPUT IS INVALID.')
 1510 FORMAT (/'0ELECTRIC FIELD SCAN'/
     1 '0NUMBER OF POINTS TO BE CALCULATED FOR PHI =',I3,', FOR',
     2 ' THETA =',I3,', AND FOR R =',I3)
 1520 FORMAT(' INITIAL FIELD VECTOR IN POLAR COORDINATES: PHI =',
     1 F12.6,' DEGREES, THETA =',F12.6,' DEGREES, AND R =',1PD12.5,
     2 ' VOLTS/CM')
 1530 FORMAT(' INCREMENT FOR PHI =',F12.6,', FOR THETA =',F12.6,', AND',
     1 ' FOR R =',1PD12.5)
 1540 FORMAT('0END OF FIELD SCAN ')
 1560 FORMAT (/'0SELF-CONSISTENT REACTION FIELD SCAN'/
     1 '0NUMBER OF POINTS TO BE CALCULATED FOR RADIUS =',I3,' AND ',
     2 'FOR DIELECTRIC CONSTANT =',I3)
 1570 FORMAT(' INITIAL VALUE OF RADIUS =',F12.6,' AND INITI',
     1 'AL VALUE OF DIELECTRIC CONSTANT =',F12.6)
 1580 FORMAT(' INCREMENT FOR RADIUS =',F12.6,' AND INCREMENT FOR ',
     1 'DIELECTRIC CONSTANT =',F12.6)
 1590 FORMAT('1SUMMARY OF RESULTS'/' ******************'//' FORMAT USED'
     1 /'0   RADIUS    DIELECTRIC',6X,'FE'/'     E(Q)',8X,'EDIF',8X,
     2 'EMOL',8X,'ESOL',6X,'X-DIPOLE    Y-DIPOLE    Z-DIPOLE  TOTAL ',
     3 'DIPOLE'/'0X-, Y-, Z- AND TOTAL DIPOLE ARE IN DEBYES'/
     4 '0',3F12.6)
 1600 FORMAT('1SUMMARY OF RESULTS'/' ******************'//' FORMAT USED'
     1 /'0  X-FIELD     Y-FIELD     Z-FIELD       PHI        THETA',10X,
     2 'R'/'    ENERGY      EDIFF      X-DIPOLE  ',
     3 '  Y-DIPOLE    Z-DIPOLE  TOTAL DIPOLE'/'0',1PD12.5,2D12.5)
 1610 FORMAT(' ',8F12.6)
 1620 FORMAT('0',5F12.6,1PD12.5)
 1630 FORMAT('0THE POINT PHI =',F12.6,', THETA =',F12.6,' AND R =',
     1 1PD12.6,' HAS BEEN REMOVED ')
 1640 FORMAT('0INVALID PARAMATERS FOR SCRFT SCAN: RADIUS = ',F12.8,
     1 ' OR DIELECTRIC = ',F12.8)
 1650 FORMAT('0PARAMATER ',I2,' OF SCAN IS INVALID.  NUMBER OF POINTS',
     1 ' TO BE CALCULATED IS ',I3,' BUT INCREMENT = ',F12.8)
 1660 FORMAT('0*** NOTE *** : VALUES OF DIPOLE MOMENTS ARE FOR SCF ',
     1 'ONLY AND NOT FOR CI.')
 1670 FORMAT('**** SUMMARY OF FIELD SCAN ****'/3F12.6)
 1680 FORMAT(6F12.6)
 1690 FORMAT('0FIELD COMPONENTS ARE IN A.U.'/' PHI AND THETA ARE ',
     1'IN DEGREES'/' R IS IN VOLTS/CM'/' EDIF IS THE DIFFERENCE',
     2 ' BETWEEN THE PRESENT ENERGY AND THE ZERO FIELD ENERGY',
     3 ' ( IN HARTREES )'/' X, Y, AND Z COMPONENTS OF DIPOLE',
     4 ' MOMENT AS WELL AS TOTAL DIPOLE MOMENT ARE IN DEBYES')
 1700 FORMAT('0RESULTS OF ELECTRIC FIELD SCAN PUNCHED TO UNIT',I3,'.')
 1710 FORMAT('0SORRY, SCRFT SCAN NOT MODIFIED TO PUNCH RESULTS TO ',
     1 'ANY UNITS.')
 1720 FORMAT(5F12.6,1PD12.5)
 1730 FORMAT ('0*** SURFACE SCANS MUST INVOLVE AT LEAST 2 POINTS -',
     1 ' THIS SCAN HAS BEEN TERMINATED.')
 1740 FORMAT (/'0*** NOTE: BOTH THE TOTAL ENERGY AND DIPOLE MOMENT',
     1 ' THAT ARE COMPUTED ARE NOT INVARIANT TO THE POSITION OF'/5X,
     2 'THE MOLECULE IN 3D SPACE, BUT SOME DERIVED PROPERTIES (E.G.',
     3 ' THE POLARIZABILITY) ARE INVARIANT EVEN FOR CHARGED SYSTEMS.')
C*
      ICHK=0
      IF(IOP(10).EQ.0)ICHK=1
      IOP21=IOP(21)
      KEY=0
C     COPY FORMAT INTO ARRAY IFMT.
      IF(IOP(5).GE.2)GO TO 600
      IFMT = IFMT1
      IF(IOP(5).EQ.0 .AND. IOP(13).EQ.0)GO TO 25
      IF(IOP(13).NE.0.OR.IOP(17).NE.1)GO TO 8
C     READ USER FORMAT.
      READ(IN,1390)IFMT
      WRITE(IOUT,1410)IFMT
      GO TO 8
C*
C     DIRECT COORDINATE INPUT.
C*
  600 IFMT = IFMT2
      IF (IOP(13).EQ.2 .AND. IOP(19).EQ.1) GO TO 900
      IF (IOP(13) .NE. 0) GO TO 640
      IF(IOP(17).NE.1)GO TO 620
C     READ USER FORMAT.
      READ(IN,1390)IFMT
      WRITE(IOUT,1410)IFMT
  620 J=NA+1
      DO 630 I=1,J
      READ(IN,IFMT)IANZ,Z
      IF(IANZ.EQ.0)GO TO 30
      IAN(I)=IANZ
      C(I,1)=Z(1)
      C(I,2)=Z(2)
  630 C(I,3)=Z(3)
C     TOO MANY ATOMS.
      WRITE(IOUT,1320)NA
      IOP(1)=-2
      RETURN
C     COMBINATION OF OPTIONS 5 AND 13 IS INVALID.
  640 WRITE (IOUT,1490)
      IOP(1) = -2
      RETURN
C*
C     FOR THE INITIAL ENTRY INTO VGEOM, IOP(13) WILL BE 0 OR 3.
C     IS THIS A RESTART ... IF SO IOP(14) WILL BE NON-ZERO.
C
    8 I=IOP(13)+1
      GO TO (10,40,400,31),I
C
C     INITIAL ENTRY:
C     READ IN
C     Z MATRIX ELEMENTS.
C     BLANK CARD.
C
   10 READ(IN,IFMT)IAN(1)
      IZ(1,1)=0
      IZ(1,2)=0
      IZ(1,3)=0
      IZ(1,4)=0
      BL(1)=ZERO
      ALPHA(1)=ZERO
      BETA(1)=ZERO
      I=1
C
   20 I=I+1
      READ(IN,IFMT)IANZ,(IZZ(J),Z(J),J=1,3),K
      IF(IZZ(1).EQ.0)GO TO 30
      IAN(I)=IANZ
      IZ(I,1)=IZZ(1)
      IZ(I,2)=IZZ(2)
      IZ(I,3)=IZZ(3)
      IZ(I,4)=K
      BL(I)=Z(1)
      ALPHA(I)=Z(2)
      BETA(I)=Z(3)
      IF(I.LE.NA)GO TO 20
      WRITE(IOUT,1320)NA
      IOP(1)=-2
      RETURN
C
C     FREE FORMAT INPUT.
C
   25 CALL FREEZ
      IF(IOP(1).NE.0)RETURN
      GO TO 31
   30 NATOMS=I-1
   31 IF(IAN(NATOMS).NE.0)GO TO 35
      WRITE(IOUT,1330)
      IOP(1)=-2
      RETURN
C
C     SET OPTIMIZATION COUNTER NSTEP
C
   35 NSTEP=0
C
C     SET ATOMIC MASSES.
C
      CALL FILMAS (IOP, IN, IOUT, IAN, NATOMS, IZMASS, ZMASS)
      IF (IOP(1) .NE. 0) RETURN
C
C     RESTART THE GEOMETRY FROM THE DISK.
C
      IF(IOP(18).EQ.0)GO TO 820
      WRITE(IOUT,1370)
      CALL TREAD(1,GOPT,NFILE(1,1),1,NFILE(1,1),1,0)
      K=0
      T=ONE
      IF(IOP(5).EQ.2)T=T/ANTOAU
      DO 800 J=1,3
      DO 800 I=1,NATOMS
      K=K+1
  800 C(I,J)=RESTRT(K,1)*T
      IF(IOP(5).GE.2)GO TO 820
      K=0
      DO 810 I=1,NATOMS
      IZ(I,2)=IABS(IZ(I,2))
      IZ(I,3)=IABS(IZ(I,3))
      K=K+1
      BL(I)=RESTRT(K,2)
      K=K+1
      ALPHA(I)=RESTRT(K,2)
      K=K+1
  810 BETA(I)=RESTRT(K,2)
      BL(1)=ZERO
C     CHECK FOR FREE FORMAT INPUT CHANGED TO STANDARD FORMAT.
      IF(ALPHA(1).NE.ZERO)IOP(5)=1
      ALPHA(1)=ZERO
C
C     FORM COORDINATE ARRAY C.
C
  820 CALL BUILDZ
      IF(IOP(3).EQ.0)GO TO 830
      IF (ICHARG.NE.0 .AND. IOP(24).NE.1) GO TO 510
      IF (IOP(19) .EQ. 1) GO TO 830
      IF(IOP(3).EQ.2)GO TO 825
C
C     INPUT FIELD COMPONENTS.
C
      READ(IN,1430)FXVCM,FYVCM,FZVCM
C     CONVERT VOLTS/CM TO ATOMIC UNITS OF FIELD.
      FXAU=FXVCM/VCM
      FYAU=FYVCM/VCM
      FZAU=FZVCM/VCM
      WRITE(IOUT,1440)FXVCM,FYVCM,FZVCM,FXAU,FYAU,FZAU
      IF (ICHARG .NE. 0) WRITE (IOUT,1740)
      GO TO 830
C
C     INPUT RADIUS IN ANGSTROMS AND DIELECTRIC CONSTANT (SCRFT).
C
  825 READ(IN,1430)RADIUS,DIEL
      IF(RADIUS.GT.ZERO .AND. DIEL.GE.ONE)GO TO 827
      WRITE(IOUT,1460)RADIUS,DIEL
      IOP(1)=-2
      RETURN
C     CALCULATE COUPLING CONSTANT
  827 FE=TWO*((DIEL-ONE)/(TWO*DIEL+ONE))/((RADIUS*ANTOAU)**3)
      WRITE(IOUT,1450)RADIUS,DIEL,FE
      IF (ICHARG .NE. 0) GO TO 510
C
C     COUNT NUMBER OF ENERGY EVALUATIONS DURING OPTIMIZATION.
C
  830 NUMB=1
      NUM=0
      IF(IOP(14).NE.0)GO TO 280
      IF(IOP(3).GT.0 .AND. IOP(19).EQ.1)GO TO 900
      RETURN
C*
C     GEOMETRY OPTIMIZATION
C*
C     BRANCH TO PROPER PHASE OF OPTIMIZATION
   40 IF(ICHK.NE.0)GO TO 105
      NSTEP=NSTEP+1
      NUMB=NUMB+1
      GO TO (50,110,140),NSTEP
C     CALCULATE SECOND POINT
C     IF DESIRED, PUNCH ENERGY FOR RESTART PROCEDURE
   50 IF(IOP(15).EQ.2)WRITE(IPUNCH,1030)ENERGY
      ENERG0=ENERGY
      IF(NUMB.GT.2)GO TO 60
   52 CALL ZPARAM(KEY,IZFREE)
      IF(KEY.EQ.0)GO TO 60
      IF(ICHK.EQ.0 .AND. IOP(5).EQ.0)CALL ZPRINT
      WRITE(IOUT,1050)ENERG0
      WRITE(IOUT,1000)EDUM(1),EDUM(2)
      IF (IOP(3) .EQ. 2) WRITE (IOUT,1480) EMOL, ESOL, DPOLE
      IF(KEY.LT.0)RETURN
C     RETURN TO SYSTEM WITH INSTRUCTION TO SKIP OUT OF OPTIMIZATION
C     LOOP
      NSTEP=0
      IOP(1)=1
      IF(ICHK.NE.0)RETURN
C     IF NO VARIATION CARDS WERE READ AT ALL, SKIP OPTIMIZATION STEP.
      IF(NUM.EQ.0)IOP(1)=2
   54 IF(IOP(15).EQ.0)RETURN
      WRITE(IPUNCH,1350)TITLE(1:68)
      DO 55 I=1,NATOMS
   55 WRITE(IPUNCH,IFMT)IAN(I),IZ(I,1),BL(I),IZ(I,2),ALPHA(I),
     1 IZ(I,3),BETA(I),IZ(I,4),IZ2,I
      WRITE(IPUNCH,1110)
      IF(IOP(5).EQ.0)CALL ZPUNCH
      WRITE(IOUT,1380)IPUNCH
      RETURN
C*
   60 IF(ICHK.EQ.0)WRITE(IOUT,1140)NUMB
      DO 70 J=1,NUM
      NIPARR=NIPAR(J)
   70 WRITE(IOUT,1090)DX(J),(IPAR(I,J),I=1,NIPARR)
      IF(IZFREE.EQ.0)GO TO 75
      WRITE(IOUT,1400)
      IOP(5)=1
   75 WRITE(IOUT,1160)
      IF(ICHK.NE.0)GO TO 52
C     ADD PARAMETER VARIATIONS TO Z MATRIX
   80 CALL ZSCALE(ONE)
C     FORM COORDINATE ARRAY C
      CALL BUILDZ
      IF(IOP(15).NE.2)RETURN
C     PUNCH VARIATIONS
      DO 100 J=1,NUM
  100 WRITE(IPUNCH,1040)(IPAR(I,J),I=1,MAXPAR),DX(J)
      RETURN
C     CHECK RUN ... READ IN ALL VARIATION CARDS
  105 WRITE(IOUT,1290)
      ENERG0=ZERO
      GO TO 52
C*
C     CALCULATE THIRD POINT ON PARABOLA
  110 IF(ENERGY.LE.ENERG0)GO TO 120
      ENERGP=ENERGY
      CON=-TWO
      NPAR=1
      GO TO 130
  120 ENERGM=ENERG0
      ENERG0=ENERGY
      CON=ONE
      NPAR=2
  130 IF(IOP21.EQ.0)WRITE(IOUT,1170)NUMB
  135 CALL ZSCALE(CON)
      CALL BUILDZ
      IF(IOP(15).EQ.2)WRITE(IPUNCH,1030)ENERGY
      RETURN
C*
C     FIT PARABOLA TO THE 3 POINTS, AND LOCATE ITS MINIMUM
  140 IF(NPAR.EQ.2)GO TO 160
      ENERGM=ENERGY
      CON=ONE
      J=NUMB-3
      GO TO 170
  160 ENERGP=ENERGY
      CON=-ONE
      J=NUMB-2
  170 WRITE(IOUT,1150)NUMB,J
      S=ENERGP+ENERGM-ENERG0-ENERG0
      T=DX(1)
      DER=S/(T*T)
      IF(DER.GT.ZERO)GO TO 175
      WRITE(IOUT,1080)
      IOP(1)=-2
      GO TO 54
  175 T=ENERGP-ENERGM
C     CALCULATE PREDICTED ENERGY AT MINIMUM
      EMIN=ENERG0-T*T/(EIGHT*S)
C     FIND STEP LENGTH FROM INITIAL POINT TO PROJECTED MINIMUM
C     PROJECTED MINIMUM IS AT POINT X(INITIAL) + EE*DX
      EE=-T/(S+S)
      DO 177 J=1,NUM
      NIPARR=NIPAR(J)
      T=EE*DX(J)
  177 WRITE(IOUT,1180)T,DX(J),(IPAR(I,J),I=1,NIPARR)
C     DOES MINIMUM LIE WITHIN RANGE COVERED BY THE THREE POINTS
      I=NUMB-1
      J=IOP(16)
      IF(J.GE.7)J=100000
      J=J+J+7
      IF(NPAR.EQ.2)GO TO 200
C     INITIAL STEP WAS IN WRONG DIRECTION
C     IF STEP LENGTH >= -1.0, THEN MINIMUM INSIDE INTERVAL
      IF(EE.GE.(-ONE))GO TO 260
      IF(NUMB.GE.J)GO TO 250
C     REVERSE DIRECTION VECTOR
      DO 180 J=1,NUM
  180 DX(J)=-DX(J)
      IF(EE.LT.(-TWO))GO TO 185
C     STEP >= -2.0, CALCULATE 1 MORE POINT
      J=I-2
      WRITE(IOUT,1310)J,I
      NSTEP=2
      T=ENERG0
      ENERG0=ENERGM
      ENERGM=T
      CON=ONE
      NPAR=2
      GO TO 135
  185 IF(EE.LT.(-THREE))GO TO 190
C     STEP >= -3.0, CALCULATE 2 MORE POINTS
      WRITE(IOUT,1240)I
      NSTEP=1
      ENERG0=ENERGM
      CON=ONE
      GO TO 135
C     START OPTIMIZATION FROM PROJECTED MINIMUM
  190 WRITE(IOUT,1250)
      CON=-(ONE+EE)
      GO TO 230
C     INITIAL STEP IN CORRECT DIRECTION
C     IF STEP LENGTH <= 1.0 THEN MINIMUM INSIDE INTERVAL
  200 IF(EE.LE.ONE)GO TO 260
      IF(NUMB.GE.J)GO TO 250
      IF(EE.GT.TWO)GO TO 210
C     STEP <= 2.0, CALCULATE 1 MORE POINT
      J=I-1
      WRITE(IOUT,1210)J,I
      NSTEP=2
      ENERGM=ENERG0
      ENERG0=ENERGP
      CON=ONE
      GO TO 135
  210 IF(EE.GT.THREE)GO TO 220
C     STEP <= 3.0, CALCULATE 2 MORE POINTS
      WRITE(IOUT,1220)I
      NSTEP=1
      ENERG0=ENERGP
      CON=ONE
      GO TO 135
C     START OPTIMIZATION FROM PROJECTED MINIMUM
  220 WRITE(IOUT,1230)
      CON=EE-ONE
  230 WRITE(IOUT,1260)EMIN
      CALL ZSCALE(CON)
      CALL BUILDZ
      IF(IOP(15).EQ.2)WRITE(IPUNCH,1030)ENERGY
      NSTEP=0
      RETURN
C     TOO MANY ENERGY CALCULATIONS DURING THE OPTIMIZATION
  250 I=J-1
      WRITE(IOUT,1200)I
      IOP(1)=-2
      GO TO 54
  260 FC1=DER*FCCONV
      FC2=FC1*DTOR2
      WRITE(IOUT,1260)EMIN
      IF(IPAR(1,1).LT.NATOMS)WRITE(IOUT,1100)FC1
      IF(IPAR(1,1).GE.NATOMS)WRITE(IOUT,1010)FC2
      CON=CON+EE
      CALL ZSCALE(CON)
C     RESET OPTIMIZATION COUNTER
      NSTEP=0
      NUMB=1
C     SET PRINTING ON FOR FINAL Z MATRIX.
      IOP(21)=0
      CALL BUILDZ
C     CREATE THE RESTART FILE.
      K=0
      DO 840 J=1,3
      DO 840 I=1,NATOMS
      K=K+1
  840 RESTRT(K,1)=C(I,J)
      K=0
      DO 850 I=1,NATOMS
      K=K+1
      RESTRT(K,2)=BL(I)
      K=K+1
      RESTRT(K,2)=ALPHA(I)
      K=K+1
  850 RESTRT(K,2)=BETA(I)
      RESTRT(2,2)=DFLOAT(IOP(5))
      CALL TWRITE(1,GOPT,NFILE(1,1),1,NFILE(1,1),1,0)
      IF(IOP(15).NE.2)RETURN
      WRITE (IPUNCH,1030) ENERGY
      DO 270 I=1,NATOMS
  270 WRITE(IPUNCH,IFMT)IAN(I),IZ(I,1),BL(I),IZ(I,2),ALPHA(I),IZ(I,3),
     1 BETA(I),IZ(I,4),IZ2,I
      WRITE (IPUNCH,1110)
      WRITE (IPUNCH,1070) ISTAR
      RETURN
C*
C     RESTART PROCEDURE
  280 READ(IN,1070)IWORD,ENER(1)
      IF(IWORD.NE.IBLANK)GO TO 390
      WRITE(IOUT,1270)ENER(1)
      CALL ZPARAM(KEY,IZFREE)
      IF(KEY.GT.0.OR.NUM.EQ.0)GO TO 500
      IF(KEY.LT.0)RETURN
      DO 300 J=1,NUM
      NIPARR=NIPAR(J)
  300 WRITE(IOUT,1090)DX(J),(IPAR(I,J),I=1,NIPARR)
      IF(IZFREE.EQ.0)GO TO 310
      WRITE(IOUT,1400)
      IOP(5)=1
  310 WRITE(IOUT,1110)
      NUMB=2
      READ(IN,1070)IWORD,ENER(2)
      IF(IWORD.EQ.ISTAR)GO TO 380
      IF(IWORD.NE.IBLANK)GO TO 390
      WRITE(IOUT,1280)NUMB,ENER(2)
      NUMB=3
      READ(IN,1070)IWORD,ENER(3)
      IF(IWORD.EQ.ISTAR)GO TO 350
      IF(IWORD.NE.IBLANK)GO TO 390
      WRITE(IOUT,1280)NUMB,ENER(3)
      NUMB=4
      READ(IN,1070)IWORD
      IF(IWORD.NE.ISTAR)GO TO 390
      IF(ENER(1).GE.ENER(2))GO TO 340
      ENERG0=ENER(1)
      ENERGP=ENER(2)
      ENERGM=ENER(3)
      CON=ZERO
      GO TO 170
  340 ENERGM=ENER(1)
      ENERG0=ENER(2)
      ENERGP=ENER(3)
      CON=ONE
      GO TO 170
  350 NSTEP=2
      IF(ENER(1).GE.ENER(2))GO TO 370
      ENERG0=ENER(1)
      ENERGP=ENER(2)
      CON=-ONE
      NPAR=1
      GO TO 130
  370 ENERGM=ENER(1)
      ENERG0=ENER(2)
      CON=TWO
      NPAR=2
      GO TO 130
  380 ENERG0=ENER(1)
      NSTEP=1
      WRITE(IOUT,1140)NUMB
      GO TO 80
C
C     RESTART ERROR
  390 WRITE(IOUT,1060)NUMB
      IOP(1)=-2
      RETURN
C*
C     POTENTIAL SURFACE SCAN SECTION
C*
  400 IF(IOP(19).EQ.1)GO TO 900
      IF(NSTEP.NE.0)GO TO 460
      READ(IN,1420)NUMSS
      WRITE(IOUT,1130)NUMSS
      NSETS=0
      DO 410 J=1,4
      IF(NUMSS(J).EQ.0)GO TO 420
      NUMB=NUMB*NUMSS(J)
      NSETS=J
  410 NSSTEP(J)=1
  420 IF(NSETS.EQ.0)GO TO 740
      IF (NUMB .LE. 1) THEN
         WRITE (IOUT,1730)
         IOP(1) = 2
         RETURN
      END IF
      IF(ICHK.NE.0)WRITE(IOUT,1300)
      DO 450 K=1,NSETS
      WRITE(IOUT,1360)K
      CALL ZPARAM(KEY,IZFREE)
      IF(KEY.GT.0)GO TO 500
      IF(KEY.LT.0)RETURN
      NUMSET(K)=NUM
      DO 450 J=1,NUM
      NIPARR=NIPAR(J)
      NSSPAR(J,K)=NIPARR
      DO 440 I=1,NIPARR
  440 ISSPAR(I,J,K)=IPAR(I,J)
      SSDX(J,K)=DX(J)
  450 WRITE(IOUT,1090)DX(J),(IPAR(I,J),I=1,NIPARR)
      WRITE(IOUT,1160)
      IF(ICHK.NE.0)GO TO 730
      GO TO 470
  460 CALL TREAD(7,ANUMSS,NFILE(7,1),1,NFILE(7,1),1,0)
  470 NUMB=NUMB-1
      IF(NUMB.LE.0)GO TO 730
      IF(NSTEP.EQ.1)WRITE(IOUT,1190)
      NSTEP=1
C     FIND NEXT POINT.
      K=1
  480 NSSTEP(K)=NSSTEP(K)+1
      IF(NSSTEP(K).LE.NUMSS(K))GO TO 490
C     END OF CURRENT PARAMETER SET - RESET TO STARTING VALUES.
      CON=-DFLOAT(NUMSS(K)-1)
      GO TO 700
C     INCREMENT THIS PARAMETER SET.
  490 CON=ONE
  700 NUM=NUMSET(K)
      DO 710 J=1,NUM
      NIPARR=NSSPAR(J,K)
      NIPAR(J)=NIPARR
      DX(J)=SSDX(J,K)
      DO 710 I=1,NIPARR
  710 IPAR(I,J)=ISSPAR(I,J,K)
      CALL ZSCALE(CON)
      IF(CON.EQ.ONE)GO TO 720
      NSSTEP(K)=1
      K=K+1
      GO TO 480
C     FORM COORDINATE ARRAY C
  720 CALL BUILDZ
      CALL TWRITE(7,ANUMSS,NFILE(7,1),1,NFILE(7,1),1,0)
      RETURN
C*
C     END OF POTENTIAL SURFACE SCAN
  730 WRITE(IOUT,1120)
C     GET OUT OF LOOP
      IOP(1)=1
      RETURN
C
C     ERROR EXITS.
C
C     ERROR ON NUMSS CARD.
  740 WRITE(IOUT,1340)
      IOP(1)=-2
      RETURN
C     NO VARIATION CARDS FOR RESTART/SCAN
  500 WRITE(IOUT,1020)
      IOP(1)=-2
      RETURN
C     CHARGE PRESENT WITH EXTERNAL FIELD OR SCRFT.
  510 WRITE (IOUT,1470)
      IOP(1) = -2
      RETURN
C
C     FIELD SCAN.
C
  900 NSS=3
      IF(IOP(3).EQ.2)NSS=2
      IF(NSTEP.NE.0)GO TO 930
C
C     INPUT NUMBER OF POINTS, IFILE, INITIAL VALUES, AND INCREMENTS.
C
      READ(IN,1420)(NUMSS(I),I=1,NSS),IFILE
      IF (IOP(3) .EQ. 1) WRITE(IOUT,1510)(NUMSS(I),I=1,NSS)
      IF (IOP(3) .EQ. 2) WRITE(IOUT,1560)(NUMSS(I),I=1,NSS)
      READ(IN,1430)(SSDX(1,I),I=1,NSS)
      IF (IOP(3) .EQ. 1) WRITE(IOUT,1520)(SSDX(1,I),I=1,NSS)
      IF (IOP(3) .EQ. 2) WRITE(IOUT,1570)(SSDX(1,I),I=1,NSS)
      READ(IN,1430)(SSDX(2,I),I=1,NSS)
      IF (IOP(3) .EQ. 1) WRITE(IOUT,1530)(SSDX(2,I),I=1,NSS)
      IF (IOP(3) .EQ. 2) WRITE(IOUT,1580)(SSDX(2,I),I=1,NSS)
      IF (IOP(3).EQ.1 .AND. IFILE.GT.0) WRITE(IOUT,1700)IFILE
      IF (IOP(3).EQ.2 .AND. IFILE.GT.0) WRITE(IOUT,1710)
C     STORE IFILE IN NUMSS( NSS + 1 ).
      NUMSS( NSS + 1 ) = IFILE
C     CHECK INPUT.
      DO 910 I=1,NSS
      NSSTEP(I)=1
      IF(NUMSS(I).EQ.0)NUMSS(I)=1
      IF(NUMSS(I).GE.0)GO TO 905
      WRITE(IOUT,1500)NUMSS(I),I
      IOP(1)=-2
  905 IF (NUMSS(I).GT.1 .AND. SSDX(2,I).NE.ZERO) GO TO 910
      IF (NUMSS(I).EQ.1 .AND. SSDX(2,I).EQ.ZERO) GO TO 910
      WRITE(IOUT,1650)I,NUMSS(I),SSDX(2,I)
      IOP(1)=-2
  910 NUMB=NUMB*NUMSS(I)
      IF (IOP(1) .EQ. -2) RETURN
      NSTEP=1
      IF (IOP(3) .EQ. 1) GO TO 920
      IF (SSDX(1,1).GT.ZERO .AND. SSDX(1,2).GE.ONE) GO TO 920
      WRITE(IOUT,1640)SSDX(1,1),SSDX(1,2)
      IOP(1)=-2
      RETURN
  920 IF(ICHK.EQ.0)CALL TWRITE(7,ANUMSS,NFILE(7,1),1,NFILE(7,1),1,0)
      RETURN
C
C     END OF ZERO FIELD POINT.
C
  930 IF(ICHK.NE.0)GO TO 995
      CALL TREAD(7,ANUMSS,NFILE(7,1),1,NFILE(7,1),1,0)
      IFILE = NUMSS( NSS + 1 )
      IF(NSTEP.NE.1)GOTO 933
      NSTEP=2
      ENERGP=ENERGY
      IF(IOP(3).EQ.2)GO TO 932
      WRITE(IOUT,1600)FXAU,FYAU,FZAU
      IF(IFILE .GT. 0)WRITE(IFILE,1670)FXAU,FYAU,FZAU
      GOTO 933
  932 WRITE(IOUT,1590)ZERO,ONE,ZERO
  933 ENERGM=ENERGY-ENERGP
C     WRITE OUT RESULTS.
      IF(IOP(3).EQ.2)GO TO 935
      WRITE(IOUT,1610)ENERGY,ENERGM,DPOLE
      IF(IFILE .GT. 0) WRITE(IFILE,1680)ENERGY,ENERGM,DPOLE
      GO TO 938
  935 WRITE(IOUT,1610)ENERGY,ENERGM,EMOL,ESOL,DPOLE
  938 NUMB=NUMB-1
      IF(NUMB.LT.0)GO TO 990
C     GET NEW POINT.
      DO 960 I=1,NSS
  960 SSDX(3,I)=SSDX(1,I)+DFLOAT(NSSTEP(I)-1)*SSDX(2,I)
C
      IF(IOP(3).NE.2)GO TO 970
      IF (SSDX(3,1).GT.ZERO .AND. SSDX(3,2).GE.ONE) GO TO 965
      WRITE(IOUT,1640)SSDX(3,1),SSDX(3,2)
      IOP(1)=-2
      RETURN
  965 FE=TWO*((SSDX(3,2)-ONE)/(TWO*SSDX(3,2)+ONE))/((SSDX(3,1)*ANTOAU)
     1 **3)
      WRITE(IOUT,1620)SSDX(3,1),SSDX(3,2),FE
      GO TO 980
C
C     DETERMINE IF THERE ARE ANY RECURSIVE POINTS, OR IF R=0.00.
C     IF SO, THEN REMOVE THE POINT.
C
  970 IF ( SSDX(3,3) .LT. THRESH ) GO TO 974
      S=DSIN( SSDX(3,1)*TORAD )
      IF ( S .GT.THRESH .OR. S .LT. -THRESH ) GO TO 978
      IF ( NSSTEP(2) .EQ. 1) GO TO 978
  974 WRITE(IOUT,1630)(SSDX(3,I),I=1,3)
      K=1
  976 NSSTEP(K)=NSSTEP(K) + 1
      IF ( NSSTEP(K) .LE. NUMSS(K) ) GO TO 938
      NSSTEP(K)=1
      K=K + 1
      IF (K .GT. 3) GO TO 990
      GO TO 976
C     WRITE OUT NEW POINT.
  978 T=SSDX(3,2)
      SSDX(3,2)=SSDX(3,2)*TORAD
      FXAU=SSDX(3,3)*DCOS(SSDX(3,2))*S/VCM
      FYAU=SSDX(3,3)*DSIN(SSDX(3,2))*S/VCM
      FZAU=SSDX(3,3)*DCOS( SSDX(3,1)*TORAD )/VCM
      WRITE(IOUT,1620)FXAU,FYAU,FZAU,SSDX(3,1),T,SSDX(3,3)
      IF(IFILE .GT. 0)WRITE(IFILE,1720)FXAU,FYAU,FZAU,
     1 SSDX(3,1),T,SSDX(3,3)
C     SET PARAMETRES NSSTEP FOR NEXT POINT.
  980 K=1
  940 NSSTEP(K)=NSSTEP(K)+1
      IF(NSSTEP(K).LE.NUMSS(K))GO TO 950
      NSSTEP(K)=1
      K=K+1
      IF(K .LE. NSS)GO TO 940
C
  950 CALL TWRITE(7,ANUMSS,NFILE(7,1),1,NFILE(7,1),1,0)
      RETURN
C
C     EXIT FROM SCAN
C
  990 IF (IOP(94) .NE. 0) WRITE(IOUT,1660)
      IF (IOP(3) .EQ. 1) WRITE(IOUT,1690)
      WRITE(IOUT,1540)
  995 IOP(1)=1
      RETURN
      END
