C     GL0301A      24 OCT 91                                         MRP
C?IBM/GLD/GBR/VAX/UNX
      SUBROUTINE GINPUT
C??
C?CDC
C     PROGRAM GINPUT
C??
C=BASIS SETS
C CHAPTER 5: BASIS SETS.
C **********
C
C1INTRODUCTION
C     LINK 0301
C*
C     --------------
C     U OF T VERSION
C     OCTOBER 1991
C     --------------
C*
C     SETUP PROGRAM FOR THE GAUSSIAN INTEGRAL PACKAGE
C*
C     GENERAL INPUT DATA LIMITATIONS
C*
C     #NS SHELLS ... SEE DEFINITION OF A SHELL IN COMMENT CARDS BELOW
C     TYPES S P SP D AND F ONLY
C     MAXIMUM OF 10 GAUSSIAN FUNCTIONS PER SHELL
C     BUT
C     MAXIMUM OF #NP GAUSSIANS IN TOTAL
C     #NB ATOMIC ORBITALS
C     #NA ATOMS (INCLUDING DUMMY AND FLOATING ATOMS).
C*
C     ******************************************************************
C*
C     INTERNAL BASIS SETS AVAILABLE:
C
C     BASIS                     CODE    ATOMS
C     ------------------------------------------------------------------
C     STO-NG,  N=1 TO 6         MN      H TO XE
C     STO-NG*                   MN*     NA TO AR
C
C     3-21G                     V3      H TO CA, GA TO SR, IN TO XE
C     3-21G*                    V3*     H TO CA, GA TO SR, IN TO XE
C     3-21G+                    V3+     H, LI TO F, NA TO AR
C     3-21G++                   V3++    H, LI TO F, NA TO AR
C
C     4-21G (PULAY)             P4      H, B TO F
C
C     4-21G                     V4      H TO NE
C     4-21G*                    V4*     H TO NE
C     4-21G**                   V4**    H TO NE
C
C     5-21G (IN PLACE OF 4-31G) E4      LI, BE
C     5-21G*                    E4*     LI, BE
C     5-21G**                   E4**    LI, BE
C
C     6-21G                     V6      H TO AR
C     6-21G*                    V6*     H TO AR
C     6-21G**                   V6**    H TO AR
C     6-21G+                    V6+     H, LI TO F, NA TO AR
C     6-21G++                   V6++    H, LI TO F, NA TO AR
C
C     4-31G                     E4      H TO NE, P, S, CL
C     4-31G*                    E4*     H TO NE
C     4-31G**                   E4**    H TO NE
C     4-31G+                    E4+     H, LI TO F, P, S, CL
C     4-31G++                   E4++    H, LI TO F, P, S, CL
C
C     5-31G                     E5      C, N, O, F
C     5-31G*                    E5*     C, N, O, F
C     5-31G**                   E5**    C, N, O, F
C
C     6-31G                     E6      H TO AR
C     6-31G*                    E6*     H TO AR
C     6-31G**                   E6**    H TO AR
C     6-31G+                    E6+     H, LI TO F, NA TO AR
C     6-31G++                   E6++    H, LI TO F, NA TO AR
C
C     6-311G                    C6      H TO NE
C     6-311G*                   C6*     H TO NE
C     6-311G**                  C6**    H TO NE
C     6-311G+                   C6+     H, LI TO F
C     6-311G++                  C6++    H, LI TO F
C
C=BASIS SETS
C1OPTIONS
C     ******************************************************************
C     OPTIONS ... IOP( )
C     ******************************************************************
C     IOP(13) ... NUMBER OF GAUSSIAN FUNCTIONS
C     N  STO-NG, N-M1G, N-M11G.
C        IF IOP(6)=0 AND IOP(13)=0, THE BASIS SET DEFAULTS TO STO-3G.
C        THE INTERNAL BASIS SET TYPES AVAILABLE ARE STO-NG (IOP(6)=0),
C        N-21G (IOP(6)=1), N-31G (IOP(6)=2), PULAY N-21G (IOP(6)=3) AND
C        N-311G (IOP(6)=4).
C        FOR INPUT OF A GENERAL BASIS SET THIS OPTION IS IGNORED.
C
C     IOP(14) ... SCALING FACTORS (SEE NOTES BELOW)
C     0  STANDARD RUN
C     1  BASIS SET OPTIMIZATION RUN (SECOND AND SUBSEQUENT ENTRIES) THE
C        BASIS SET IS NOT REDEFINED.
C
C     IOP(15) ... HANDLING OF SMALL TWO ELECTRON INTEGRALS
C     N  DISCARD IF MAGNITUDE LESS THAN 10**-(6+N).
C     NOTE ... ACCURACY OF CALCULATED INTEGRALS SHOULD BE BETWEEN
C     10**-8 AND 10**-9 AU, AND NORMALLY IOP(15)=4 IS USED.
C
C     IOP(16) ... PRINTING OF OVERLAP / CORE HAMILTONIAN INTEGRALS.
C     0  NO PRINTING.
C     1  PRINT OVERLAP INTEGRALS.
C     2  PRINT OVERLAP AND CORE HAMILTONIAN (T+V) INTEGRALS.
C     3  PRINT CORE HAMILTONIAN INTEGRALS.
C     7  PRINT S AND H (T+V) INTEGRALS WITH EXTENDED PRECISION, AS WELL
C        AS NORMALLY.
C
C     IOP(17) ... PRINTING OF DIPOLE MOMENT INTEGRALS.
C     0  NO.
C     1  YES.
C
C     IOP(18) ... PRINTING OF TWO ELECTRON INTEGRALS
C     0  NO PRINTING.
C     1  PRINT ... FOUR PER LINE WITH ASSOCIATED LABELS.
C
C     IOP(19) ... PRINTING OF NORMALIZED COEFFICIENTS.
C     0  NO.
C     1  YES.
C
C     IOP(20) ... SET UP BASIS SET FOR PROJECTED INITIAL GUESS.
C     0  NOT USING PROJECTED INITIAL GUESS.
C     1  SET UP STO-3G.
C     2  SET UP 3-21G.
C     3  SET UP A GENERAL BASIS SET.
C     THIS OPTION SAVES THE DATA REQUIRED IN LINK 0401 ON DISK: THE
C     BASIS SET TO FILE 31, THE SELF-OVERLAP TO FILE 31 AND THE
C     OVERLAP BETWEEN THE BASES TO FILE 4.
C     THIS BASIS SET WILL ALWAYS USE 5D/7F TYPE ORBITALS IF REQUIRED.
C     IF PRINTED, THIS BASIS WILL BE BEFORE THE ACTUAL BASIS TO BE USED
C     IN THE CALCULATION. ANY FLOATING ATOMS WILL BE TREATED AS DUMMY
C     ATOMS FOR THE INTERNAL BASES, AND ANY FLOATING ATOMS AFTER THE
C     LAST REAL ATOM WILL NOT BE PRINTED SINCE THE BASIS SET IS PRINTED
C     BY SHELLS, NOT ATOMS.
C
C     IOP(21) ... RESTART THE BASIS SET.
C     0  NO.
C     1  YES - THE ORIGINAL BASIS SET IS READ IN, THEN UPDATED
C     FROM THE FILES ON UNIT IMAT.
C
C     IOP(22) ... COMPUTE S AND H INTEGRALS ON CHECK RUNS.
C     0  NO.
C     1  YES.
C
C     IOP(23) ... PRINT CONTROL.
C     0  ONLY PRINT IF NON-STANDARD SCALE FACTORS ARE USED.
C     1  NO PRINTING OF BASIS SET TABLE OR 2-ELECTRON INTEGRAL
C     COUNTS. INTEGRAL PRINTING DETERMINED FROM IOP'S 16 - 18.
C     2  PRINT THE BASIS SET TABLE.
C
C     IOP(24) ... NORMALIZATION OF PRIMITIVE FUNCTIONS.
C     0  CONTRACTION COEFFICIENTS REFER TO UN-NORMALIZED PRIMITIVES.
C     1  CONTRACTION COEFFICIENTS REFER TO NORMALIZED PRIMITIVES.
C     NOTE THAT THE CONTRACTED FUNCTIONS ARE ALWAYS NORMALIZED.
C     THIS OPTION DOES NOT APPLY TO THE BASIS SET TO BE PROJECTED - IT
C     IS ASSUMED TO HAVE UN-NORMALIZED PRIMITIVES.
C
C     IOP(25) ... POLARIZATION FUNCTIONS ADDED TO INTERNAL BASIS SETS.
C     0  NONE.
C     1  D ORBITALS ON NA-AR.
C     2  D ORBITALS ON LI-NE (FOR N-M1G/N-M11G BASES).
C     3  COMBINATION OF 1 AND 2.
C     4  P ORBITALS ON H/HE (FOR N-M1G/N-M11G BASES).
C     5  COMBINATION OF 1 AND 4.
C     6  COMBINATION OF 2 AND 4.
C     7  COMBINATION OF 1, 2 AND 4.
C     THIS OPTION IS APPLIED ONLY TO AN INTERNAL BASIS USED FOR
C     THE ACTUAL CALCULATION, NOT TO AN INTERNAL BASIS USED FOR A
C     PROJECTED INITIAL GUESS.
C
C     IOP(26) ... PRINT PROJECTED GUESS BASIS SET.
C     0  NO.
C     1  YES - PROJECTION FROM A GENERAL BASIS ALWAYS CAUSES PRINTING.
C
C     IOP(27) ... POLARIZATION FUNCTIONS ADDED TO INTERNAL BASIS SETS.
C     0  NONE.
C     1  D ORBITALS ON K, CA, GA-KR (FOR N-M1G/N-M11G BASES).
C     2  D ORBITALS ON RB, SR, IN-XE (FOR N-M1G/N-M11G BASES).
C     3  COMBINATION OF 1 AND 2.
C     THIS OPTION IS APPLIED ONLY TO AN INTERNAL BASIS USED FOR
C     THE ACTUAL CALCULATION, NOT TO AN INTERNAL BASIS USED FOR A
C     PROJECTED INITIAL GUESS.
C
C     IOP(28) ... DIFFUSE FUNCTIONS ADDED TO INTERNAL BASIS SETS.
C     0  NONE.
C     1  SP ORBITALS ON NA-AR (FOR N-M1G/N-M11G BASES).
C     2  SP ORBITALS ON LI-NE (FOR N-M1G/N-M11G BASES).
C     3  COMBINATION OF 1 AND 2.
C     4  S ORBITALS ON H/HE (FOR N-M1G/N-M11G BASES).
C     5  COMBINATION OF 1 AND 4.
C     6  COMBINATION OF 2 AND 4.
C     7  COMBINATION OF 1, 2 AND 4.
C     THIS OPTION IS APPLIED ONLY TO AN INTERNAL BASIS USED FOR
C     THE ACTUAL CALCULATION, NOT TO AN INTERNAL BASIS USED FOR A
C     PROJECTED INITIAL GUESS.
C
C     IOP(29) ... DIFFUSE FUNCTIONS ADDED TO INTERNAL BASIS SETS.
C     0  NONE.
C     1  SP ORBITALS ON K, CA, GA-KR (FOR N-M1G/N-M11G BASES).
C     2  SP ORBITALS ON RB, SR, IN-XE (FOR N-M1G/N-M11G BASES).
C     3  COMBINATION OF 1 AND 2.
C     THIS OPTION IS APPLIED ONLY TO AN INTERNAL BASIS USED FOR
C     THE ACTUAL CALCULATION, NOT TO AN INTERNAL BASIS USED FOR A
C     PROJECTED INITIAL GUESS.
C
C     IOP(30) ... INTEGRAL ACCURACY CUTOFFS.
C     0  STANDARD CUTOFFS FOR 10**-8 INTEGRAL ACCURACY.
C     1  NO CUTOFFS USED.
C     2  USE OLD "SLOPPY" STO-3G CUTOFFS FOR 10**-6 ACCURACY.
C
C     IOP(31) ... USE "FAST" SPDF INTEGRAL ROUTINES.
C     0  YES, IF POSSIBLE.
C     1  NO.
C
C     IOP(32) ... PRINTING OF S / H INTEGRALS AFTER ED/BSSE SELECTION.
C     0  NO PRINTING.
C     1  PRINT OVERLAP INTEGRALS.
C     2  PRINT OVERLAP AND CORE HAMILTONIAN (T+V) INTEGRALS.
C     3  PRINT CORE HAMILTONIAN INTEGRALS.
C
C     IOP(33) ... PRINTING OF 2-E INTEGRALS AFTER ED/BSSE SELECTION.
C     0  NO PRINTING.
C     1  PRINT ... FOUR PER LINE WITH ASSOCIATED LABELS.
C
C     IOP(34) ... ENERGY DECOMPOSITION / BSSE CORRECTION.
C     0  NO.
C     1  ENERGY DECOMPOSITION ONLY.
C     2  BSSE CORRECTION ONLY.
C     3  ENERGY DECOMPOSITION AND BSSE CORRECTION.
C
C     IOP(35) TO IOP(60) ... NOT USED
C     ******************************************************************
C
C=BASIS SETS
C1SCALE-FACTORS
C     FOR THE STO-NG BASES THE SCALE FACTORS PERTAIN TO THE FOLLOWING
C     ORBITALS
C     1S 2SP 3SP 3D 4S 4P 4D 5S 5P,    OR
C     1S 2SP 3SP 3D 4SP 4D 5SP
C     FOR K AND CA, THE 3D SCALE FACTOR IS INCLUDED IN THE LIST, BUT
C     NOT USED, AS THOSE BASES DO NOT INCLUDE 3D ORBITALS AT PRESENT.
C     FOR RB AND SR, THE 4D SCALE FACTOR IS INCLUDED IN THE LIST, BUT
C     NOT USED, AS THOSE BASES DO NOT INCLUDE 4D ORBITALS AT PRESENT.
C
C     FOR THE N-21G/N-31G SERIES OF BASES:
C     FOR HYDROGEN/HELIUM:
C     1S' 1S" 2P(POL) 2S(DIFF)
C     FOR LITHIUM TO NEON:
C     1S 2SP' 2SP" 3D(POL) 3SP(DIFF)
C     FOR SODIUM TO ARGON:
C     1S 2SP 3SP' 3SP" 3D(POL) 4SP(DIFF)
C     FOR POTASSIUM TO KRYPTON:
C     1S 2SP 3SP 3D 4SP' 4SP" 4D(POL) 5SP(DIFF)
C     FOR RUBIDIUM TO XENON:
C     1S 2SP 3SP 3D 4SP 4D 5SP' 5SP" 5D(POL) 6SP(DIFF)
C
C     AND FOR THE N-311G SERIES OF BASES:
C     FOR H/HE:
C     1S' 1S" 1S"' 2P(POL) 2S(DIFF)
C     FOR LI-NE:
C     1S 2SP' 2SP" 2SP"' 3D(POL) 3SP(DIFF)
C     FOR NA-AR:
C     1S 2SP 3SP' 3SP" 3SP"' 3D(POL) 4SP(DIFF)
C
C=BASIS SETS
C1EXPONENTS
C     ******************************************************************
C     STANDARD EXPONENTS
C     ******************************************************************
C*
C     FOR STO-NG BASIS--------------------------------------------------
C*
C     ATOM  1S    2SP   3SP   3D    4SP   4S    4P    4D    5SP
C*
C     H     1.24
C     HE    1.69
C     LI    2.69  0.80
C     BE    3.68  1.15
C     B     4.68  1.50
C     C     5.67  1.72
C     N     6.67  1.95
C     O     7.66  2.25
C     F     8.65  2.55
C     NE    9.64  2.88
C     NA   10.61  3.48  1.75
C     MG   11.59  3.90  1.70
C     AL   12.56  4.36  1.70
C     SI   13.53  4.83  1.75
C     P    14.50  5.31  1.90
C     S    15.47  5.79  2.05
C     CL   16.43  6.26  2.10
C     AR   17.40  6.74  2.33
C     K    18.61  7.26  2.75        1.43
C     CA   19.58  7.74  3.01        1.36
C     SC   20.56  8.22  3.21  1.10  1.60  1.16  1.05
C     TI   21.54  8.70  3.44  1.90  1.70  1.20  1.10
C     V    22.53  9.18  3.67  2.55  1.70  1.25  1.15
C     CR   23.52  9.66  3.89  3.05  1.75  1.28  1.20
C     MN   24.50 10.13  4.11  3.45  1.65  1.32  1.25
C     FE   25.49 10.61  4.33  3.75  1.55  1.36  1.30
C     CO   26.47 11.09  4.55  4.10  1.55  1.39  1.35
C     NI   27.46 11.56  4.76  4.35  1.60  1.43  1.40
C     CU   28.44 12.04  4.98  4.60  1.60  1.46  1.45
C     ZN   29.43 12.52  5.19  4.90  1.90  1.49  1.50
C     GA   30.42 12.99  5.26  5.26  1.80
C     GE   31.40 13.47  5.58  5.58  2.00
C     AS   32.39 13.94  5.90  5.90  2.12
C     SE   33.37 14.40  6.22  6.22  2.22
C     BR   34.36 14.87  6.54  6.54  2.38
C     KR   35.34 15.34  6.86  6.86  2.54
C     RB   36.32 15.81  7.18  7.18  3.02                    1.90
C     SR   37.31 16.28  7.49  7.49  3.16                    1.80
C     Y    38.29 16.72  7.97  7.97  3.29              1.40  1.80
C     ZR   39.27 17.19  8.21  8.21  3.48              1.95  1.90
C     NB   40.26 17.66  8.51  8.51  3.67              2.40  1.90
C     MO   41.24 18.12  8.82  8.82  3.87              2.70  1.95
C     TC   42.22 18.59  9.14  9.14  4.05              3.00  1.85
C     RU   43.21 19.05  9.45  9.45  4.24              3.20  1.75
C     RH   44.19 19.51  9.77  9.77  4.41              3.45  1.75
C     PD   45.17 19.97 10.09 10.09  4.59              3.60  1.80
C     AG   46.15 20.43 10.41 10.41  4.76              3.75  1.80
C     CD   47.14 20.88 10.74 10.74  4.93              3.95  2.10
C     IN   48.12 21.33 11.08 11.08  4.65              4.65  2.05
C     SN   49.10 21.79 11.39 11.39  4.89              4.89  2.15
C     SB   50.08 22.25 11.71 11.71  5.12              5.12  2.20
C     TE   51.07 22.71 12.03 12.03  5.36              5.36  2.28
C     I    52.05 23.17 12.35 12.35  5.59              5.59  2.42
C     XE   53.03 23.63 12.66 12.66  5.82              5.82  2.57
C*
C     ATOMS H-AR:
C     INNER SHELLS ARE BEST ATOM VALUES ... J.CHEM.PHYS. 38, 2686 (1963)
C     OUTER SHELL HAS BEEN SELECTED ON THE BASIS OF NUMEROUS
C     OPTIMIZATION STUDIES ON VARIED SMALL MOLECULES:
C     H, LI-F: W.J. HEHRE, R.F. STEWART AND J.A. POPLE, JCP, 51,
C     2657 (1969). NA-CL: W.J. HEHRE, R. DITCHFIELD, R.F. STEWART AND
C     J.A. POPLE, JCP, 52, 2769 (1970).
C     ATOMS K, CA AND GA-KR USE A 3S=3P=3D/4S=4P BASIS:
C     W.J. PIETRO, B.A. LEVI, W.J. HEHRE AND R.F. STEWART, INORG. CHEM.,
C     19, 2225 (1980).
C     ATOM SC-ZN:
C     W.J. PIETRO AND W.J. HEHRE, J. COMPUT. CHEM., 4, 241 (1983).
C     ATOMS SC-ZN 4S AND 4P ARE ATOM OPTIMIZED VALUES:
C     E. CLEMENTI AND D.L. RAIMONDI, J.C.P., 38, 2686 (1963).
C     ATOMS RB, SR, IN-XE USE A 3S=3P=3D, 4S=4P=4D AND 5S=5P BASIS:
C     W.J. PIETRO, E.S. BLUROCK, R.F. HOUT, JR., W.J. HEHRE,
C     DEFREES AND R.F. STEWART, INORG. CHEM., 20, 3650 (1981).
C
C     ******************************************************************
C*
C     FOR 3-21G, 4-21G AND 6-21G BASIS SETS.
C*
C     ALL SCALE FACTORS ARE 1.0, EXCEPT H WHICH ARE 1.10 FOR 1S AND 1S*.
C
C     REFERENCES:
C     H-NE: J.S. BINKLEY, J.A. POPLE AND W.J. HEHRE,
C     JACS, 102, 939 (1980).
C     NA-AR: M.S. GORDON, J.S. BINKLEY, J.A. POPLE, W.J. PIETRO
C     AND W.J. HEHRE, JACS, 104, 2797 (1982).
C     K-XE (MAIN GROUP ONLY): K.D. DOBBS AND W.J. HEHRE, J. COMP. CHEM.,
C     7, 359-378 (1986).
C*
C     FOR THE PULAY 4-21G BASIS SET.
C*
C     ALL SCALE FACTORS ARE UNITY.
C
C     REFERENCE: P. PULAY, G. FOGARASI, F. PANG AND J.E. BOGGS, JACS,
C     101, 2550 (1979).
C     ******************************************************************
C*
C     FOR N-31G BASIS ... ALSO N-31G*, N-31G**.
C*
C     HYDROGEN, HELIUM--------------------------------------------------
C*
C            1S'   1S"
C*
C     H     1.20  1.15
C     HE    1.00  1.00
C*
C     FIRST ROW ATOMS---------------------------------------------------
C*
C     ATOM   1S   2SP'  2SP"
C*
C     LI    1.00  1.03  1.12
C     BE    1.00  1.03  1.12
C     B     1.00  1.03  1.12
C     C     1.00  1.00  1.04
C     N     1.00  0.99  0.98
C     O     1.00  0.99  0.98
C     F     1.00  1.00  1.00
C     NE    1.00  1.00  1.00
C*
C     SECOND ROW ATOMS (4-31G(**) ONLY)---------------------------------
C*
C     ATOM   1S   2SP   3SP'  3SP"
C*
C     SI    1.00  1.00  1.00  1.00
C     P     1.00  1.00  0.98  1.02
C     S     1.00  1.00  0.98  1.01
C     CL    1.00  1.00  1.00  1.01
C*
C     INNER SHELLS LEFT AT BEST ATOM VALUES.
C     AGAIN 4-31G(**) OUTER SCALE FACTORS CHOSEN ON THE BASIS OF
C     NUMEROUS OPTIMIZATION STUDIES ON SMALL MOLECULES:
C     H, C-F: R. DITCHFIELD, W.J. HEHRE AND J.A. POPLE, JCP, 54,
C     724 (1971). W.J. HEHRE, R. DITCHFIELD AND J.A. POPLE, JCP,
C     56, 2257 (1972). B: W.J. HEHRE AND J.A. POPLE, JCP, 56,
C     4233 (1972). P-CL: W.J. HEHRE AND W.A. LATHAN, JCP, 56,
C     5255 (1972). LI, B: J.D. DILL AND J.A. POPLE, JCP, 62, 2921
C     (1975). BE: J.S. BINKLEY AND J.A. POPLE, JCP, 66, 879 (1977).
C     FOR 6-31G(**) NA TO AR ALL SCALE FACTORS ARE UNITY: M.M. FRANCL,
C     W.J. PIETRO, W.J. HEHRE, J.S. BINKLEY, M.S. GORDON, D.J. DEFREES
C     AND J.A. POPLE, J. CHEM. PHYS., 77, 3654 (1982).
C     ******************************************************************
C*
C     FOR THE 6-311G(**) BASIS SET.
C*
C     ALL SCALE FACTORS ARE UNITY.
C
C     REFERENCE: R. KRISHNAN, J.S. BINKLEY, R. SEEGER AND J.A. POPLE,
C     J. CHEM. PHYS., 72, 650 (1980).
C*
C=BASIS SETS
C1POLARIZATION-FUNCTIONS
C     ******************************************************************
C     STANDARD POLARIZATION FUNCTION EXPONENTS.
C     ******************************************************************
C*
C     STO-NG* BASIS (USES 5D):
C
C     NA,MG  0.09      AL-AR  0.39
C
C     REFERENCE: J.B. COLLINS, P.V.R. SCHLEYER, J.S. BINKLEY AND
C     J.A. POPLE, J.C.P., 64, 5142 (1976).
C     ******************************************************************
C*
C     N-21G* BASIS (USES 6D):
C
C     H,HE   1.1 (2P)
C     LI-NE  0.8 (3D)
C     NA-AR  (SEE N-31G)
C
C     REFERENCE FOR H-NE: GAUSSIAN 80.
C     FOR NA-AR: W.J. PIETRO, M.M. FRANCL, W.J. HEHRE, D.J. DEFREES,
C     J.A. POPLE AND J.S. BINKLEY, JACS, 104, 5039 (1982).
C     K-XE (MAIN GROUP ONLY): K.D. DOBBS AND W.J. HEHRE, J. COMP. CHEM.,
C     7, 359-378 (1986).
C     NOTE THAT THE STANDARD N-21G* BASIS SET PUTS D-TYPE POLARIZATION
C     FUNCTIONS ONLY ON ATOMS PAST NE, AND THAT N-21G** IS NOT A
C     STANDARD BASIS SET.
C     ******************************************************************
C*
C     N-31G* AND N-31G** BASIS (USES 6D):
C
C     H,HE   1.1 (2P)
C     LI     0.2 (3D)
C     BE     0.4 (3D)
C     B      0.6 (3D)
C     C-NE   0.8 (3D)
C     NA     0.175 (3D)
C     MG     0.175 (3D)
C     AL     0.325 (3D)
C     SI     0.45  (3D)
C     P      0.55  (3D)
C     S      0.65  (3D)
C     CL     0.75  (3D)
C     AR     0.85  (3D)
C
C     REFERENCE: FOR H-NE: P.C. HARIHARAN AND J.A. POPLE, TCA, 28, 213
C                (1973).
C                FOR NA-AR: M.M. FRANCL, W.J. PIETRO, W.J. HEHRE,
C                J.S. BINKLEY, M.S. GORDON, D.J. DEFREES AND
C                J.A. POPLE, J. CHEM. PHYS., 77, 3654 (1982).
C     ******************************************************************
C*
C     6-311G* AND 6-311G** BASIS:
C
C     H,HE   0.750 (2P)
C     LI     0.200 (3D)
C     BE     0.255 (3D)
C     B      0.401 (3D)
C     C      0.626 (3D)
C     N      0.913 (3D)
C     O      1.292 (3D)
C     F      1.750 (3D)
C     NE     2.304 (3D)
C
C     REFERENCE: R. KRISHNAN, J.S. BINKLEY, R. SEEGER AND J.A. POPLE,
C     J. CHEM. PHYS., 72, 650 (1980).
C*
C     ******************************************************************
C=BASIS SETS
C1DIFFUSE-FUNCTIONS
C     ******************************************************************
C     STANDARD DIFFUSE FUNCTION EXPONENTS.
C     ******************************************************************
C*
C     N-21+G, N-21++G, 6-31+G, 6-31++G, 6-311+G AND 6-311++G BASES:
C
C     H      0.0360 (1S)
C     LI     0.0074 (2SP)
C     BE     0.0207 (2SP)
C     B      0.0315 (2SP)
C     C      0.0438 (2SP)
C     N      0.0639 (2SP)
C     O      0.0845 (2SP)
C     F      0.1076 (2SP)
C     NA     0.0076 (3SP)
C     MG     0.0146 (3SP)
C     AL     0.0318 (3SP)
C     SI     0.0331 (3SP)
C     P      0.0348 (3SP)
C     S      0.0405 (3SP)
C     CL     0.0483 (3SP)
C     AR     0.0554 (3SP)  (NOTE: THIS IS AN EXTRAPOLATED VALUE)
C
C     REFERENCES:
C     FOR H, LI-F: T. CLARK, J. CHANDRASEKHAR, G.W. SPITZNAGEL AND
C     P.V.R. SCHLEYER, J. COMP. CHEM., 4, 294-301 (1983).
C     FOR NA-AR: G.W. SPITZNAGEL, T. CLARK, P.V.R. SCHLEYER AND
C     W.J. HEHRE, J. COMP. CHEM., 8, 1109-1116 (1987).
C     FOR 6-311+(+)G BASIS: M.J. FRISCH, J.A. POPLE AND
C     J.S. BINKLEY, J. CHEM. PHYS., 80, 3265-3269 (1984).
C     ******************************************************************
C*
C     4-31+G AND 4-31++G BASIS:
C
C     H      0.0360 (1S)
C     LI     0.0120 (2SP)
C     BE     0.0260 (2SP)
C     B      0.0340 (2SP)
C     C      0.0400 (2SP)
C     N      0.0530 (2SP)
C     O      0.0680 (2SP)
C     F      0.0900 (2SP)
C
C     REFERENCE:
C     FOR H, LI-F: J. CHANDRASEKHAR, J.G. ANDRADE AND
C     P.V.R. SCHLEYER, J.A.C.S., 103, 5609-5612 (1981).
C     ******************************************************************
C==
C*
C/
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C#
C     PARAMETER (NA=#NA, NB=#NB)
C     PARAMETER (NS=#NS, NP=#NP)
C##
      PARAMETER (NA= 36, NB=200)
      PARAMETER (NS=120, NP=300)
C###
      PARAMETER (ZERO=0.0D0, ONE=1.0D0, TWO=2.0D0)
C
      INTEGER SHELLA,SHELLN,SHELLT,AOS,SHELLC
C
      COMMON /A/ IOP(99)
      COMMON /A/ NATOMS,ICHARG,MULTIP,IAN(NA),NAE,NBE,NE,NBASIS,C(NA,3)
      COMMON /A/ CDUM(4),ICDUM(401)
C
C     USE OF COMMON /B/ AS FOLLOWS
C     BUT FIRST WE MUST DEFINE THE CONCEPT OF A SHELL AS A GROUP
C     ATOMIC ORBITALS SHARING THE SAME PRIMITIVE GAUSSIAN EXPONENTS ...
C     THAT IS, NOT EXPANSION COEFFICIENTS.
C     FOR 1S 2S AND 2P FUNCTIONS WE MAY CONSIDER THE FOLLOWING
C     SHELL TYPES:
C     1S ONLY  1 ATOMIC ORBITAL
C     2S ONLY  1 ATOMIC ORBITAL
C     2PX 2PY 2PZ ONLY  3 ATOMIC ORBITALS
C     2S 2PX 2PY 2PZ  4 ATOMIC ORBITALS
C     AND SIMILAR DEFINITIONS FOR SECOND ROW ELEMENTS AND FOR
C     EXTENSIONS OVER MINIMAL BASIS SETS.
C     THE INTERNAL BASIS SETS EMPLOY ONLY THE FIRST AND THE LAST,
C     THE LATTER EMPLOYING THE TIME SAVING S=P FUNCTION CONSTRAINT.
C     SHELLS CONTAINING D ORBITALS MAY NOT CONTAIN S OR P TYPE ORBITALS
C     IXYZ   ATOM NUMBER THIS SHELL IS LOCATED ON.
C     SHELLA ... AN INTEGER ... LOCATION IN LIST OF GAUSSIAN FUNCTIONS
C     OF FIRST FUNCTION IN A GIVEN SHELL.
C     SHELLN   NUMBER OF GAUSSIAN FUNCTIONS IN A SHELL.
C     SHELLT   LARGEST PRINCIPAL QUANTUM NUMBER REPRESENTED
C     BY A GIVEN SHELL:
C     SHELLT=0  S.
C     SHELLT=1  P.
C     SHELLT=2  D.
C     SHELLT=3  F.
C     SHELLC ... SHELL CONSTRAINT:
C     SHELLC=0  S, SP, D OR F SHELL.
C     SHELLC=1  P SHELL.
C     AOS   NUMBER OF FIRST ATOMIC ORBITAL PRODUCED BY A SHELL.
C     NSHELL  NUMBER OF SHELLS.
C     MAXTYP  LARGEST PRINCIPAL QUANTUM NUMBER FOUND IN BASIS
C     (SEE SHELLT FOR CONVENTION).
C     EXX   GAUSSIAN EXPONENTS.
C     C1,C2   S AND P COEFFICIENTS (D AND F COEFFS IN C1).
C
      COMMON/B/IXYZ(NS),SHELLA(NS),SHELLN(NS),SHELLT(NS),
     1 SHELLC(NS),AOS(NS),NSHELL,MAXTYP,EXX(NP),C1(NP),C2(NP)
      COMMON/SCAL/SCALE(NS),C1S(NP),C2S(NP)
      COMMON/BSINFO/NVO(NA),IAOFF(NA)
      COMMON /BSINFC/ NSH(NB), LAO(NB), LABEL(NS), LSHELL(NS), BLABEL
C
      COMMON/IO/IN,IOUT,IPUNCH,IMAT,IODUM(13),NFILE(100,2)
C
      CHARACTER IATOM*12, IAOLAB*1, LA*4, ISTAR*1
      CHARACTER NSH*2, LAO*4, LABEL*4, LSHELL*2, BLABEL*200, BTYPE*8
C
      DIMENSION IATOM(56),OVRLAP(4),LA(44)
      DIMENSION ISTAR(2),IAOLAB(4)
C
      LOGICAL SEP
C
      EQUIVALENCE (IXYZ(1),XYZ)
      EQUIVALENCE (OVRLAP(1),OVRS),(OVRLAP(2),OVRP),(OVRLAP(3),OVRD),
     1 (OVRLAP(4),OVRF)
C*
      DATA PT75/0.75D0/, ONEP25/1.25D0/,
     1 ONEP75/1.75D0/, TWOP25/2.25D0/, F15/15.0D0/
      DATA THREE/3.0D0/, PI/3.14159265358979D0/
      DATA ONEPT5/1.5D0/, TWOPT5/2.5D0/, THRPT5/3.5D0/, FORPT5/4.5D0/,
     1 FOUR/4.0D0/, TENM10/1.0D-10/
      DATA ISTAR/' ', '*'/
      DATA IAOLAB/'S', 'P', 'D', 'F'/
C*
C     FLOATING FUNCTIONS HAVE ATOMIC NUMBERS LESS THAN ZERO, BUT
C     WILL BE LABELED AS IF THEY WERE ATOMIC NUMBER 55.  IF IATOM IS
C     EXPANDED, INSERT BEFORE FLOATING FUNCTION LABEL AND CHANGE VALUE
C     OF IFLOAT.
C     SIMILARLY, TREAT DUMMY ATOMS AS ATOMIC NUMBER 56.
      DATA IFLOAT/55/,IDUMMY/56/
      DATA IATOM     /'    HYDROGEN','      HELIUM',
     1 '     LITHIUM','   BERYLLIUM','       BORON',
     2 '      CARBON','    NITROGEN','      OXYGEN',
     3 '    FLUORINE','        NEON','      SODIUM',
     4 '   MAGNESIUM','    ALUMINUM','     SILICON',
     5 '  PHOSPHORUS','      SULFUR','    CHLORINE',
     6 '       ARGON','   POTASSIUM','     CALCIUM',
     7 '    SCANDIUM','    TITANIUM','    VANADIUM',
     8 '    CHROMIUM','   MANGANESE','        IRON',
     9 '      COBALT','      NICKEL','      COPPER',
     1 '        ZINC','     GALLIUM','   GERMANIUM',
     2 '     ARSENIC','    SELENIUM','     BROMINE',
     3 '     KRYPTON','    RUBIDIUM','   STRONTIUM',
     4 '     YTTRIUM','   ZIRCONIUM','     NIOBIUM',
     5 '  MOLYBDENUM','  TECHNETIUM','   RUTHENIUM',
     6 '     RHODIUM','   PALLADIUM','      SILVER',
     7 '     CADMIUM','      INDIUM','         TIN',
     8 '    ANTIMONY','   TELLURIUM','      IODINE',
     9 '       XENON','   FLOATING*','      DUMMY*'/
C*
C     LA IS THE AO LABELS, TO BE STORED IN LAO (IN COMMON/BSINFC/). THE
C     AO NUMBERING WILL BE COPIED FROM LSHELL INTO NSH (AND EXPANDED
C     FROM SHELL NUMBERS TO AO NUMBERS), AND THE NUMBER OF ORBITALS PER
C     ATOM PUT IN NVO. THIS INFORMATION REQUIRED BY GBSOUT FOR PRINTING.
C?GLD
C     DATA LA/'S   ','PX  ','PY  ','PZ  ','DXX ','DYY ','DZZ ','DXY ',
C    1 'DXZ ','DYZ ','FXXX','FYYY','FZZZ','FXYY','FXXY','FXXZ','FXZZ',
C    2 'FYZZ','FYYZ','FXYZ','S''  ','PX'' ','PY'' ','PZ'' ',
C    3 'S""  ','PX"" ','PY"" ','PZ"" ',
C    4 'D 0 ','D 1+','D 1-','D 2+','D 2-',
C    5 'F 0 ','F 1+','F 1-','F 2+','F 2-','F 3+','F 3-',
C    6 'S""'' ','PX""''','PY""''','PZ""'''/
C??
C?GBR/IBM/VAX/CDC/UNX
      DATA LA/'S   ','PX  ','PY  ','PZ  ','DXX ','DYY ','DZZ ','DXY ',
     1 'DXZ ','DYZ ','FXXX','FYYY','FZZZ','FXYY','FXXY','FXXZ','FXZZ',
     2 'FYZZ','FYYZ','FXYZ','S''  ','PX'' ','PY'' ','PZ'' ',
     3 'S"  ','PX" ','PY" ','PZ" ',
     4 'D 0 ','D 1+','D 1-','D 2+','D 2-',
     5 'F 0 ','F 1+','F 1-','F 2+','F 2-','F 3+','F 3-',
     6 'S"'' ','PX"''','PY"''','PZ"'''/
C??
 1000 FORMAT('1BASIS SET FOR THIS CALCULATION (EXPONENTS ARE SCALED)'/)
 1010 FORMAT('0SCALE FACTOR OR EXPONENT IS ZERO OR NEGATIVE')
 1020 FORMAT('1NORMALIZED BASIS SET'/)
 1030 FORMAT('1BASIS SET FOR PROJECTED INITIAL GUESS'/)
 1040 FORMAT ('0ERROR: ',A1,' ORBITAL CONTRACTION COEFFICIENT IS ZERO ',
     1 'FOR SHELL',I4,' (ATOM',I3,').')
 1050 FORMAT(1X,130('*'))
 1060 FORMAT(15X,'ATOMIC ORBITAL',37X,'GAUSSIAN FUNCTIONS')
 1070 FORMAT(6X,'ATOM',7X,'NO.',4X,'TYPE',3X,
     1 'SCALE FACTOR',4X,'EXPONENT',8X,'S COEF',9X,'P COEF',9X,
     2 'D COEF',9X,'F COEF')
 1080 FORMAT (1X,A12)
 1090 FORMAT(16X,I5,3X,A2,A4,F11.5)
 1100 FORMAT(14X,I3,'-',I3,3X,A2,A4,F11.5)
 1110 FORMAT(44X,1PD14.7,4D15.7)
 1120 FORMAT('0*** CHARGE/MULTIPLICITY ERROR')
 1130 FORMAT(/'0*** THE S=P EXPONENT CONSTRAINT HAS BEEN REMOVED')
 1140 FORMAT('0TOO MANY SHELLS OR BASIS FUNCTIONS:'/
     1 ' NUMBER OF SHELLS IS',I4,' (LIMIT IS',I4,')'/
     2 ' NUMBER OF BASIS FUNCTIONS IS',I4,' (LIMIT IS',I4,')'/
     3 ' NOTE THAT THESE NUMBERS CAN BE CHANGED BY CONTACTING ',
     4 'YOUR MONSTERGAUSS SUPPLIER.')
 1150 FORMAT(' CONTAINS',I4,' SHELLS AND',I4,' BASIS FUNCTIONS')
 1160 FORMAT('0TOO MANY PRMITIVE GAUSSIAN FUNCTIONS:'/
     1 ' NUMBER OF PRMITIVES IS',I4,' (LIMIT IS',I4,')'/
     2 ' NOTE THAT THIS NUMBER CAN BE CHANGED BY CONTACTING ',
     3 'YOUR MONSTERGAUSS SUPPLIER.')
 1170 FORMAT (1X,130('-'))
 1200 FORMAT('0BASIS SET ERROR: NBASIS =',I4,', N2 =',I4)
 1230 FORMAT(/'0PROJECTING FROM STO-3G BASIS (5D/7F)')
 1240 FORMAT(/'0PROJECTING FROM 3-21G BASIS (5D/7F)')
 1250 FORMAT(/'0PROJECTING FROM A GENERAL BASIS (5D/7F)')
 1260 FORMAT (A8,1X,'STO-',I1,'G',A1,'     (',I2,'D/',I2,'F)')
 1270 FORMAT (A8,1X,I1,'-',I1,'1G',2A1,'     (',I2,'D/',I2,'F)')
 1290 FORMAT (A8,1X,I1,'-311G',2A1,'    (',I2,'D/',I2,'F)')
 1300 FORMAT('0BASIS SET RESTORED FROM UNIT',I4/)
 1310 FORMAT('0ATOM',I4,' HAS MORE THAN 127 ATOMIC ORBITALS.')
 1320 FORMAT (A8,1X,I1,'-',I1,'1+G',2A1,'    (',I2,'D/',I2,'F)')
 1340 FORMAT (A8,1X,I1,'-311+G',2A1,'   (',I2,'D/',I2,'F)')
 1350 FORMAT (A8,1X,I1,'-',I1,'1++G',2A1,'   (',I2,'D/',I2,'F)')
 1370 FORMAT (A8,1X,I1,'-311++G',2A1,' (',I2,'D/',I2,'F)')
 1380 FORMAT (A8,' GENERAL     (',I2,'D/',I2,'F)')
 1390 FORMAT (/'0BASIS SET TYPE: ',A30/' POLARIZATION  : ',A85/
     1 ' DIFFUSE FUNCS : ',A85)
C*
      IF (IOP(4) .GE. 5) RETURN
      PI34=PI**PT75
      ROOT2=DSQRT(TWO)
      ROOT3=DSQRT(THREE)
      FCON=TWO*ROOT2/(PI34*DSQRT(F15))
      IF(IOP(1).NE.-3)GO TO 10
C     PRINT FINAL BASIS SET, THEN TERMINATE.
      IOP(14)=1
      IOP(19)=0
      IOP(20)=0
      IOP(21)=0
      IOP(23)=2
C     DO WE SET UP A BASIS SET FOR A PROJECTED INITIAL GUESS?
   10 IOP20=IOP(20)
      IF(IOP20.EQ.0)GO TO 70
      IPRINT=1-IOP(26)
      IF(IOP20-2)11,12,13
   11 WRITE(IOUT,1230)
      GO TO 15
   12 WRITE(IOUT,1240)
      GO TO 15
   13 IPRINT=0
      WRITE(IOUT,1250)
   15 IF(IPRINT.EQ.0)WRITE(IOUT,1030)
      IOP6S=IOP(6)
      IOP8S = IOP(8)
      IOP13S=IOP(13)
      IOP14S=IOP(14)
      IOP25S=IOP(25)
      IOP27S=IOP(27)
      IOP28S=IOP(28)
      IOP29S=IOP(29)
C     SET IOP'S FOR THE BASIS SET TO BE PROJECTED.
      IOP(6)=IOP20-1
      IF(IOP20.EQ.3)IOP(6)=7
      IOP(8) = 1
      IOP(13)=3
      IOP(14)=0
      IOP(25)=0
      IOP(27)=0
      IOP(28)=0
      IOP(29)=0
      GO TO 80
C     RESET TO PROPER BASIS, AFTER SAVING THE CURRENT BASIS SET.
   20 CALL TWRITE(31,XYZ,NFILE(6,1),1,NFILE(6,1),1,0)
      IOP(93)=NBASIS
      IOP(6)=IOP6S
      IOP(8) = IOP8S
      IOP(13)=IOP13S
      IOP(14)=IOP14S
      IOP(25)=IOP25S
      IOP(27)=IOP27S
      IOP(28)=IOP28S
      IOP(29)=IOP29S
      IOP20=0
C
C     GENERATE BASIS SET LABEL.
C
   70 ND=6-IOP(8)
      NF=10-3*IOP(8)
C     SET D/P POLARIZATION FLAGS.
      I = IOP(25)
      IFPOL1 = I / 4
      I = I - 4*IFPOL1
      IFPOL2 = I / 2
      IFPOL3 = I - 2*IFPOL2
      I = IOP(27) - 4*(IOP(27)/4)
      IFPOL5 = I / 2
      IFPOL4 = I - 2*IFPOL5
      IFPOL = IFPOL1 + IFPOL2 + IFPOL3 + IFPOL4 + IFPOL5
      IF (IFPOL .GT. 0) IFPOL = 1
      IFPOL = IFPOL + 1
C     SET SP/S DIFFUSE FUNCTION FLAGS.
      I = IOP(28)
      IFDIF1 = I / 4
      I = I - 4*IFDIF1
      IFDIF2 = I / 2
      IFDIF3 = I - 2*IFDIF2
      I = IOP(29) - 4*(IOP(29)/4)
      IFDIF5 = I / 2
      IFDIF4 = I - 2*IFDIF5
      IFDIF = IFDIF1 + IFDIF2 + IFDIF3 + IFDIF4 + IFDIF5
      IF (IFDIF .GT. 0) IFDIF = 1
      BTYPE = 'STANDARD'
      IF (IOP(6) .EQ. 3) BTYPE = 'PULAY'
      IF (IOP(6) .EQ. 7) BTYPE = 'EXTERNAL'
      IF (IOP(14) .NE. 0) THEN
         BLABEL(1:8) = 'MODIFIED'
         GO TO 78
      END IF
C
C     STO-NG.
      IF(IOP(6).NE.0)GO TO 72
      NG=IOP(13)
      IF(NG.EQ.0)NG=3
      WRITE (BLABEL,1260) BTYPE,NG,ISTAR(IFPOL),ND,NF
      GO TO 77
C     N-21G/N-31G/PULAY 4-21G.
   72 IF(IOP(6).GT.3)GO TO 74
      J=2
      IF(IOP(6).EQ.2)J=3
      IF (IFDIF1 .NE. 0) THEN
         WRITE (BLABEL,1350) BTYPE,IOP(13),J,ISTAR(IFPOL),
     1    ISTAR(IFPOL1+1),ND,NF
      ELSE IF (IFDIF .NE. 0) THEN
         WRITE (BLABEL,1320) BTYPE,IOP(13),J,ISTAR(IFPOL),
     1    ISTAR(IFPOL1+1),ND,NF
      ELSE
         WRITE (BLABEL,1270) BTYPE,IOP(13),J,ISTAR(IFPOL),
     1    ISTAR(IFPOL1+1),ND,NF
      END IF
      GO TO 77
C     6-311G.
   74 IF (IOP(6).GT.4) GO TO 75
      IF (IFDIF1 .NE. 0) THEN
         WRITE (BLABEL,1370) BTYPE,IOP(13),ISTAR(IFPOL),
     1    ISTAR(IFPOL1+1),ND,NF
      ELSE IF (IFDIF .NE. 0) THEN
         WRITE (BLABEL,1340) BTYPE,IOP(13),ISTAR(IFPOL),
     1    ISTAR(IFPOL1+1),ND,NF
      ELSE
         WRITE (BLABEL,1290) BTYPE,IOP(13),ISTAR(IFPOL),
     1    ISTAR(IFPOL1+1),ND,NF
      END IF
      GO TO 77
C     GENERAL BASIS.
   75 WRITE (BLABEL,1380) BTYPE,ND,NF
      BLABEL(31:) = 'UNKNOWN'
      BLABEL(116:) = 'UNKNOWN'
      GO TO 78
C
C     GENERATE SPECIFIC POLARIZATION/DIFFUSE FUNCTION LABELS.
C
   77 I = 31
      BLABEL(I:) = 'NONE'
      IF (IFPOL2 .NE. 0) THEN
         BLABEL (I:) = 'D ON LI-NE'
         I = I + 13
      END IF
      IF (IFPOL3 .NE. 0) THEN
         BLABEL (I:) = 'D ON NA-AR'
         I = I + 13
      END IF
      IF (IFPOL4 .NE. 0) THEN
         BLABEL (I:) = 'D ON K-KR'
         I = I + 12
      END IF
      IF (IFPOL5 .NE. 0) THEN
         BLABEL (I:) = 'D ON RB-XE'
         I = I + 13
      END IF
      IF (IFPOL1 .NE. 0) THEN
         BLABEL (I:) = 'P ON H-HE'
      END IF
      I = 116
      BLABEL(I:) = 'NONE'
      IF (IFDIF2 .NE. 0) THEN
         BLABEL (I:) = 'SP ON LI-NE'
         I = I + 14
      END IF
      IF (IFDIF3 .NE. 0) THEN
         BLABEL (I:) = 'SP ON NA-AR'
         I = I + 14
      END IF
      IF (IFDIF4 .NE. 0) THEN
         BLABEL (I:) = 'SP ON K-KR'
         I = I + 13
      END IF
      IF (IFDIF5 .NE. 0) THEN
         BLABEL (I:) = 'SP ON RB-XE'
         I = I + 14
      END IF
      IF (IFDIF1 .NE. 0) THEN
         BLABEL (I:) = 'S ON H-HE'
      END IF
C
C     SET BASIS SET TABLE PRINT OPTION.
C
   78 IF (IOP(23) .EQ. 0) THEN
         WRITE (IOUT,1390) BLABEL(1:30), BLABEL(31:115), BLABEL(116:200)
         IF (IOP(14) .EQ. 0) THEN
            IPRINT = 1
         ELSE
            IPRINT = 0
         END IF
      ELSE IF (IOP(23) .EQ. 1) THEN
         IPRINT = 1
      ELSE
         WRITE (IOUT,1390) BLABEL(1:30), BLABEL(31:115), BLABEL(116:200)
         IPRINT = 0
      END IF
C
   80 IOP6=IOP(6)
      IF(IOP20.EQ.0.AND.IPRINT.EQ.0)WRITE(IOUT,1000)
      IPASS=0
      IF(IOP(14).EQ.1)GO TO 300
C     CHECK FOR INPUT OF GENERAL BASIS SET ... BYPASS EXPONENT SECTION
C     IF THIS IS SO
      IF(IOP6.NE.7)GO TO 90
      CALL GBASIS(LA,NS)
      GO TO 340
   90 IF(IOP6.NE.0)GO TO 100
      CALL STO (LA, IOP20)
      GO TO 340
  100 CALL NM1G (LA, IOP20)
      GO TO 340
C     RESUME BASIS SET OPTIMIZATION ... PULL CURRENT BASIS SET
C     FROM DISK
  300 CALL TREAD(2,SCALE,NFILE(2,1),1,NFILE(2,1),1,0)
      IF(IOP(21).NE.1)GO TO 301
      CALL TREAD(6,XYZ,NFILE(6,1),1,NFILE(6,1),1,0)
      WRITE(IOUT,1300)IMAT
C     COPY THE RAW COEFFICIENTS.
  301 K=SHELLA(NSHELL)+SHELLN(NSHELL)-1
      DO 305 I=1,K
      C1(I)=C1S(I)
  305 C2(I)=C2S(I)
      IF(IOP(1).EQ.-3)IOP(1)=-2
      GO TO 380
C     BASIS SET ERROR?
  340 IF(IOP(1).LT.0)RETURN
      IF(NSHELL.GT.NS.OR.NBASIS.GT.NB)GO TO 940
      K=SHELLA(NSHELL)+SHELLN(NSHELL)-1
      IF(K.GT.NP)GO TO 945
C     SAVE THE RAW COEFFICIENTS, AND THE SCALE FACTORS.
C     CHECK FOR BASIS SET RESTART.
      IF(IOP20.EQ.0.AND.IOP(21).EQ.1)GO TO 300
      IF(IOP20.NE.0.OR.IOP(24).NE.1)GO TO 2040
C     UN-NORMALIZE THE NORMALIZED PRIMITIVES.
      DO 2030 I=1,NSHELL
      ITYPE=SHELLT(I)+1
      N1=SHELLA(I)
      N2=N1+SHELLN(I)-1
      DO 2030 J=N1,N2
      E=EXX(J)+EXX(J)
      GO TO (2000,2000,2010,2020),ITYPE
 2000 C1(J)=C1(J)*PI34/E**PT75
      C2(J)=C2(J)*PI34/(ROOT2*E**ONEP25)
      GO TO 2030
 2010 C1(J)=C1(J)*ROOT3*PI34/(TWO*E**ONEP75)
      GO TO 2030
 2020 C1(J)=C1(J)/(FCON*E**TWOP25)
 2030 CONTINUE
C
 2040 DO 350 I=1,K
      C1S(I)=C1(I)
  350 C2S(I)=C2(I)
      IF(IOP20.EQ.0)CALL TWRITE(2,SCALE,NFILE(2,1),1,NFILE(2,1),1,0)
C     PRINT TABLE
  380 IPASS=IPASS+1
      IF(IPRINT.NE.0)GO TO 390
      WRITE (IOUT,1050)
      WRITE (IOUT,1060)
      WRITE (IOUT,1050)
      WRITE (IOUT,1070)
      WRITE (IOUT,1050)
  390 IOLD=0
      N2=0
      IOP8=IOP(8)
      SEP = .FALSE.
C     SET UP CORRELATION BETWEEN SHELLS AND AO FOR GBSOUT.
      DO 700 I=1,NATOMS
  700 NVO(I)=0
C
      DO 420 I=1,NSHELL
      ICENT=IXYZ(I)
      IA=IAN(ICENT)
      IF(IA.LT.0)IA=IFLOAT
      IF(ICENT.EQ.IOLD)GO TO 375
      IF(ICENT.EQ.IOLD+1)GO TO 374
C     ATOMS IOLD+1 TO ICENT-1 INCLUSIVE ARE DUMMY/FLOATING ATOMS.
      IF(IPRINT.NE.0)GO TO 374
      IOLD=IOLD+1
      MM=ICENT-1
      DO 372 K=IOLD,MM
      IF (SEP) WRITE (IOUT,1170)
      SEP = .TRUE.
      IF (IAN(K) .EQ. 0) THEN
         WRITE (IOUT,1080) IATOM(IDUMMY)
      ELSE
         WRITE (IOUT,1080) IATOM(IFLOAT)
      END IF
  372 CONTINUE
C
  374 IOLD=ICENT
      IF  (IPRINT.EQ.0 .AND. SEP) WRITE (IOUT,1170)
      SEP = .TRUE.
      IF(IPRINT.EQ.0)WRITE(IOUT,1080) IATOM(IA)
  375 N1=N2+1
      ITYPE=SHELLT(I)+1
      GO TO (710,720,730,740),ITYPE
C     S SHELL.
  710 N2=N1
      NVO(ICENT)=NVO(ICENT)+1
      IF(IPRINT.EQ.0)WRITE(IOUT,1090)N1,LSHELL(I),LABEL(I),SCALE(I)
      GO TO 400
C     SP OR P SHELL.
  720 K=4-SHELLC(I)
      GO TO 790
C     D SHELL.
  730 K=6-IOP8
      GO TO 790
C     F SHELL.
  740 K=10-3*IOP8
  790 N2=N2+K
      NVO(ICENT)=NVO(ICENT)+K
      IF(IPRINT.EQ.0)WRITE(IOUT,1100)N1,N2,LSHELL(I),LABEL(I),SCALE(I)
  400 IF(SCALE(I).LE.ZERO)GO TO 950
      CS=ZERO
      CP=ZERO
      CD=ZERO
      CF=ZERO
      NGAUSS=SHELLN(I)
      DO 420 J=1,NGAUSS
      K=SHELLA(I)+J-1
      IERR = 0
      GO TO (800,800,810,820),ITYPE
C     S, P OR SP.
  800 CS=C1(K)
      IF (CS.EQ.ZERO .AND. (ITYPE.EQ.1 .OR.
     1 (ITYPE.EQ.2.AND.SHELLC(I).EQ.0))) IERR = 1
      CP=C2(K)
      IF (CP.EQ.ZERO .AND. ITYPE.EQ.2) IERR = 2
      GO TO 410
C     D.
  810 CD=C1(K)
      IF (CD .EQ. ZERO) IERR = 3
      GO TO 410
C     F.
  820 CF=C1(K)
      IF (CF .EQ. ZERO) IERR = 4
  410 IF (IPRINT .EQ. 0)  WRITE (IOUT,1110) EXX(K),CS,CP,CD,CF
      IF(EXX(K).LE.ZERO)GO TO 950
      IF (IERR .NE. 0) GO TO 980
  420 CONTINUE
C
      IF(IPRINT.EQ.0)WRITE (IOUT,1050)
C     END OF TABLE PRINTING
C
C     DETERMINE THE OFFSETS TO BE APPLIED FOR EACH ATOM WHEN
C     THE 2-ELECTRON INTEGRAL LABELS ARE STORED.
C
      K=0
      DO 2100 I=1,NATOMS
      IAOFF(I)=K
      IF(NVO(I).GT.127) GO TO 970
 2100 K=K+NVO(I)
      IF(IPASS.EQ.2)RETURN
C     CHECK NBASIS AND N2.
      IF(NBASIS.NE.N2)GO TO 960
C     CALCULATE NUMBER OF ELECTRONS AND OCCUPATION NUMBERS NAE,NBE
      NE=0
      DO 510 I=1,NATOMS
  510 IF(IAN(I).GT.0)NE=NE+IAN(I)
      NE=NE-ICHARG
      NAE=(NE+MULTIP-1)/2
      NBE=(NE-MULTIP+1)/2
      IF (MULTIP.GT.0 .AND. NAE+NBE.EQ.NE .AND. NAE.GE.0 .AND. NBE.GE.0)
     1 GO TO 520
C     CHARGE/MULTIPLICITY ERROR
      WRITE(IOUT,1120)
      IOP(1)=-2
      RETURN
C     NORMALIZE SCALED GAUSSIAN FUNCTIONS
C     ENSURE CONTRACTED AO'S ARE NORMALIZED.
C     CODE ADAPTED FROM GAUSSIAN 76.
C     DETERMINE MAXTYP ... LARGEST PRINCIPLE QUANTUM NUMBER IN BASIS.
  520 MAXTYP=0
      DO 690 I=1,NSHELL
      N1=SHELLA(I)
      N2=N1+SHELLN(I)-1
      ITYPE=SHELLT(I)-2
      IF(SHELLT(I).GT.MAXTYP)MAXTYP=SHELLT(I)
      OVRS=ZERO
      OVRP=ZERO
      OVRD=ZERO
      OVRF=ZERO
      DO 630 J=N1,N2
      DO 630 K=N1,N2
      AXB=FOUR*EXX(J)*EXX(K)
      APB=EXX(J)+EXX(K)
      CJK=C1(J)*C1(K)
      IF(ITYPE)600,610,620
C     SP SHELL.
  600 OVRS=OVRS+CJK*(AXB**PT75)/(APB**ONEPT5)
      OVRP=OVRP+C2(J)*C2(K)*(AXB**ONEP25)/(APB**TWOPT5)
      GO TO 630
C     D SHELL.
  610 OVRD=OVRD+CJK*(AXB**ONEP75)/(APB**THRPT5)
      GO TO 630
C     F SHELL.
  620 OVRF=OVRF+CJK*(AXB**TWOP25)/(APB**FORPT5)
  630 CONTINUE
      DO 650 K=1,4
      IF(OVRLAP(K).GT.TENM10)GO TO 640
      OVRLAP(K)=ZERO
      GO TO 650
  640 OVRLAP(K)=ONE/DSQRT(OVRLAP(K))
  650 CONTINUE
      DO 690 J=N1,N2
      IF(ITYPE)660,670,680
  660 C1(J)=C1(J)*OVRS
      C2(J)=C2(J)*OVRP
      GO TO 690
  670 C1(J)=C1(J)*OVRD
      GO TO 690
  680 C1(J)=C1(J)*OVRF
  690 CONTINUE
C*
      K=0
      DO 930 I=1,NSHELL
      ITYPE=SHELLT(I)+1
      N1=SHELLA(I)
      N2=N1+SHELLN(I)-1
      DO 930 J=N1,N2
      E=TWO*EXX(J)
      GO TO (900,900,910,920),ITYPE
  900 C1(J)=C1(J)*E**PT75/PI34
      C2(J)=C2(J)*ROOT2*E**ONEP25/PI34
      IF(SHELLC(I).NE.0)K=1
      GO TO 930
  910 C1(J)=C1(J)*TWO*E**ONEP75/(ROOT3*PI34)
      GO TO 930
  920 C1(J)=C1(J)*FCON*(E**TWOP25)
  930 CONTINUE
      IF(IOP20.NE.0)GO TO 20
      IF(IOP(21).NE.1)CALL TWRITE(6,XYZ,NFILE(6,1),1,NFILE(6,1),1,0)
      IF(IOP(23).EQ.0.AND.IPRINT.EQ.1)WRITE(IOUT,1150)NSHELL,NBASIS
      IF(K.EQ.1.AND.IPRINT.EQ.0)WRITE(IOUT,1130)
C     PRINT NORMALIZED COEFFICIENTS?
      IF(IOP(19).NE.1)RETURN
      WRITE(IOUT,1020)
      GO TO 380
C
C     ERROR SECTION.
C
C     TOO MANY SHELLS OR BASIS FUNCTIONS.
  940 WRITE (IOUT,1140) NSHELL, NS, NBASIS, NB
      IOP(1)=-2
      RETURN
C     TOO MANY PRIMITIVE GAUSSIANS.
  945 WRITE (IOUT,1160) K, NP
      IOP(1)=-2
      RETURN
C     SCALE FACTOR OR EXPONENT IS ZERO OR NEGATIVE.
  950 WRITE(IOUT,1010)
      IOP(1)=-2
      RETURN
C     NBASIS AND NUMBER OF BASIS FUNCTIONS IN TABLE DO NOT MATCH.
  960 WRITE(IOUT,1200)NBASIS,N2
      IOP(1)=-2
      RETURN
C     TOO MANY ATOMIC ORBITALS FOR AN ATOM.
  970 WRITE(IOUT,1310)
      IOP(1)=-2
      RETURN
C     FOUND ZERO CONTRACTION COEFFICIENT IN A SHELL.
  980 WRITE (IOUT,1040) IAOLAB(IERR), I, IXYZ(I)
      IOP(1) = -2
      RETURN
      END
      SUBROUTINE STO (LA, IOP20)
C*
C     --------------
C     U OF T VERSION
C     FEBRUARY 1987
C     --------------
C*
C     SETS UP A MINIMAL BASIS OF SLATER TYPE ORBITALS
C*
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C#
C     PARAMETER (NA=#NA, NB=#NB)
C     PARAMETER (NS=#NS, NP=#NP)
C##
      PARAMETER (NA= 36, NB=200)
      PARAMETER (NS=120, NP=300)
C###
      PARAMETER (ZERO=0.0D0, ONE=1.0D0)
C
      INTEGER SHELLA,SHELLN,SHELLT,AOS,SHELLC
C
      COMMON /A/ IOP(99)
      COMMON /A/ NATOMS,ICHARG,MULTIP,IAN(NA),NAE,NBE,NE,NBASIS,C(NA,3)
      COMMON /A/ CDUM(4),ICDUM(401)
C
      COMMON/B/IXYZ(NS),SHELLA(NS),SHELLN(NS),SHELLT(NS),
     1 SHELLC(NS),AOS(NS),NSHLL,MAXTYP,EXX(NP),C1(NP),C2(NP)
      COMMON/SCAL/SCALE(NS),CSAVE(NP,2)
      COMMON /BSINFC/ NSH(NB), LAO(NB), LABEL(NS), LSHELL(NS), BLABEL
      COMMON/IO/IN,IOUT,IODUM(215)
C
      CHARACTER LSHELL*2,NSH*2,NAO*2,LA*4,LABEL*4,IAO*4,LAO*4,LAB*4,
     1 BLABEL*200
C
      DIMENSION E(6),CS(6),CP(6),IAO(6),NAO(5),LA(44)
      DIMENSION STO1S(54),STO2SP(52),STO3SP(44),STO3D(44),STO4SP(36)
      DIMENSION STO4D(16),STO5SP(18)
C
      DATA IAO/'S   ','SP  ','D   ','P   ','SP* ','D*  '/
      DATA PT39/0.39D0/, PT09/0.09D0/
      DATA NAO/' 1', ' 2', ' 3', ' 4', ' 5'/
C     N1S, N2SP, .... POINT TO ATOM NUMBER (IA) FOR THE FIRST ATOM
C     AVAILABLE (IA-N1S)
      DATA N1S,N2SP,N3SP,N3D,N4SP,N4D,N5SP
     1 /     0,   2,  10, 10,  18, 38,  36/
C     1S SHELL
      DATA STO1S/1.24D0,1.69D0,2.69D0,3.68D0,4.68D0,5.67D0,6.67D0,
     1 7.66D0,8.65D0,9.64D0,10.61D0,11.59D0,12.56D0,13.53D0,14.50D0,
     2 15.47D0,16.43D0,17.40D0,18.61D0,19.58D0,20.56D0,21.54D0,22.53D0,
     3 23.52D0,24.50D0,25.49D0,26.47D0,27.46D0,28.44D0,29.43D0,30.42D0,
     4 31.40D0,32.39D0,33.37D0,34.36D0,35.34D0,36.32D0,37.31D0,38.29D0,
     5 39.27D0,40.26D0,41.24D0,42.22D0,43.21D0,44.19D0,45.17D0,46.15D0,
     6 47.14D0,48.12D0,49.10D0,50.08D0,51.07D0,52.05D0,53.03D0/
C     2SP SHELL
      DATA STO2SP/0.80D0,1.15D0,1.50D0,1.72D0,1.95D0,
     1 2.25D0,2.55D0,2.88D0,3.48D0,3.90D0,4.36D0,4.83D0,5.31D0,5.79D0,
     2 6.26D0,6.74D0,7.26D0,7.74D0,8.22D0,8.70D0,9.18D0,9.66D0,10.13D0,
     3 10.61D0,11.09D0,11.56D0,12.04D0,12.52D0,12.99D0,13.47D0,13.94D0,
     4 14.40D0,14.87D0,15.34D0,15.81D0,16.28D0,16.72D0,17.19D0,17.66D0,
     5 18.12D0,18.59D0,19.05D0,19.51D0,19.97D0,20.43D0,20.88D0,21.33D0,
     6 21.79D0,22.25D0,22.71D0,23.17D0,23.63D0/
C     3SP SHELL
      DATA STO3SP/1.75D0,2*1.70D0,1.75D0,1.90D0,2.05D0,
     1 2.10D0,2.33D0,2.75D0,3.01D0,3.21D0,3.44D0,3.67D0,3.89D0,4.11D0,
     2 4.33D0,4.55D0,4.76D0,4.98D0,5.19D0,5.26D0,5.58D0,5.90D0,6.22D0,
     3 6.54D0,6.86D0,7.18D0,7.49D0,7.97D0,8.21D0,8.51D0,8.82D0,9.14D0,
     4 9.45D0,9.77D0,10.09D0,10.41D0,10.74D0,11.08D0,11.39D0,11.71D0,
     5 12.03D0,12.35D0,12.66D0/
C     3D SHELL
      DATA STO3D/8*1.0D0,0.0D0,0.0D0,1.10D0,1.90D0,2.55D0,
     1 3.05D0,3.45D0,3.75D0,4.10D0,4.35D0,4.60D0,4.90D0,5.26D0,5.58D0,
     2 5.90D0,6.22D0,6.54D0,6.86D0,7.18D0,7.49D0,7.97D0,8.21D0,8.51D0,
     3 8.82D0,9.14D0,9.45D0,9.77D0,10.09D0,10.41D0,10.74D0,11.08D0,
     4 11.39D0,11.71D0,12.03D0,12.35D0,12.66D0/
C     4SP SHELL
      DATA STO4SP/1.43D0,1.36D0,1.60D0,1.70D0,1.70D0,1.75D0,1.65D0,
     5 1.55D0,1.55D0,1.60D0,1.60D0,1.90D0,1.80D0,2.00D0,2.12D0,2.22D0,
     6 2.38D0,2.54D0,3.02D0,3.16D0,3.29D0,3.48D0,3.67D0,3.87D0,4.05D0,
     7 4.24D0,4.41D0,4.59D0,4.76D0,4.93D0,4.65D0,4.89D0,5.12D0,5.36D0,
     8 5.59D0,5.82D0/
C     4D SHELL
      DATA STO4D/1.40D0,1.95D0,2.40D0,2.70D0,3.00D0,3.20D0,3.45D0,
     1 3.60D0,3.75D0,3.95D0,4.65D0,4.89D0,5.12D0,5.36D0,5.59D0,5.82D0/
C     5SP SHELL
      DATA STO5SP/1.90D0,1.80D0,1.80D0,1.90D0,1.90D0,1.95D0,1.85D0,
     1 1.75D0,1.75D0,1.80D0,1.80D0,2.10D0,2.05D0,
     2 2.15D0,2.20D0,2.28D0,2.42D0,2.57D0/
C
 1000 FORMAT ('0*** INVALID POLARIZATION/DIFFUSE FUNCTION OPTIONS',
     1 ' SELECTED IN ROUTINE STO (LINK 0301):'/
     2 ' IOP(25) =',I2,', IOP(27) =',I2,', IOP(28) =',I2,', IOP(29) =',
     3 I2)
C*
      MM=1
      NSHELL=0
      NSTART=1
      NGAUSS=IOP(13)
      IF(NGAUSS.EQ.0) NGAUSS=3
C     SET FLAG FOR D ORBITALS ON NA-AR.
      IFDON2=IOP(25)-2*(IOP(25)/2)
C     CHECK THAT ALL OTHER POLARIZATION FLAGS ARE NOT SET.
      IF (IOP(25).GE.2 .OR. IOP(27).NE.0 .OR.
     1 IOP(28).NE.0 .OR. IOP(29).NE.0) THEN
         WRITE (IOUT,1000) IOP(25), IOP(27), IOP(28), IOP(29)
         IOP(1) = -2
         RETURN
      END IF
      ND=6-IOP(8)
      LDIND=4
      IF(IOP(8).EQ.1)LDIND=28
C
      DO 200 I=1,NATOMS
      IA=IAN(I)
      IF (IA .EQ. 0) GO TO 200
      IF (IOP20.NE.0 .AND. IA.LT.0) GO TO 200
C     EXIT TO ERROR ROUTINE IF FUNCTIONS FOR ATOMS HEAVIER THAN
C     XENON ARE REQUESTED, OR FOR FLOATING FUNCTIONS.
      IF (IA.GT.0 .AND. IA.LE.54) GO TO 10
    1 CALL BERROR(0,IA)
      GO TO 200
C     HYDROGEN TO HELIUM
   10 CALL S1S(E,CS,NGAUSS)
      IS=IA-N1S
      DO 20 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*STO1S(IS)**2
      C1(J1)=CS(J)
   20 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=0
      SCALE(NSHELL)=STO1S(IS)
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(1)
      LSHELL(NSHELL)=NAO(1)
      NSH(NSTART)=NAO(1)
      LAO(NSTART)=LA(1)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+1
      MM=MM+NGAUSS
      IF(IA.LE.2)GO TO 200
C     LITHIUM TO NEON
C     NOTE ... WE CONSIDER THE MINIMAL BASES FOR THE LITHIUM AND
C     BERYLLIUM ATOMS TO CONTAIN 2P FUNCTIONS
      IF(NGAUSS.EQ.1)GO TO 1
      CALL S2SP(E,CS,CP,NGAUSS)
      IS=IA-N2SP
      DO 40 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*STO2SP(IS)**2
      C1(J1)=CS(J)
   40 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=STO2SP(IS)
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(2)
      NSH(NSTART  )=NAO(2)
      NSH(NSTART+1)=NAO(2)
      NSH(NSTART+2)=NAO(2)
      NSH(NSTART+3)=NAO(2)
      LAO(NSTART  )=LA(1)
      LAO(NSTART+1)=LA(2)
      LAO(NSTART+2)=LA(3)
      LAO(NSTART+3)=LA(4)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
      IF(IA.LE.10)GO TO 200
C     SODIUM TO ARGON.
C     LIKEWISE THE BASES FOR SODIUM AND MAGNESIUM CONTAIN 3P FUNCTIONS.
C     ALSO USE 3S=3P FOR SC-ZN.
      IF(IA.EQ.19.OR.IA.EQ.20.OR.IA.GE.31)GO TO 50
      LAB=IAO(2)
      CALL S3SP(E,CS,CP,NGAUSS)
      IS=IA-N3SP
      GO TO 55
C     K, CA AND GA-SR,IN-XE USE 3S=3P=3D FIT - GET S=P PORTION.
   50 LAB=IAO(5)
      IF(NGAUSS.EQ.1)GO TO 1
      CALL S3SPD1(E,CS,CP,NGAUSS)
      IS=IA-N3SP
   55 DO 60 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*STO3SP(IS)**2
      C1(J1)=CS(J)
   60 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=STO3SP(IS)
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=LAB
      LSHELL(NSHELL)=NAO(3)
      NSH(NSTART  )=NAO(3)
      NSH(NSTART+1)=NAO(3)
      NSH(NSTART+2)=NAO(3)
      NSH(NSTART+3)=NAO(3)
      LAO(NSTART  )=LA(1)
      LAO(NSTART+1)=LA(2)
      LAO(NSTART+2)=LA(3)
      LAO(NSTART+3)=LA(4)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
      IF(IA.GT.18)GO TO 70
      IF(IFDON2.NE.1)GO TO 200
C     ADD SET OF D ORBITALS TO SECOND ROW ATOMS (STO-NG*).
      IF(IOP(7).EQ.0)GO TO 71
      IS=IA-N3D
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=1
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=STO3D(IS)
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(3)
      LSHELL(NSHELL)=NAO(3)
      NM1=NSTART-1
      DO 65 J=1,ND
      NSH(NM1+J)=NAO(3)
   65 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      EXX(MM)=PT39
      IF(IA.LE.12)EXX(MM)=PT09
      EXX(MM)=EXX(MM)*STO3D(IS)**2
      C1(MM)=ONE
      C2(MM)=ZERO
      MM=MM+1
      GO TO 200
C     POTASSIUM TO KRYPTON.
C     ATOMS K AND CA HAVE A 4SP SHELL ONLY, NO 3D ORBITALS.
C     ATOMS SC TO ZN HAVE 3D, 4S AND 4P BASIS FUNCTIONS.
C     ATOMS GA TO KR HAVE 3D (FROM 3S=3P=3D) AND 4SP SHELLS.
C     ATOMS RB AND SR HAVE 3D (3S=3P=3D), 4S=4P AND 5S=5P SHELLS.
C     ATOMS IN-XE HAVE 3D (3S=3P=3D), 4S=4P=4D AND 5S=5P SHELLS.
   70 IF(IA.LE.20)GO TO 87
      IF(IOP(7).EQ.1)GO TO 75
   71 CALL BERROR(-1,IA)
      GO TO 200
   75 IF(IA.GE.31)GO TO 76
      LAB=IAO(3)
      CALL S3D(E,CS,NGAUSS)
      IS=IA-N3D
      GO TO 79
   76 LAB=IAO(6)
      IF(NGAUSS.EQ.1)GO TO 1
      CALL S3SPD2(E,CS,NGAUSS)
      IS=IA-N3D
   79 DO 80 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*STO3D(IS)**2
      C1(J1)=CS(J)
   80 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=STO3D(IS)
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=LAB
      LSHELL(NSHELL)=NAO(3)
      NM1=NSTART-1
      DO 85 J=1,ND
      NSH(NM1+J)=NAO(3)
   85 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      MM=MM+NGAUSS
C     4SP SHELL (ATOMS K TO KR).
      IF(IA.GT.36)GO TO 110
   87 IF(NGAUSS.EQ.1)GO TO 1
      CALL S4SP(E,CS,CP,NGAUSS)
      IS=IA-N4SP
      DO 88 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*STO4SP(IS)**2
      C1(J1)=CS(J)
   88 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=STO4SP(IS)
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(4)
      NSH(NSTART  )=NAO(4)
      NSH(NSTART+1)=NAO(4)
      NSH(NSTART+2)=NAO(4)
      NSH(NSTART+3)=NAO(4)
      LAO(NSTART  )=LA(1)
      LAO(NSTART+1)=LA(2)
      LAO(NSTART+2)=LA(3)
      LAO(NSTART+3)=LA(4)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
      GO TO 200
C     4SP OF 4SPD (ATOMS RB, SR, IN-XE).
  110 IF(NGAUSS.EQ.1)GO TO 1
      LAB=IAO(5)
      CALL S4SPD1(E,CS,CP,NGAUSS)
      IS=IA-N4SP
      DO 115 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*STO4SP(IS)**2
      C1(J1)=CS(J)
  115 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=STO4SP(IS)
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=LAB
      LSHELL(NSHELL)=NAO(4)
      NSH(NSTART  )=NAO(4)
      NSH(NSTART+1)=NAO(4)
      NSH(NSTART+2)=NAO(4)
      NSH(NSTART+3)=NAO(4)
      LAO(NSTART  )=LA(1)
      LAO(NSTART+1)=LA(2)
      LAO(NSTART+2)=LA(3)
      LAO(NSTART+3)=LA(4)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
      IF (IA .LE. 38) GO TO 130
C     4D OF 4SPD (ATOMS IN-XE).
      LAB=IAO(6)
      CALL S4SPD2(E,CS,NGAUSS)
      IS=IA-N4D
      DO 120 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*STO4D(IS)**2
      C1(J1)=CS(J)
  120 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=STO4D(IS)
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=LAB
      LSHELL(NSHELL)=NAO(4)
      NM1=NSTART-1
      DO 125 J=1,ND
      NSH(NM1+J)=NAO(4)
  125 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      MM=MM+NGAUSS
C     5SP SHELL (ATOMS RB, SR, IN-XE).
  130 IF(NGAUSS.EQ.1)GO TO 1
      CALL S5SP(E,CS,CP,NGAUSS)
      IS=IA-N5SP
      DO 140 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*STO5SP(IS)**2
      C1(J1)=CS(J)
  140 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=STO5SP(IS)
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(5)
      NSH(NSTART  )=NAO(5)
      NSH(NSTART+1)=NAO(5)
      NSH(NSTART+2)=NAO(5)
      NSH(NSTART+3)=NAO(5)
      LAO(NSTART  )=LA(1)
      LAO(NSTART+1)=LA(2)
      LAO(NSTART+2)=LA(3)
      LAO(NSTART+3)=LA(4)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
  200 CONTINUE
C     COPY NUMBER OF SHELLS INTO COMMON B - SAVED SEPARATELY AS A
C     SAFETY FEATURE IN CASE NSHELL BECOMES TOO LARGE.
      NSHLL=NSHELL
      NBASIS=NSTART-1
      RETURN
      END
      SUBROUTINE NM1G (LA, IOP20)
C*
C     --------------
C     U OF T VERSION
C     APRIL 1987
C     --------------
C*
C     SETS UP SPLIT VALENCE N-M1G/N-M11G BASES.
C*
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C#
C     PARAMETER (NA=#NA, NB=#NB)
C     PARAMETER (NS=#NS, NP=#NP)
C##
      PARAMETER (NA= 36, NB=200)
      PARAMETER (NS=120, NP=300)
C###
      PARAMETER (ZERO=0.0D0, ONE=1.0D0)
C
      INTEGER SHELLA,SHELLN,SHELLT,AOS,SHELLC
C
      COMMON /A/ IOP(99)
      COMMON /A/ NATOMS,ICHARG,MULTIP,IAN(NA),NAE,NBE,NE,NBASIS,C(NA,3)
      COMMON /A/ CDUM(4),ICDUM(401)
C
      COMMON/B/IXYZ(NS),SHELLA(NS),SHELLN(NS),SHELLT(NS),
     1 SHELLC(NS),AOS(NS),NSHLL,MAXTYP,EXX(NP),C1(NP),C2(NP)
      COMMON/SCAL/SCALE(NS),CSAVE(NP,2)
      COMMON /BSINFC/ NSH(NB), LAO(NB), LABEL(NS), LSHELL(NS), BLABEL
C
      COMMON/IO/IN,IOUT,IODUM(215)
C
      CHARACTER LSHELL*2,NSH*2,IAO*4,LA*4,LAO*4,LABEL*4,NAO*4,
     1 BLABEL*200
C
      DIMENSION E(6),CS(6),CP(6),LA(44),IAO(10),NAO(6),MAP(6,4)
      DIMENSION EX31G1(18),EX31G2(18)
C
C     SCALE FACTORS FOR VALENCE SHELLS OF N-31G BASIS SETS.
C     VALENCE SCALE FACTORS FOR 6-31G ON NA-AR ARE ALL 1.0.
      DATA EX31G1/1.20D0,1.0D0,3*1.03D0,1.0D0,2*0.99D0,2*1.0D0,3*0.0D0,
     1 1.00D0,2*0.98D0,1.0D0,0.0D0/
      DATA EX31G2/1.15D0,1.0D0,3*1.12D0,1.04D0,
     1 2*0.98D0,2*1.0D0,3*0.0D0,1.00D0,1.02D0,2*1.01D0,0.0D0/
C?GLD
C     DATA IAO/'S   ','SP  ','SP'' ','SP"" ','D   ',
C    1 'P   ','S''  ','S""  ','S""'' ','SP""'''/
C??
C?GBR/IBM/VAX/CDC/UNX
      DATA IAO/'S   ','SP  ','SP'' ','SP" ','D   ',
     1 'P   ','S''  ','S"  ','S"'' ','SP"'''/
C??
      DATA ONEPT1/1.1D0/
      DATA NAO/' 1', ' 2', ' 3', ' 4', ' 5', ' 6'/
C     MAP CONTAINS THE BASIS SET TYPE NUMBER FOR THE LEGAL VALUES OF
C     N AND IOP(6).
      DATA MAP/0,0,1,7,0,6, 3*0,2,3,4, 3*0,5,2*0, 5*0,8/
C
C     ORBITAL SCALING FACTORS FOR EACH ATOM
C     FOR EXTENDED BASES:
C
C     FOR HYDROGEN AND HELIUM:
C     SC1 REFERS TO THE 1S' SHELL,
C     SC2 TO THE 1S" SHELL,
C     SC3 TO THE 2P POLARIZATION SHELL (1S"' FOR N-M11G),
C     SC4 TO THE 2S DIFFUSE SHELL (1S"' FOR N-M11G ONLY),
C     SC5 TO THE 2S DIFFUSE SHELL (FOR N-M11G ONLY).
C
C     FOR LITHIUM TO NEON:
C     SC1 REFERS TO THE 1S SHELL,
C     SC2 TO THE 2SP' SHELL,
C     SC3 TO THE 2SP" SHELL,
C     SC4 TO THE 3D POLARIZATION SHELL (2SP"' FOR N-M11G),
C     SC5 TO THE 3SP DIFFUSE SHELL (3D POLARIZATION FOR N-M11G ONLY),
C     SC6 TO THE 3SP DIFFUSE SHELL (FOR N-M11G ONLY).
C
C     FOR SODIUM TO ARGON:
C     SC1 REFERS TO THE 1S SHELL,
C     SC2 TO THE 2SP SHELL,
C     SC3 TO THE 3SP' SHELL,
C     SC4 TO THE 3SP" SHELL,
C     SC5 TO THE 3D POLARIZATION SHELL,
C     SC6 TO THE 4SP DIFFUSE SHELL.
C
C     FOR POTASSIUM TO KRYPTON:
C     SC1 REFERS TO THE 1S SHELL,
C     SC2 TO THE 2SP SHELL,
C     SC3 TO THE 3SP SHELL,
C     SC4 TO THE 3D SHELL (NOT USED FOR K/CA),
C     SC5 TO THE 4SP' SHELL,
C     SC6 TO THE 4SP" SHELL,
C     SC7 TO THE 4D POLARIZATION SHELL,
C     SC8 TO THE 5SP DIFFUSE SHELL.
C
C     FOR RUBIDIUM TO XENON:
C     SC1 REFERS TO THE 1S SHELL,
C     SC2 TO THE 2SP SHELL,
C     SC3 TO THE 3SP SHELL,
C     SC4 TO THE 3D SHELL,
C     SC5 TO THE 4SP SHELL,
C     SC6 TO THE 4D SHELL (NOT USED FOR RB/SR),
C     SC7 TO THE 5SP' SHELL,
C     SC8 TO THE 5SP" SHELL,
C     SC9 TO THE 5D POLARIZATION SHELL,
C     SC10 TO THE 6SP DIFFUSE SHELL.
C*
 1000 FORMAT('0ILLEGAL COMBINATION OF BASIS SET TYPE (IOP(6) =',I2,') ',
     1 'AND NUMBER OF GAUSSIANS (IOP(13) =',I2,') IN LINK 0301 (NM1G)')
 1010 FORMAT(' FOR ATOM NUMBER',I4,' (ATOMIC NUMBER',I4,')')
C*
C     MM COUNTS PRIMITIVES, NSTART COUNTS ATOMIC ORBITALS.
      MM=1
      NSHELL=0
      NSTART=1
C     SET BASIS SET TYPE: 3-21G, 4-31G, 5-31G, 6-31G, 4-21G (PULAY),
C     6-21G, 4-21G OR 6-311G.
      IA = 0
      IOP6=IOP(6)
      IOP13=IOP(13)
      IF(IOP6.LE.0.OR.IOP6.GT.4)GO TO 900
      IF(IOP13.LE.0.OR.IOP13.GT.6)GO TO 900
      ITYPE=MAP(IOP13,IOP6)
      IF(ITYPE.EQ.0)GO TO 900
C     SET D/P POLARIZATION FLAGS.
      I = IOP(25)
      IFPOL1 = I / 4
      I = I - 4*IFPOL1
      IFPOL2 = I / 2
      IFPOL3 = I - 2*IFPOL2
      I = IOP(27) - 4*(IOP(27)/4)
      IFPOL5 = I / 2
      IFPOL4 = I - 2*IFPOL5
C     SET SP/S DIFFUSE FUNCTION FLAGS.
      I = IOP(28)
      IFDIF1 = I / 4
      I = I - 4*IFDIF1
      IFDIF2 = I / 2
      IFDIF3 = I - 2*IFDIF2
      I = IOP(29) - 4*(IOP(29)/4)
      IFDIF5 = I / 2
      IFDIF4 = I - 2*IFDIF5
      ND=6-IOP(8)
      LDIND=4
      IF(IOP(8).EQ.1)LDIND=28
C
      DO 800 I=1,NATOMS
      SC1 = ONE
      SC2 = ONE
      SC3 = ONE
      SC4 = ONE
      SC5 = ONE
      SC6 = ONE
      SC7 = ONE
      SC8 = ONE
      SC9 = ONE
      SC10 = ONE
      IA=IAN(I)
C     EXIT TO ERROR ROUTINE IF FUNCTIONS FOR ATOMS HEAVIER THAN XENON
C     ARE REQUESTED, OR FOR FLOATING FUNCTIONS.
      IF (IA .EQ. 0) GO TO 800
      IF (IOP20.NE.0 .AND. IA.LT.0) GO TO 800
      IF (IA.GT.0 .AND. IA.LE.20) GO TO 11
      IF (IA.GT.30 .AND. IA.LE.38) GO TO 11
      IF (IA.GT.48 .AND. IA.LE.54) GO TO 11
C     BASIS SET ERROR.
      CALL BERROR(ITYPE,IA)
      GO TO 800
C
C     H TO HE.
C
   11 IF(IA.GT.2)GO TO 30
      IF(IOP6.NE.2)GO TO 12
      SC1=EX31G1(IA)
      SC2=EX31G2(IA)
      GO TO 14
   12 IF(IOP6.NE.1)GO TO 14
      IF(IA.NE.1)GO TO 14
C     H (3-21G)
      SC1=ONEPT1
      SC2=ONEPT1
C     HYDROGEN, HELIUM.
   14 CALL EZERO(E,CS,CP,IA,ITYPE,1,NGAUSS)
      DO 20 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC1**2
      C1(J1)=CS(J)
   20 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=0
      SCALE(NSHELL)=SC1
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(7)
      LSHELL(NSHELL)=NAO(1)
      NSH(NSTART)=NAO(1)
      LAO(NSTART)=LA(21)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+1
      MM=MM+NGAUSS
C
      CALL EZERO(E,CS,CP,IA,ITYPE,2,NGAUSS)
      DO 22 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC2**2
      C1(J1)=CS(J)
   22 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=0
      SCALE(NSHELL)=SC2
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(8)
      LSHELL(NSHELL)=NAO(1)
      NSH(NSTART)=NAO(1)
      LAO(NSTART)=LA(25)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+1
      MM=MM+NGAUSS
C
      IF(IOP6.NE.4)GO TO 24
      CALL EZERO(E,CS,CP,IA,ITYPE,3,NGAUSS)
      DO 23 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC3**2
      C1(J1)=CS(J)
   23 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=0
      SCALE(NSHELL)=SC3
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(9)
      LSHELL(NSHELL)=NAO(1)
      NSH(NSTART)=NAO(1)
      LAO(NSTART)=LA(41)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+1
      MM=MM+NGAUSS
C
   24 IF(IFPOL1.NE.1)GO TO 27
C     ADD A SET OF P'S TO H/HE.
      J=3
      SC=SC3
      IF(IOP6.NE.4)GO TO 25
      J=4
      SC=SC4
   25 CALL EZERO(E,CS,CP,IA,ITYPE,J,NGAUSS)
      DO 26 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC*SC
      C1(J1)=ZERO
   26 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=1
      LABEL(NSHELL)=IAO(6)
      LSHELL(NSHELL)=NAO(2)
      NSH(NSTART  )=NAO(2)
      NSH(NSTART+1)=NAO(2)
      NSH(NSTART+2)=NAO(2)
      LAO(NSTART  )=LA(2)
      LAO(NSTART+1)=LA(3)
      LAO(NSTART+2)=LA(4)
      AOS(NSHELL)=NSTART-1
      NSTART=NSTART+3
      MM=MM+NGAUSS
C
   27 IF(IFDIF1.NE.1)GO TO 800
C     ADD A SET OF DIFFUSE S'S TO H/HE.
      J=4
      SC=SC4
      IF(IOP6.NE.4)GO TO 28
      J=5
      SC=SC5
   28 CALL EZERO(E,CS,CP,IA,ITYPE,J,NGAUSS)
      DO 29 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC**2
      C1(J1)=CS(J)
   29 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=0
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(1)
      LSHELL(NSHELL)=NAO(2)
      NSH(NSTART)=NAO(2)
      LAO(NSTART)=LA(41)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+1
      MM=MM+NGAUSS
      GO TO 800
C
C     LI TO NE.
C
   30 IF(IA.GT.10)GO TO 60
      IF(IOP6.NE.2)GO TO 32
      SC2=EX31G1(IA)
      SC3=EX31G2(IA)
C     FIRST ROW ATOMS
   32 CALL EONE(E,CS,CP,IA,ITYPE,1,NGAUSS)
      DO 40 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC1**2
      C1(J1)=CS(J)
   40 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=0
      SCALE(NSHELL)=SC1
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(1)
      LSHELL(NSHELL)=NAO(1)
      NSH(NSTART)=NAO(1)
      LAO(NSTART)=LA(1)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+1
      MM=MM+NGAUSS
C
      CALL EONE(E,CS,CP,IA,ITYPE,2,NGAUSS)
      DO 50 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC2**2
      C1(J1)=CS(J)
   50 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC2
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(3)
      LSHELL(NSHELL)=NAO(2)
      NSH(NSTART  )=NAO(2)
      NSH(NSTART+1)=NAO(2)
      NSH(NSTART+2)=NAO(2)
      NSH(NSTART+3)=NAO(2)
      LAO(NSTART  )=LA(21)
      LAO(NSTART+1)=LA(22)
      LAO(NSTART+2)=LA(23)
      LAO(NSTART+3)=LA(24)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      CALL EONE(E,CS,CP,IA,ITYPE,3,NGAUSS)
      DO 52 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC3**2
      C1(J1)=CS(J)
   52 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC3
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(4)
      LSHELL(NSHELL)=NAO(2)
      NSH(NSTART  )=NAO(2)
      NSH(NSTART+1)=NAO(2)
      NSH(NSTART+2)=NAO(2)
      NSH(NSTART+3)=NAO(2)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      IF(IOP6.NE.4)GO TO 54
      CALL EONE(E,CS,CP,IA,ITYPE,4,NGAUSS)
      DO 53 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC4**2
      C1(J1)=CS(J)
   53 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC4
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(10)
      LSHELL(NSHELL)=NAO(2)
      NSH(NSTART  )=NAO(2)
      NSH(NSTART+1)=NAO(2)
      NSH(NSTART+2)=NAO(2)
      NSH(NSTART+3)=NAO(2)
      LAO(NSTART  )=LA(41)
      LAO(NSTART+1)=LA(42)
      LAO(NSTART+2)=LA(43)
      LAO(NSTART+3)=LA(44)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
   54 IF(IFPOL2.NE.1)GO TO 57
C     ADD A SET OF D'S TO THE CURRENT ATOM.
      IF (IOP(7) .NE. 1) THEN
         CALL BERROR(-1,IA)
         GO TO 800
      END IF
      J=4
      SC=SC4
      IF (IOP6 .EQ. 4) THEN
         J=5
         SC=SC5
      END IF
      CALL EONE(E,CS,CP,IA,ITYPE,J,NGAUSS)
      DO 55 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC*SC
      C1(J1)=CS(J)
   55 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(5)
      LSHELL(NSHELL)=NAO(3)
      NM1=NSTART-1
      DO 56 J=1,ND
      NSH(NM1+J)=NAO(3)
   56 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      MM=MM+NGAUSS
C
   57 IF(IFDIF2.NE.1)GO TO 800
C     ADD A SET OF DIFFUSE SP'S TO THE CURRENT ATOM.
      J=5
      SC=SC5
      IF (IOP6 .EQ. 4) THEN
         J=6
         SC=SC6
      END IF
      CALL EONE(E,CS,CP,IA,ITYPE,J,NGAUSS)
      DO 58 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC**2
      C1(J1)=CS(J)
   58 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(3)
      NSH(NSTART  )=NAO(3)
      NSH(NSTART+1)=NAO(3)
      NSH(NSTART+2)=NAO(3)
      NSH(NSTART+3)=NAO(3)
      LAO(NSTART  )=LA(41)
      LAO(NSTART+1)=LA(42)
      LAO(NSTART+2)=LA(43)
      LAO(NSTART+3)=LA(44)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
      GO TO 800
C
C     NA TO AR.
C
   60 IF (IA .GT. 18) GO TO 140
      IF (IOP6.NE.2 .OR. IOP13.EQ.6) GO TO 62
      SC3=EX31G1(IA)
      SC4=EX31G2(IA)
   62 CALL ETWO(E,CS,CP,IA,ITYPE,1,NGAUSS)
      DO 70 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC1**2
      C1(J1)=CS(J)
   70 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=0
      SCALE(NSHELL)=SC1
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(1)
      LSHELL(NSHELL)=NAO(1)
      NSH(NSTART)=NAO(1)
      LAO(NSTART)=LA(1)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+1
      MM=MM+NGAUSS
C
      CALL ETWO(E,CS,CP,IA,ITYPE,2,NGAUSS)
      DO 80 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC2**2
      C1(J1)=CS(J)
   80 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC2
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(2)
      NSH(NSTART  )=NAO(2)
      NSH(NSTART+1)=NAO(2)
      NSH(NSTART+2)=NAO(2)
      NSH(NSTART+3)=NAO(2)
      LAO(NSTART  )=LA(1)
      LAO(NSTART+1)=LA(2)
      LAO(NSTART+2)=LA(3)
      LAO(NSTART+3)=LA(4)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      CALL ETWO(E,CS,CP,IA,ITYPE,3,NGAUSS)
      DO 90 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC3**2
      C1(J1)=CS(J)
   90 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC3
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(3)
      LSHELL(NSHELL)=NAO(3)
      NSH(NSTART  )=NAO(3)
      NSH(NSTART+1)=NAO(3)
      NSH(NSTART+2)=NAO(3)
      NSH(NSTART+3)=NAO(3)
      LAO(NSTART  )=LA(21)
      LAO(NSTART+1)=LA(22)
      LAO(NSTART+2)=LA(23)
      LAO(NSTART+3)=LA(24)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      CALL ETWO(E,CS,CP,IA,ITYPE,4,NGAUSS)
      DO 100 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC4**2
      C1(J1)=CS(J)
  100 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC4
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(4)
      LSHELL(NSHELL)=NAO(3)
      NSH(NSTART  )=NAO(3)
      NSH(NSTART+1)=NAO(3)
      NSH(NSTART+2)=NAO(3)
      NSH(NSTART+3)=NAO(3)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      IF(IFPOL3.NE.1)GO TO 135
C     ADD A SET OF D'S TO THE CURRENT ATOM.
      IF(IOP(7).EQ.1)GO TO 110
      CALL BERROR(-1,IA)
      GO TO 800
  110 SC=SC5
      CALL ETWO(E,CS,CP,IA,ITYPE,5,NGAUSS)
      DO 120 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC*SC
      C1(J1)=CS(J)
  120 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(5)
      LSHELL(NSHELL)=NAO(3)
      NM1=NSTART-1
      DO 130 J=1,ND
      NSH(NM1+J)=NAO(3)
  130 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      MM=MM+NGAUSS
C
  135 IF(IFDIF3.NE.1)GO TO 800
C     ADD A SET OF DIFFUSE SP'S TO THE CURRENT ATOM.
      SC=SC6
      CALL ETWO(E,CS,CP,IA,ITYPE,6,NGAUSS)
      DO 136 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC**2
      C1(J1)=CS(J)
  136 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(4)
      NSH(NSTART  )=NAO(4)
      NSH(NSTART+1)=NAO(4)
      NSH(NSTART+2)=NAO(4)
      NSH(NSTART+3)=NAO(4)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
      GO TO 800
C
C     K, CA, GA TO KR.
C
  140 IF(IOP6.NE.1.OR.IOP13.NE.3)GO TO 900
      IF(IA.GT.36)GO TO 210
      CALL ETHREE(E,CS,CP,IA,ITYPE,1,NGAUSS)
      DO 150 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC1**2
      C1(J1)=CS(J)
  150 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=0
      SCALE(NSHELL)=SC1
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(1)
      LSHELL(NSHELL)=NAO(1)
      NSH(NSTART)=NAO(1)
      LAO(NSTART)=LA(1)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+1
      MM=MM+NGAUSS
C
      CALL ETHREE(E,CS,CP,IA,ITYPE,2,NGAUSS)
      DO 160 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC2**2
      C1(J1)=CS(J)
  160 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC2
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(2)
      NSH(NSTART  )=NAO(2)
      NSH(NSTART+1)=NAO(2)
      NSH(NSTART+2)=NAO(2)
      NSH(NSTART+3)=NAO(2)
      LAO(NSTART  )=LA(1)
      LAO(NSTART+1)=LA(2)
      LAO(NSTART+2)=LA(3)
      LAO(NSTART+3)=LA(4)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      CALL ETHREE(E,CS,CP,IA,ITYPE,3,NGAUSS)
      DO 170 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC3**2
      C1(J1)=CS(J)
  170 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC3
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(3)
      NSH(NSTART  )=NAO(3)
      NSH(NSTART+1)=NAO(3)
      NSH(NSTART+2)=NAO(3)
      NSH(NSTART+3)=NAO(3)
      LAO(NSTART  )=LA(21)
      LAO(NSTART+1)=LA(22)
      LAO(NSTART+2)=LA(23)
      LAO(NSTART+3)=LA(24)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      IF(IA.LT.21)GO TO 192
      CALL ETHREE(E,CS,CP,IA,ITYPE,4,NGAUSS)
      DO 180 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC4*SC4
      C1(J1)=CS(J)
  180 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=SC4
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(5)
      LSHELL(NSHELL)=NAO(3)
      NM1=NSTART-1
      DO 190 J=1,ND
      NSH(NM1+J)=NAO(3)
  190 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      MM=MM+NGAUSS
C
  192 CALL ETHREE(E,CS,CP,IA,ITYPE,5,NGAUSS)
      DO 200 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC5**2
      C1(J1)=CS(J)
  200 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC5
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(3)
      LSHELL(NSHELL)=NAO(4)
      NSH(NSTART  )=NAO(4)
      NSH(NSTART+1)=NAO(4)
      NSH(NSTART+2)=NAO(4)
      NSH(NSTART+3)=NAO(4)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      CALL ETHREE(E,CS,CP,IA,ITYPE,6,NGAUSS)
      DO 202 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC6*SC6
      C1(J1)=CS(J)
  202 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC6
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(4)
      LSHELL(NSHELL)=NAO(4)
      NSH(NSTART  )=NAO(4)
      NSH(NSTART+1)=NAO(4)
      NSH(NSTART+2)=NAO(4)
      NSH(NSTART+3)=NAO(4)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      IF(IFPOL4.NE.1)GO TO 207
C     ADD A SET OF D'S TO THE CURRENT ATOM.
      SC=SC7
      CALL ETHREE(E,CS,CP,IA,ITYPE,7,NGAUSS)
      DO 204 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC*SC
      C1(J1)=CS(J)
  204 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(5)
      LSHELL(NSHELL)=NAO(4)
      NM1=NSTART-1
      DO 206 J=1,ND
      NSH(NM1+J)=NAO(4)
  206 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      MM=MM+NGAUSS
C
  207 IF(IFDIF4.NE.1)GO TO 800
C     ADD A SET OF DIFFUSE SP'S TO THE CURRENT ATOM.
      SC=SC8
      CALL ETHREE(E,CS,CP,IA,ITYPE,8,NGAUSS)
      DO 208 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC*SC
      C1(J1)=CS(J)
  208 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(5)
      NSH(NSTART  )=NAO(5)
      NSH(NSTART+1)=NAO(5)
      NSH(NSTART+2)=NAO(5)
      NSH(NSTART+3)=NAO(5)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
      GO TO 800
C
C     RB, SR, IN TO XE.
C
  210 IF(IOP6.NE.1.OR.IOP13.NE.3)GO TO 900
      CALL EFOUR(E,CS,CP,IA,ITYPE,1,NGAUSS)
      DO 220 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC1**2
      C1(J1)=CS(J)
  220 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=0
      SCALE(NSHELL)=SC1
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(1)
      LSHELL(NSHELL)=NAO(1)
      NSH(NSTART)=NAO(1)
      LAO(NSTART)=LA(1)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+1
      MM=MM+NGAUSS
C
      CALL EFOUR(E,CS,CP,IA,ITYPE,2,NGAUSS)
      DO 230 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC2**2
      C1(J1)=CS(J)
  230 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC2
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(2)
      NSH(NSTART  )=NAO(2)
      NSH(NSTART+1)=NAO(2)
      NSH(NSTART+2)=NAO(2)
      NSH(NSTART+3)=NAO(2)
      LAO(NSTART  )=LA(1)
      LAO(NSTART+1)=LA(2)
      LAO(NSTART+2)=LA(3)
      LAO(NSTART+3)=LA(4)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      CALL EFOUR(E,CS,CP,IA,ITYPE,3,NGAUSS)
      DO 240 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC3**2
      C1(J1)=CS(J)
  240 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC3
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(3)
      NSH(NSTART  )=NAO(3)
      NSH(NSTART+1)=NAO(3)
      NSH(NSTART+2)=NAO(3)
      NSH(NSTART+3)=NAO(3)
      LAO(NSTART  )=LA(21)
      LAO(NSTART+1)=LA(22)
      LAO(NSTART+2)=LA(23)
      LAO(NSTART+3)=LA(24)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      CALL EFOUR(E,CS,CP,IA,ITYPE,4,NGAUSS)
      DO 250 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC4*SC4
      C1(J1)=CS(J)
  250 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=SC4
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(5)
      LSHELL(NSHELL)=NAO(3)
      NM1=NSTART-1
      DO 260 J=1,ND
      NSH(NM1+J)=NAO(3)
  260 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      MM=MM+NGAUSS
C
      CALL EFOUR(E,CS,CP,IA,ITYPE,5,NGAUSS)
      DO 270 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC5**2
      C1(J1)=CS(J)
  270 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC5
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(4)
      NSH(NSTART  )=NAO(4)
      NSH(NSTART+1)=NAO(4)
      NSH(NSTART+2)=NAO(4)
      NSH(NSTART+3)=NAO(4)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      IF(IA.LT.39)GO TO 292
      CALL EFOUR(E,CS,CP,IA,ITYPE,6,NGAUSS)
      DO 280 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC6*SC6
      C1(J1)=CS(J)
  280 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=SC6
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(5)
      LSHELL(NSHELL)=NAO(4)
      NM1=NSTART-1
      DO 290 J=1,ND
      NSH(NM1+J)=NAO(4)
  290 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      MM=MM+NGAUSS
C
  292 CALL EFOUR(E,CS,CP,IA,ITYPE,7,NGAUSS)
      DO 300 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC7*SC7
      C1(J1)=CS(J)
  300 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC7
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(3)
      LSHELL(NSHELL)=NAO(5)
      NSH(NSTART  )=NAO(5)
      NSH(NSTART+1)=NAO(5)
      NSH(NSTART+2)=NAO(5)
      NSH(NSTART+3)=NAO(5)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      CALL EFOUR(E,CS,CP,IA,ITYPE,8,NGAUSS)
      DO 310 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC8*SC8
      C1(J1)=CS(J)
  310 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC8
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(4)
      LSHELL(NSHELL)=NAO(5)
      NSH(NSTART  )=NAO(5)
      NSH(NSTART+1)=NAO(5)
      NSH(NSTART+2)=NAO(5)
      NSH(NSTART+3)=NAO(5)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
C
      IF(IFPOL5.NE.1)GO TO 340
C     ADD A SET OF D'S TO THE CURRENT ATOM.
      SC=SC9
      CALL EFOUR(E,CS,CP,IA,ITYPE,9,NGAUSS)
      DO 320 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC*SC
      C1(J1)=CS(J)
  320 C2(J1)=ZERO
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=2
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(5)
      LSHELL(NSHELL)=NAO(5)
      NM1=NSTART-1
      DO 330 J=1,ND
      NSH(NM1+J)=NAO(5)
  330 LAO(NM1+J)=LA(LDIND+J)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+ND
      MM=MM+NGAUSS
C
  340 IF(IFDIF5.NE.1)GO TO 800
C     ADD A SET OF DIFFUSE SP'S TO THE CURRENT ATOM.
      SC=SC10
      CALL EFOUR(E,CS,CP,IA,ITYPE,10,NGAUSS)
      DO 350 J=1,NGAUSS
      J1=MM-1+J
      EXX(J1)=E(J)*SC*SC
      C1(J1)=CS(J)
  350 C2(J1)=CP(J)
      NSHELL=NSHELL+1
      IXYZ(NSHELL)=I
      SHELLA(NSHELL)=MM
      SHELLN(NSHELL)=NGAUSS
      SHELLT(NSHELL)=1
      SCALE(NSHELL)=SC
      SHELLC(NSHELL)=0
      LABEL(NSHELL)=IAO(2)
      LSHELL(NSHELL)=NAO(6)
      NSH(NSTART  )=NAO(6)
      NSH(NSTART+1)=NAO(6)
      NSH(NSTART+2)=NAO(6)
      NSH(NSTART+3)=NAO(6)
      LAO(NSTART  )=LA(25)
      LAO(NSTART+1)=LA(26)
      LAO(NSTART+2)=LA(27)
      LAO(NSTART+3)=LA(28)
      AOS(NSHELL)=NSTART
      NSTART=NSTART+4
      MM=MM+NGAUSS
  800 CONTINUE
C
C     COPY NUMBER OF SHELLS INTO COMMON B - SAVED SEPARATELY AS A
C     SAFETY FEATURE IN CASE NSHELL BECOMES TOO LARGE.
C
      NSHLL=NSHELL
      NBASIS=NSTART-1
      RETURN
C
C     ILLEGAL BASIS SET TYPE.
  900 WRITE(IOUT,1000)IOP6,IOP13
      IF (IA .NE. 0) WRITE (IOUT,1010) I, IA
      IOP(1)=-2
      RETURN
      END
      SUBROUTINE BERROR(K,IA)
C*
C     --------------
C     U OF T VERSION
C     APRIL 1987
C     --------------
C*
C     ROUTINE TO KICK THOU OFF FOR AN IMPROPER BASIS FUNCTION
C     SPECIFICATION FOR ATOMIC NUMBER IA
C*
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C#
C     PARAMETER (NA=#NA)
C##
      PARAMETER (NA= 36)
C###
      COMMON /A/ IOP(99),IC1(7),IC2(NA),CD1(NA,3),CD2(4),IC3(401)
      COMMON/IO/IN,IOUT,IODUM(215)
C*
      CHARACTER IBASIS*6,JBASIS*14
C
      DIMENSION IBASIS(9)
C*
      DATA IBASIS/'STO-NG','3-21G ','4-31G ','5-31G ','6-31G ',
     1 '4-21P ','6-21G ','4-21G ','6-311G'/
C*
 1000 FORMAT('0',A14,' BASIS SET NOT AVAILABLE FOR ATOMIC NUMBER',I4)
 1010 FORMAT('0BASIS SET FOR ATOMIC NUMBER',I4,' CONTAINS D/F ',
     1 'ORBITALS THAT WERE NOT SPECIFIED ON THE *MOL CARD')
C*
      IF(K.LT.0)GO TO 10
C
      JBASIS = IBASIS(K+1)
      J = 6
      IF (K.EQ.0 .OR. K.EQ.8) J = 7
      IF (IOP(25)+IOP(27) .NE. 0) THEN
         JBASIS(J:) = '*(*)'
         J = J + 4
      END IF
      IF (IOP(28)+IOP(29) .NE. 0) JBASIS(J:) = '+(+)'
      WRITE (IOUT,1000) JBASIS, IA
      GO TO 20
C
   10 WRITE(IOUT,1010)IA
C
   20 IOP(1)=-2
      RETURN
      END
