C/    GL9991       05 MAR 87                                         MRP
      SUBROUTINE D2ZER(IFORMS,NZERO,NZROS,TP,WP,TWORHO,ZTEMP)
C
C     --------------
C     GAUSSIAN 82
C     U OF T VERSION
C     MARCH 1987
C     --------------
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     ROUTINE TO COMPUTE TWO-DIMENSION INTEGRALS AND THEIR
C     DERIVATIVES FOR TWO-ELECTRON INTEGRAL FIRST DERIVATIVES
C     COMPUTED IN CORE.
C
      DIMENSION TP(NZERO),WP(NZERO)
C
      COMMON/CCPQ/CCPX(48),CCPY(48),CCPZ(48),CCQX(48),CCQY(48),CCQZ(48)
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,PP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON/IPDRV1/AB2I,CD2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     $             D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,XYZDMY(48)
      COMMON/XYZIP1/XIP (580),YIP (580),ZIP (580),
     $              XIPI(405),YIPI(405),ZIPI(405),
     $              XIPJ(405),YIPJ(405),ZIPJ(405),
     $              XIPK(405),YIPK(405),ZIPK(405)
C
      DATA ONE/1.D0/
C
      NXYZNT=LAMAX*LBMAX*LCMAX*LDMAX
      NZROS=0
      IXYZNT=1-NXYZNT
      DO 118 IZERO=1,NZERO
C     OBTAIN ROOT OF RYS POLYNOMIAL.
      RHOT2=TWORHO*TP(IZERO)
      ZCONST=ZTEMP*WP(IZERO)
C     TEST FOR POSSIBLE BYPASS WITHIN ZEROES LOOP.
      NZROS=NZROS+1
      IXYZNT=IXYZNT+NXYZNT
      CALL  GETIP2(XIP(IXYZNT),PQX,ONE,CCPX,CCQX)
      CALL  GETIP2(YIP(IXYZNT),PQY,ONE,CCPY,CCQY)
      CALL  GETIP2(ZIP(IXYZNT),PQZ,ZCONST,CCPZ,CCQZ)
      GO TO (830,840,850,860,870,880),IFORMS
  830 CALL DIPABC(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,XIPJ,YIPJ,ZIPJ,
     *      XIPK,YIPK,ZIPK,IXYZNT)
      GO TO 118
  840 CALL DIPAC(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,XIPK,YIPK,ZIPK,IXYZNT)
      GO TO 118
  850 CALL DIPACI(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,IXYZNT)
      GO TO 118
  860 CALL DIPAB(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,XIPJ,YIPJ,ZIPJ,IXYZNT)
      GO TO 118
  870 CALL DIPA(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,IXYZNT)
      GO TO 118
  880 CALL DIPABI(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,IXYZNT)
  118 CONTINUE
      RETURN
      END
      SUBROUTINE DIPA(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,IXYZNT)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTER I
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,EP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/
     1 EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     2 D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     3 XYZA1(4),XYZB1(4),XYZC1(4),
     4 XYZA2(4),XYZB2(4),XYZC2(4),
     5 XYZA3(4),XYZB3(4),XYZC3(4),
     6 XYZA4(4),XYZB4(4),XYZC4(4)
C
      DIMENSION XIP(580),YIP(580),ZIP(580),XIPI(405),YIPI(405),ZIPI(405)
C
      RHOT2A=RHOT2*AIAB
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
   30 IND=IXYZNT-1
      DO 100 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 100 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 100 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 100 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XTEMP=XIP(IP)
      YTEMP=YIP(IP)
      ZTEMP=ZIP(IP)
      XIPA=AXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-64
      XTEMP=XIP(IP64)
      YTEMP=YIP(IP64)
      ZTEMP=ZIP(IP64)
      ATEMP=XYZA1(I)
      XIPA=XIPA+ATEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-16
      XTEMP=XIP(IP16)
      YTEMP=YIP(IP16)
      ZTEMP=ZIP(IP16)
      ATEMP=XYZA2(J)
      XIPA=XIPA+ATEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-4
      XTEMP=XIP(IP4)
      YTEMP=YIP(IP4)
      ZTEMP=ZIP(IP4)
      ATEMP=XYZA3(K)
      XIPA=XIPA+ATEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=XIP(IP1)
      YTEMP=YIP(IP1)
      ZTEMP=ZIP(IP1)
      ATEMP=XYZA4(L)
      XIPA=XIPA+ATEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
   80 XIPI(IND)=XIPA
      YIPI(IND)=YIPA
      ZIPI(IND)=ZIPA
  100 CONTINUE
C
C     PACK DOWN XIP,YIP,ZIP
C
      IND=IXYZNT-1
      DO 200 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 200 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 200 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 200 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XIP(IND)=XIP(IP)
      YIP(IND)=YIP(IP)
  200 ZIP(IND)=ZIP(IP)
      RETURN
      END
      SUBROUTINE DIPAB(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,XIPJ,YIPJ,ZIPJ,IXYZNT)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,J
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,EP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/
     1 EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     2 D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     3 XYZA1(4),XYZB1(4),XYZC1(4),
     4 XYZA2(4),XYZB2(4),XYZC2(4),
     5 XYZA3(4),XYZB3(4),XYZC3(4),
     6 XYZA4(4),XYZB4(4),XYZC4(4)
C
      DIMENSION XIP(580),YIP(580),ZIP(580),XIPI(405),XIPJ(405),
     $ YIPI(405),YIPJ(405),ZIPI(405),ZIPJ(405)
C
      RHOT2A=RHOT2*AIAB
      RHOT2B=RHOT2*BIAB
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      BXCNST=-D1ABX + PQX*RHOT2B
      BYCNST=-D1ABY + PQY*RHOT2B
      BZCNST=-D1ABZ + PQZ*RHOT2B
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2BPR=RHOT2B*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZB1(2)= BIAB-D2BPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZB1(3)=XYZB1(2)+XYZB1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZB1(4)=XYZB1(3)+XYZB1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZB2(2)=-AIAB-D2BPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZB2(3)=XYZB2(2)+XYZB2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZB2(4)=XYZB2(3)+XYZB2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2BQR=RHOT2B*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZB3(2)=      D2BQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZB3(3)=XYZB3(2)+XYZB3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZB3(4)=XYZB3(3)+XYZB3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZB4(2)=      D2BQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZB4(3)=XYZB4(2)+XYZB4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZB4(4)=XYZB4(3)+XYZB4(2)
   30 IND=IXYZNT-1
      DO 100 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 100 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 100 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 100 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XTEMP=XIP(IP)
      YTEMP=YIP(IP)
      ZTEMP=ZIP(IP)
      XIPA=AXCNST*XTEMP
      XIPB=BXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPB=BYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPB=BZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-64
      XTEMP=XIP(IP64)
      YTEMP=YIP(IP64)
      ZTEMP=ZIP(IP64)
      ATEMP=XYZA1(I)
      BTEMP=XYZB1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-16
      XTEMP=XIP(IP16)
      YTEMP=YIP(IP16)
      ZTEMP=ZIP(IP16)
      ATEMP=XYZA2(J)
      BTEMP=XYZB2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-4
      XTEMP=XIP(IP4)
      YTEMP=YIP(IP4)
      ZTEMP=ZIP(IP4)
      ATEMP=XYZA3(K)
      BTEMP=XYZB3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=XIP(IP1)
      YTEMP=YIP(IP1)
      ZTEMP=ZIP(IP1)
      ATEMP=XYZA4(L)
      BTEMP=XYZB4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   80 XIPI(IND)=XIPA
      YIPI(IND)=YIPA
      ZIPI(IND)=ZIPA
      XIPJ(IND)=XIPB
      YIPJ(IND)=YIPB
      ZIPJ(IND)=ZIPB
  100 CONTINUE
C
C     PACK DOWN XIP,YIP,ZIP
C
      IND=IXYZNT-1
      DO 200 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 200 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 200 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 200 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XIP(IND)=XIP(IP)
      YIP(IND)=YIP(IP)
  200 ZIP(IND)=ZIP(IP)
      RETURN
      END
      SUBROUTINE DIPABI(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,IXYZNT)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,J
C
C     THIS ROUTINE IS A COPY OF DIPAB, MODIFIED FOR THE CASE I=J
C     BY MIKE PETERSON, DEPT OF CHEMISTRY, UNIVERSITY OF TORONTO,
C     TO AVOID COMPILER PROBLEMS WHERE XIPI, YIPI AND ZIPI COINCIDE WITH
C     XIPJ, YIPJ AND ZIPJ, DUE TO INVALID CODE OPTIMIZATION.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,EP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/
     1 EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     2 D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     3 XYZA1(4),XYZB1(4),XYZC1(4),
     4 XYZA2(4),XYZB2(4),XYZC2(4),
     5 XYZA3(4),XYZB3(4),XYZC3(4),
     6 XYZA4(4),XYZB4(4),XYZC4(4)
C
      DIMENSION XIP(580),YIP(580),ZIP(580),XIPI(405),YIPI(405),
     $ ZIPI(405)
C
      RHOT2A=RHOT2*AIAB
      RHOT2B=RHOT2*BIAB
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      BXCNST=-D1ABX + PQX*RHOT2B
      BYCNST=-D1ABY + PQY*RHOT2B
      BZCNST=-D1ABZ + PQZ*RHOT2B
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2BPR=RHOT2B*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZB1(2)= BIAB-D2BPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZB1(3)=XYZB1(2)+XYZB1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZB1(4)=XYZB1(3)+XYZB1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZB2(2)=-AIAB-D2BPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZB2(3)=XYZB2(2)+XYZB2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZB2(4)=XYZB2(3)+XYZB2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2BQR=RHOT2B*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZB3(2)=      D2BQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZB3(3)=XYZB3(2)+XYZB3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZB3(4)=XYZB3(3)+XYZB3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZB4(2)=      D2BQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZB4(3)=XYZB4(2)+XYZB4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZB4(4)=XYZB4(3)+XYZB4(2)
   30 IND=IXYZNT-1
      DO 100 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 100 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 100 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 100 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XTEMP=XIP(IP)
      YTEMP=YIP(IP)
      ZTEMP=ZIP(IP)
      XIPA=AXCNST*XTEMP
      XIPB=BXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPB=BYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPB=BZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-64
      XTEMP=XIP(IP64)
      YTEMP=YIP(IP64)
      ZTEMP=ZIP(IP64)
      ATEMP=XYZA1(I)
      BTEMP=XYZB1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-16
      XTEMP=XIP(IP16)
      YTEMP=YIP(IP16)
      ZTEMP=ZIP(IP16)
      ATEMP=XYZA2(J)
      BTEMP=XYZB2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-4
      XTEMP=XIP(IP4)
      YTEMP=YIP(IP4)
      ZTEMP=ZIP(IP4)
      ATEMP=XYZA3(K)
      BTEMP=XYZB3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=XIP(IP1)
      YTEMP=YIP(IP1)
      ZTEMP=ZIP(IP1)
      ATEMP=XYZA4(L)
      BTEMP=XYZB4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   80 XIPI(IND)=XIPA+XIPB
      YIPI(IND)=YIPA+YIPB
      ZIPI(IND)=ZIPA+ZIPB
  100 CONTINUE
C
C     PACK DOWN XIP,YIP,ZIP
C
      IND=IXYZNT-1
      DO 200 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 200 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 200 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 200 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XIP(IND)=XIP(IP)
      YIP(IND)=YIP(IP)
  200 ZIP(IND)=ZIP(IP)
      RETURN
      END
      SUBROUTINE DIPABC(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,XIPJ,YIPJ,ZIPJ,
     $      XIPK,YIPK,ZIPK,IXYZNT)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,J,K
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,EP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/
     1 EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     2 D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     3 XYZA1(4),XYZB1(4),XYZC1(4),
     4 XYZA2(4),XYZB2(4),XYZC2(4),
     5 XYZA3(4),XYZB3(4),XYZC3(4),
     6 XYZA4(4),XYZB4(4),XYZC4(4)
C
      DIMENSION XIP(580),YIP(580),ZIP(580),XIPI(405),XIPJ(405),
     $ XIPK(405),YIPI(405),YIPJ(405),YIPK(405),ZIPI(405),
     $ ZIPJ(405),ZIPK(405)
C
      RHOT2A=RHOT2*AIAB
      RHOT2B=RHOT2*BIAB
      RHOT2C=RHOT2*CICD
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      BXCNST=-D1ABX + PQX*RHOT2B
      BYCNST=-D1ABY + PQY*RHOT2B
      BZCNST=-D1ABZ + PQZ*RHOT2B
      CXCNST= D1CDX - PQX*RHOT2C
      CYCNST= D1CDY - PQY*RHOT2C
      CZCNST= D1CDZ - PQZ*RHOT2C
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2BPR=RHOT2B*EP2I
      D2CPR=RHOT2C*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZB1(2)= BIAB-D2BPR
      XYZC1(2)=      D2CPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZB1(3)=XYZB1(2)+XYZB1(2)
      XYZC1(3)=XYZC1(2)+XYZC1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZB1(4)=XYZB1(3)+XYZB1(2)
      XYZC1(4)=XYZC1(3)+XYZC1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZB2(2)=-AIAB-D2BPR
      XYZC2(2)=      D2CPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZB2(3)=XYZB2(2)+XYZB2(2)
      XYZC2(3)=XYZC2(2)+XYZC2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZB2(4)=XYZB2(3)+XYZB2(2)
      XYZC2(4)=XYZC2(3)+XYZC2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2BQR=RHOT2B*EQ2I
      D2CQR=RHOT2C*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZB3(2)=      D2BQR
      XYZC3(2)=-DICD-D2CQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZB3(3)=XYZB3(2)+XYZB3(2)
      XYZC3(3)=XYZC3(2)+XYZC3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZB3(4)=XYZB3(3)+XYZB3(2)
      XYZC3(4)=XYZC3(3)+XYZC3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZB4(2)=      D2BQR
      XYZC4(2)=+CICD-D2CQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZB4(3)=XYZB4(2)+XYZB4(2)
      XYZC4(3)=XYZC4(2)+XYZC4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZB4(4)=XYZB4(3)+XYZB4(2)
      XYZC4(4)=XYZC4(3)+XYZC4(2)
   30 IND=IXYZNT-1
      DO 100 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 100 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 100 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 100 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XTEMP=XIP(IP)
      YTEMP=YIP(IP)
      ZTEMP=ZIP(IP)
      XIPA=AXCNST*XTEMP
      XIPB=BXCNST*XTEMP
      XIPC=CXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPB=BYCNST*YTEMP
      YIPC=CYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPB=BZCNST*ZTEMP
      ZIPC=CZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-64
      XTEMP=XIP(IP64)
      YTEMP=YIP(IP64)
      ZTEMP=ZIP(IP64)
      ATEMP=XYZA1(I)
      BTEMP=XYZB1(I)
      CTEMP=XYZC1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-16
      XTEMP=XIP(IP16)
      YTEMP=YIP(IP16)
      ZTEMP=ZIP(IP16)
      ATEMP=XYZA2(J)
      BTEMP=XYZB2(J)
      CTEMP=XYZC2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-4
      XTEMP=XIP(IP4)
      YTEMP=YIP(IP4)
      ZTEMP=ZIP(IP4)
      ATEMP=XYZA3(K)
      BTEMP=XYZB3(K)
      CTEMP=XYZC3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=XIP(IP1)
      YTEMP=YIP(IP1)
      ZTEMP=ZIP(IP1)
      ATEMP=XYZA4(L)
      BTEMP=XYZB4(L)
      CTEMP=XYZC4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   80 XIPI(IND)=XIPA
      YIPI(IND)=YIPA
      ZIPI(IND)=ZIPA
      XIPJ(IND)=XIPB
      YIPJ(IND)=YIPB
      ZIPJ(IND)=ZIPB
      XIPK(IND)=XIPC
      YIPK(IND)=YIPC
      ZIPK(IND)=ZIPC
  100 CONTINUE
C
C     PACK DOWN XIP,YIP,ZIP
C
      IND=IXYZNT-1
      DO 200 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 200 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 200 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 200 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XIP(IND)=XIP(IP)
      YIP(IND)=YIP(IP)
  200 ZIP(IND)=ZIP(IP)
      RETURN
      END
      SUBROUTINE DIPAC(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,
     $      XIPK,YIPK,ZIPK,IXYZNT)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,K
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,EP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/
     1 EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     2 D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     3 XYZA1(4),XYZB1(4),XYZC1(4),
     4 XYZA2(4),XYZB2(4),XYZC2(4),
     5 XYZA3(4),XYZB3(4),XYZC3(4),
     6 XYZA4(4),XYZB4(4),XYZC4(4)
C
      DIMENSION XIP(580),YIP(580),ZIP(580),XIPI(405),XIPK(405),
     $ YIPI(405),YIPK(405),ZIPI(405),ZIPK(405)
C
      RHOT2A=RHOT2*AIAB
      RHOT2C=RHOT2*CICD
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      CXCNST= D1CDX - PQX*RHOT2C
      CYCNST= D1CDY - PQY*RHOT2C
      CZCNST= D1CDZ - PQZ*RHOT2C
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2CPR=RHOT2C*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZC1(2)=      D2CPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZC1(3)=XYZC1(2)+XYZC1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZC1(4)=XYZC1(3)+XYZC1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZC2(2)=      D2CPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZC2(3)=XYZC2(2)+XYZC2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZC2(4)=XYZC2(3)+XYZC2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2CQR=RHOT2C*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZC3(2)=-DICD-D2CQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZC3(3)=XYZC3(2)+XYZC3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZC3(4)=XYZC3(3)+XYZC3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZC4(2)=+CICD-D2CQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZC4(3)=XYZC4(2)+XYZC4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZC4(4)=XYZC4(3)+XYZC4(2)
   30 IND=IXYZNT-1
      DO 100 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 100 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 100 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 100 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XTEMP=XIP(IP)
      YTEMP=YIP(IP)
      ZTEMP=ZIP(IP)
      XIPA=AXCNST*XTEMP
      XIPC=CXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPC=CYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPC=CZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-64
      XTEMP=XIP(IP64)
      YTEMP=YIP(IP64)
      ZTEMP=ZIP(IP64)
      ATEMP=XYZA1(I)
      CTEMP=XYZC1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-16
      XTEMP=XIP(IP16)
      YTEMP=YIP(IP16)
      ZTEMP=ZIP(IP16)
      ATEMP=XYZA2(J)
      CTEMP=XYZC2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-4
      XTEMP=XIP(IP4)
      YTEMP=YIP(IP4)
      ZTEMP=ZIP(IP4)
      ATEMP=XYZA3(K)
      CTEMP=XYZC3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=XIP(IP1)
      YTEMP=YIP(IP1)
      ZTEMP=ZIP(IP1)
      ATEMP=XYZA4(L)
      CTEMP=XYZC4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   80 XIPI(IND)=XIPA
      YIPI(IND)=YIPA
      ZIPI(IND)=ZIPA
      XIPK(IND)=XIPC
      YIPK(IND)=YIPC
      ZIPK(IND)=ZIPC
  100 CONTINUE
C
C     PACK DOWN XIP,YIP,ZIP
C
      IND=IXYZNT-1
      DO 200 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 200 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 200 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 200 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XIP(IND)=XIP(IP)
      YIP(IND)=YIP(IP)
  200 ZIP(IND)=ZIP(IP)
      RETURN
      END
      SUBROUTINE DIPACI(XIP,YIP,ZIP,XIPI,YIPI,ZIPI,IXYZNT)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,K
C
C     THIS ROUTINE IS A COPY OF DIPAC, MODIFIED FOR THE CASE I=K
C     BY MIKE PETERSON, DEPT OF CHEMISTRY, UNIVERSITY OF TORONTO,
C     TO AVOID COMPILER PROBLEMS WHERE XIPI, YIPI AND ZIPI COINCIDE WITH
C     XIPK, YIPK AND ZIPK, DUE TO INVALID CODE OPTIMIZATION.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,EP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/
     1 EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     2 D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     3 XYZA1(4),XYZB1(4),XYZC1(4),
     4 XYZA2(4),XYZB2(4),XYZC2(4),
     5 XYZA3(4),XYZB3(4),XYZC3(4),
     6 XYZA4(4),XYZB4(4),XYZC4(4)
C
      DIMENSION XIP(580),YIP(580),ZIP(580),XIPI(405),YIPI(405),
     $ ZIPI(405)
C
      RHOT2A=RHOT2*AIAB
      RHOT2C=RHOT2*CICD
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      CXCNST= D1CDX - PQX*RHOT2C
      CYCNST= D1CDY - PQY*RHOT2C
      CZCNST= D1CDZ - PQZ*RHOT2C
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2CPR=RHOT2C*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZC1(2)=      D2CPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZC1(3)=XYZC1(2)+XYZC1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZC1(4)=XYZC1(3)+XYZC1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZC2(2)=      D2CPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZC2(3)=XYZC2(2)+XYZC2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZC2(4)=XYZC2(3)+XYZC2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2CQR=RHOT2C*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZC3(2)=-DICD-D2CQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZC3(3)=XYZC3(2)+XYZC3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZC3(4)=XYZC3(3)+XYZC3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZC4(2)=+CICD-D2CQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZC4(3)=XYZC4(2)+XYZC4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZC4(4)=XYZC4(3)+XYZC4(2)
   30 IND=IXYZNT-1
      DO 100 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 100 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 100 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 100 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XTEMP=XIP(IP)
      YTEMP=YIP(IP)
      ZTEMP=ZIP(IP)
      XIPA=AXCNST*XTEMP
      XIPC=CXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPC=CYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPC=CZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-64
      XTEMP=XIP(IP64)
      YTEMP=YIP(IP64)
      ZTEMP=ZIP(IP64)
      ATEMP=XYZA1(I)
      CTEMP=XYZC1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-16
      XTEMP=XIP(IP16)
      YTEMP=YIP(IP16)
      ZTEMP=ZIP(IP16)
      ATEMP=XYZA2(J)
      CTEMP=XYZC2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-4
      XTEMP=XIP(IP4)
      YTEMP=YIP(IP4)
      ZTEMP=ZIP(IP4)
      ATEMP=XYZA3(K)
      CTEMP=XYZC3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=XIP(IP1)
      YTEMP=YIP(IP1)
      ZTEMP=ZIP(IP1)
      ATEMP=XYZA4(L)
      CTEMP=XYZC4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   80 XIPI(IND)=XIPA+XIPC
      YIPI(IND)=YIPA+YIPC
      ZIPI(IND)=ZIPA+ZIPC
  100 CONTINUE
C
C     PACK DOWN XIP,YIP,ZIP
C
      IND=IXYZNT-1
      DO 200 I=1,LAMAX
      IPI=(I-1)*64+IXYZNT-1
      DO 200 J=1,LBMAX
      IPJ=(J-1)*16+IPI
      DO 200 K=1,LCMAX
      IPK=(K-1)*4+IPJ
      DO 200 L=1,LDMAX
      IP=IPK+L
      IND=IND+1
      XIP(IND)=XIP(IP)
      YIP(IND)=YIP(IP)
  200 ZIP(IND)=ZIP(IP)
      RETURN
      END
      SUBROUTINE DRVIP1(XIP,YIP,ZIP,XIP1,YIP1,ZIP1,XIP2,YIP2,ZIP2,
     1 TWOPT2,IXYZ)
C*
C     ----------------
C     GAUSSIAN 82
C     U OF T VERSION
C     FEBRUARY 1987
C     ----------------
C*
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/IPDRV/AIAB,BIAB,EPIO2,PCX,PCY,PCZ,DABX,DABY,DABZ
      COMMON /I1ECOM/ LAMAX, LBMAX, LPMAX
C
      DIMENSION XIP(80),YIP(80),ZIP(80),XIP1(80),YIP1(80),ZIP1(80),
     1 XIP2(80),YIP2(80),ZIP2(80)
      DIMENSION XYZA1(4),XYZA2(4),XYZC(4)
C*
      T2=TWOPT2*AIAB
      AXCNST=DABX+PCX*T2
      AYCNST=DABY+PCY*T2
      AZCNST=DABZ+PCZ*T2
      CXCNST=-PCX*TWOPT2
      CYCNST=-PCY*TWOPT2
      CZCNST=-PCZ*TWOPT2
      XYZA1(2)=-BIAB-T2*EPIO2
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZA2(2)= AIAB-T2*EPIO2
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZC(2)=TWOPT2*EPIO2
      XYZC(3)=XYZC(2)+XYZC(2)
      XYZC(4)=XYZC(3)+XYZC(2)
      DO 100 I=1,LAMAX
      IPI=(I-1)*4+IXYZ-1
      DO 100 J=1,LBMAX
      IP=IPI+J
      XIP1T=CXCNST*XIP(IP)
      YIP1T=CYCNST*YIP(IP)
      ZIP1T=CZCNST*ZIP(IP)
      XIP2T=AXCNST*XIP(IP)
      YIP2T=AYCNST*YIP(IP)
      ZIP2T=AZCNST*ZIP(IP)
      IF(I.EQ.1) GO TO 50
      K=IP-4
      ATEMP=XYZA1(I)
      CTEMP=XYZC(I)
      XIP1T=XIP1T+CTEMP*XIP(K)
      YIP1T=YIP1T+CTEMP*YIP(K)
      ZIP1T=ZIP1T+CTEMP*ZIP(K)
      XIP2T=XIP2T+ATEMP*XIP(K)
      YIP2T=YIP2T+ATEMP*YIP(K)
      ZIP2T=ZIP2T+ATEMP*ZIP(K)
   50 IF(J.EQ.1) GO TO 60
      K=IP-1
      ATEMP=XYZA2(J)
      CTEMP=XYZC(J)
      XIP1T=XIP1T+CTEMP*XIP(K)
      YIP1T=YIP1T+CTEMP*YIP(K)
      ZIP1T=ZIP1T+CTEMP*ZIP(K)
      XIP2T=XIP2T+ATEMP*XIP(K)
      YIP2T=YIP2T+ATEMP*YIP(K)
      ZIP2T=ZIP2T+ATEMP*ZIP(K)
   60 XIP1(IP)=XIP1T
      YIP1(IP)=YIP1T
      ZIP1(IP)=ZIP1T
      ZIP2(IP)=ZIP2T
      YIP2(IP)=YIP2T
  100 XIP2(IP)=XIP2T
      RETURN
      END
      SUBROUTINE F1DA(RHO,NZERO,TP)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTER I
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,PP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/ EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     * D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     *          XYZA1(4),XYZB1(4),XYZC1(4),
     *          XYZA2(4),XYZB2(4),XYZC2(4),
     *          XYZA3(4),XYZB3(4),XYZC3(4),
     *          XYZA4(4),XYZB4(4),XYZC4(4)
      COMMON/FST2D0/GX(45),GY(45),GZ(45),
     $              X2(125),Y2(125),Z2(125),
     $              X3(225),Y3(225),Z3(225),
     $              X4(405),Y4(405),Z4(405)
      COMMON/XYZIP1/XIP (580),YIP (580),ZIP (580),
     $              XIPI(405),YIPI(405),ZIPI(405),
     $              XIPJ(405),YIPJ(405),ZIPJ(405),
     $              XIPK(405),YIPK(405),ZIPK(405)
C
      DIMENSION TP(NZERO)
C
      KOFFST=LDMAX
      JOFFST=LCMAX*KOFFST
      IOFFST=LBMAX*JOFFST
      NXYZNT=LAMAX*IOFFST
C
      IP=0
      IND=0
      DO 200 IZERO=1,NZERO
C
      RHOT2=(RHO+RHO)*TP(IZERO)
      RHOT2A=RHOT2*AIAB
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
   30 CONTINUE
      DO 100 I=1,LAMAX
      DO 100 J=1,LBMAX
      DO 100 K=1,LCMAX
      DO 100 L=1,LDMAX
      IP=IP+1
      IND=IND+1
      XTEMP=X4(IP)
      YTEMP=Y4(IP)
      ZTEMP=Z4(IP)
      XIPA=AXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-IOFFST
      XTEMP=X4(IP64)
      YTEMP=Y4(IP64)
      ZTEMP=Z4(IP64)
      ATEMP=XYZA1(I)
      XIPA=XIPA+ATEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-JOFFST
      XTEMP=X4(IP16)
      YTEMP=Y4(IP16)
      ZTEMP=Z4(IP16)
      ATEMP=XYZA2(J)
      XIPA=XIPA+ATEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-KOFFST
      XTEMP=X4(IP4)
      YTEMP=Y4(IP4)
      ZTEMP=Z4(IP4)
      ATEMP=XYZA3(K)
      XIPA=XIPA+ATEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=X4(IP1)
      YTEMP=Y4(IP1)
      ZTEMP=Z4(IP1)
      ATEMP=XYZA4(L)
      XIPA=XIPA+ATEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
   80 CONTINUE
      XIPI(IND)=XIPA
      YIPI(IND)=YIPA
      ZIPI(IND)=ZIPA
  100 CONTINUE
  200 CONTINUE
C
      RETURN
      END
      SUBROUTINE F1DAB1(RHO,NZERO,TP)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,J
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,PP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/ EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     $ D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     $          XYZA1(4),XYZB1(4),XYZC1(4),
     $          XYZA2(4),XYZB2(4),XYZC2(4),
     $          XYZA3(4),XYZB3(4),XYZC3(4),
     $          XYZA4(4),XYZB4(4),XYZC4(4)
      COMMON/FST2D0/GX(45),GY(45),GZ(45),
     $              X2(125),Y2(125),Z2(125),
     $              X3(225),Y3(225),Z3(225),
     $              X4(405),Y4(405),Z4(405)
      COMMON/XYZIP1/XIP (580),YIP (580),ZIP (580),
     $              XIPI(405),YIPI(405),ZIPI(405),
     $              XIPJ(405),YIPJ(405),ZIPJ(405),
     $              XIPK(405),YIPK(405),ZIPK(405)
C
      DIMENSION TP(NZERO)
C
      KOFFST=LDMAX
      JOFFST=LCMAX*KOFFST
      IOFFST=LBMAX*JOFFST
C
      IP=0
      IND=0
      DO 200 IZERO=1,NZERO
C
      RHOT2=(RHO+RHO)*TP(IZERO)
      RHOT2A=RHOT2*AIAB
      RHOT2B=RHOT2*BIAB
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      BXCNST=-D1ABX + PQX*RHOT2B
      BYCNST=-D1ABY + PQY*RHOT2B
      BZCNST=-D1ABZ + PQZ*RHOT2B
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2BPR=RHOT2B*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZB1(2)= BIAB-D2BPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZB1(3)=XYZB1(2)+XYZB1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZB1(4)=XYZB1(3)+XYZB1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZB2(2)=-AIAB-D2BPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZB2(3)=XYZB2(2)+XYZB2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZB2(4)=XYZB2(3)+XYZB2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2BQR=RHOT2B*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZB3(2)=      D2BQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZB3(3)=XYZB3(2)+XYZB3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZB3(4)=XYZB3(3)+XYZB3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZB4(2)=      D2BQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZB4(3)=XYZB4(2)+XYZB4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZB4(4)=XYZB4(3)+XYZB4(2)
   30 CONTINUE
      DO 100 I=1,LAMAX
      DO 100 J=1,LBMAX
      DO 100 K=1,LCMAX
      DO 100 L=1,LDMAX
      IP=IP+1
      IND=IND+1
      XTEMP=X4(IP)
      YTEMP=Y4(IP)
      ZTEMP=Z4(IP)
      XIPA=AXCNST*XTEMP
      XIPB=BXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPB=BYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPB=BZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-IOFFST
      XTEMP=X4(IP64)
      YTEMP=Y4(IP64)
      ZTEMP=Z4(IP64)
      ATEMP=XYZA1(I)
      BTEMP=XYZB1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-JOFFST
      XTEMP=X4(IP16)
      YTEMP=Y4(IP16)
      ZTEMP=Z4(IP16)
      ATEMP=XYZA2(J)
      BTEMP=XYZB2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-KOFFST
      XTEMP=X4(IP4)
      YTEMP=Y4(IP4)
      ZTEMP=Z4(IP4)
      ATEMP=XYZA3(K)
      BTEMP=XYZB3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=X4(IP1)
      YTEMP=Y4(IP1)
      ZTEMP=Z4(IP1)
      ATEMP=XYZA4(L)
      BTEMP=XYZB4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   80 CONTINUE
      XIPI(IND)=XIPA
      YIPI(IND)=YIPA
      ZIPI(IND)=ZIPA
      XIPJ(IND)=XIPB
      YIPJ(IND)=YIPB
      ZIPJ(IND)=ZIPB
  100 CONTINUE
  200 CONTINUE
C
      RETURN
      END
      SUBROUTINE F1DAB2(RHO,NZERO,TP)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,J
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,PP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/ EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     $ D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     $          XYZA1(4),XYZB1(4),XYZC1(4),
     $          XYZA2(4),XYZB2(4),XYZC2(4),
     $          XYZA3(4),XYZB3(4),XYZC3(4),
     $          XYZA4(4),XYZB4(4),XYZC4(4)
      COMMON/FST2D0/GX(45),GY(45),GZ(45),
     $              X2(125),Y2(125),Z2(125),
     $              X3(225),Y3(225),Z3(225),
     $              X4(405),Y4(405),Z4(405)
      COMMON/XYZIP1/XIP (580),YIP (580),ZIP (580),
     $              XIPI(405),YIPI(405),ZIPI(405),
     $              XIPJ(405),YIPJ(405),ZIPJ(405),
     $              XIPK(405),YIPK(405),ZIPK(405)
C
      DIMENSION TP(NZERO)
C
      KOFFST=LDMAX
      JOFFST=LCMAX*KOFFST
      IOFFST=LBMAX*JOFFST
C
      IP=0
      IND=0
      DO 200 IZERO=1,NZERO
C
      RHOT2=(RHO+RHO)*TP(IZERO)
      RHOT2A=RHOT2*AIAB
      RHOT2B=RHOT2*BIAB
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      BXCNST=-D1ABX + PQX*RHOT2B
      BYCNST=-D1ABY + PQY*RHOT2B
      BZCNST=-D1ABZ + PQZ*RHOT2B
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2BPR=RHOT2B*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZB1(2)= BIAB-D2BPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZB1(3)=XYZB1(2)+XYZB1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZB1(4)=XYZB1(3)+XYZB1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZB2(2)=-AIAB-D2BPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZB2(3)=XYZB2(2)+XYZB2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZB2(4)=XYZB2(3)+XYZB2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2BQR=RHOT2B*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZB3(2)=      D2BQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZB3(3)=XYZB3(2)+XYZB3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZB3(4)=XYZB3(3)+XYZB3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZB4(2)=      D2BQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZB4(3)=XYZB4(2)+XYZB4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZB4(4)=XYZB4(3)+XYZB4(2)
   30 CONTINUE
      DO 100 I=1,LAMAX
      DO 100 J=1,LBMAX
      DO 100 K=1,LCMAX
      DO 100 L=1,LDMAX
      IP=IP+1
      IND=IND+1
      XTEMP=X4(IP)
      YTEMP=Y4(IP)
      ZTEMP=Z4(IP)
      XIPA=AXCNST*XTEMP
      XIPB=BXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPB=BYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPB=BZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-IOFFST
      XTEMP=X4(IP64)
      YTEMP=Y4(IP64)
      ZTEMP=Z4(IP64)
      ATEMP=XYZA1(I)
      BTEMP=XYZB1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-JOFFST
      XTEMP=X4(IP16)
      YTEMP=Y4(IP16)
      ZTEMP=Z4(IP16)
      ATEMP=XYZA2(J)
      BTEMP=XYZB2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-KOFFST
      XTEMP=X4(IP4)
      YTEMP=Y4(IP4)
      ZTEMP=Z4(IP4)
      ATEMP=XYZA3(K)
      BTEMP=XYZB3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=X4(IP1)
      YTEMP=Y4(IP1)
      ZTEMP=Z4(IP1)
      ATEMP=XYZA4(L)
      BTEMP=XYZB4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
   80 CONTINUE
      XIPI(IND)=XIPA+XIPB
      YIPI(IND)=YIPA+YIPB
      ZIPI(IND)=ZIPA+ZIPB
  100 CONTINUE
  200 CONTINUE
C
      RETURN
      END
      SUBROUTINE F1DABC(RHO,NZERO,TP)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,J,K
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,PP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/ EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     $ D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     $          XYZA1(4),XYZB1(4),XYZC1(4),
     $          XYZA2(4),XYZB2(4),XYZC2(4),
     $          XYZA3(4),XYZB3(4),XYZC3(4),
     $          XYZA4(4),XYZB4(4),XYZC4(4)
      COMMON/FST2D0/GX(45),GY(45),GZ(45),
     $              X2(125),Y2(125),Z2(125),
     $              X3(225),Y3(225),Z3(225),
     $              X4(405),Y4(405),Z4(405)
      COMMON/XYZIP1/XIP (580),YIP (580),ZIP (580),
     $              XIPI(405),YIPI(405),ZIPI(405),
     $              XIPJ(405),YIPJ(405),ZIPJ(405),
     $              XIPK(405),YIPK(405),ZIPK(405)
C
      DIMENSION TP(NZERO)
C
      KOFFST=LDMAX
      JOFFST=LCMAX*KOFFST
      IOFFST=LBMAX*JOFFST
      NXYZNT=LAMAX*IOFFST
C
      IP=0
      IND=0
      DO 200 IZERO=1,NZERO
C
      RHOT2=(RHO+RHO)*TP(IZERO)
      RHOT2A=RHOT2*AIAB
      RHOT2B=RHOT2*BIAB
      RHOT2C=RHOT2*CICD
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      BXCNST=-D1ABX + PQX*RHOT2B
      BYCNST=-D1ABY + PQY*RHOT2B
      BZCNST=-D1ABZ + PQZ*RHOT2B
      CXCNST= D1CDX - PQX*RHOT2C
      CYCNST= D1CDY - PQY*RHOT2C
      CZCNST= D1CDZ - PQZ*RHOT2C
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2BPR=RHOT2B*EP2I
      D2CPR=RHOT2C*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZB1(2)= BIAB-D2BPR
      XYZC1(2)=      D2CPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZB1(3)=XYZB1(2)+XYZB1(2)
      XYZC1(3)=XYZC1(2)+XYZC1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZB1(4)=XYZB1(3)+XYZB1(2)
      XYZC1(4)=XYZC1(3)+XYZC1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZB2(2)=-AIAB-D2BPR
      XYZC2(2)=      D2CPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZB2(3)=XYZB2(2)+XYZB2(2)
      XYZC2(3)=XYZC2(2)+XYZC2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZB2(4)=XYZB2(3)+XYZB2(2)
      XYZC2(4)=XYZC2(3)+XYZC2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2BQR=RHOT2B*EQ2I
      D2CQR=RHOT2C*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZB3(2)=      D2BQR
      XYZC3(2)=-DICD-D2CQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZB3(3)=XYZB3(2)+XYZB3(2)
      XYZC3(3)=XYZC3(2)+XYZC3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZB3(4)=XYZB3(3)+XYZB3(2)
      XYZC3(4)=XYZC3(3)+XYZC3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZB4(2)=      D2BQR
      XYZC4(2)=+CICD-D2CQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZB4(3)=XYZB4(2)+XYZB4(2)
      XYZC4(3)=XYZC4(2)+XYZC4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZB4(4)=XYZB4(3)+XYZB4(2)
      XYZC4(4)=XYZC4(3)+XYZC4(2)
   30 CONTINUE
      DO 100 I=1,LAMAX
      DO 100 J=1,LBMAX
      DO 100 K=1,LCMAX
      DO 100 L=1,LDMAX
      IP=IP+1
      IND=IND+1
      XTEMP=X4(IP)
      YTEMP=Y4(IP)
      ZTEMP=Z4(IP)
      XIPA=AXCNST*XTEMP
      XIPB=BXCNST*XTEMP
      XIPC=CXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPB=BYCNST*YTEMP
      YIPC=CYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPB=BZCNST*ZTEMP
      ZIPC=CZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-IOFFST
      XTEMP=X4(IP64)
      YTEMP=Y4(IP64)
      ZTEMP=Z4(IP64)
      ATEMP=XYZA1(I)
      BTEMP=XYZB1(I)
      CTEMP=XYZC1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-JOFFST
      XTEMP=X4(IP16)
      YTEMP=Y4(IP16)
      ZTEMP=Z4(IP16)
      ATEMP=XYZA2(J)
      BTEMP=XYZB2(J)
      CTEMP=XYZC2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-KOFFST
      XTEMP=X4(IP4)
      YTEMP=Y4(IP4)
      ZTEMP=Z4(IP4)
      ATEMP=XYZA3(K)
      BTEMP=XYZB3(K)
      CTEMP=XYZC3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=X4(IP1)
      YTEMP=Y4(IP1)
      ZTEMP=Z4(IP1)
      ATEMP=XYZA4(L)
      BTEMP=XYZB4(L)
      CTEMP=XYZC4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPB=XIPB+BTEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPB=YIPB+BTEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPB=ZIPB+BTEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   80 CONTINUE
      XIPI(IND)=XIPA
      YIPI(IND)=YIPA
      ZIPI(IND)=ZIPA
      XIPJ(IND)=XIPB
      YIPJ(IND)=YIPB
      ZIPJ(IND)=ZIPB
      XIPK(IND)=XIPC
      YIPK(IND)=YIPC
      ZIPK(IND)=ZIPC
  100 CONTINUE
  200 CONTINUE
C
      RETURN
      END
      SUBROUTINE F1DAC1(RHO,NZERO,TP)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,K
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,PP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/ EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     $ D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     $          XYZA1(4),XYZB1(4),XYZC1(4),
     $          XYZA2(4),XYZB2(4),XYZC2(4),
     $          XYZA3(4),XYZB3(4),XYZC3(4),
     $          XYZA4(4),XYZB4(4),XYZC4(4)
      COMMON/XYZIP1/XIP (580),YIP (580),ZIP (580),
     $              XIPI(405),YIPI(405),ZIPI(405),
     $              XIPJ(405),YIPJ(405),ZIPJ(405),
     $              XIPK(405),YIPK(405),ZIPK(405)
      COMMON/FST2D0/GX(45),GY(45),GZ(45),
     $              X2(125),Y2(125),Z2(125),
     $              X3(225),Y3(225),Z3(225),
     $              X4(405),Y4(405),Z4(405)
C
      DIMENSION TP(NZERO)
C
      KOFFST=LDMAX
      JOFFST=LCMAX*KOFFST
      IOFFST=LBMAX*JOFFST
C
      IP=0
      IND=0
      DO 200 IZERO=1,NZERO
C
      RHOT2=(RHO+RHO)*TP(IZERO)
      RHOT2A=RHOT2*AIAB
      RHOT2C=RHOT2*CICD
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      CXCNST= D1CDX - PQX*RHOT2C
      CYCNST= D1CDY - PQY*RHOT2C
      CZCNST= D1CDZ - PQZ*RHOT2C
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2CPR=RHOT2C*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZC1(2)=      D2CPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZC1(3)=XYZC1(2)+XYZC1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZC1(4)=XYZC1(3)+XYZC1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZC2(2)=      D2CPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZC2(3)=XYZC2(2)+XYZC2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZC2(4)=XYZC2(3)+XYZC2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2CQR=RHOT2C*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZC3(2)=-DICD-D2CQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZC3(3)=XYZC3(2)+XYZC3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZC3(4)=XYZC3(3)+XYZC3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZC4(2)=+CICD-D2CQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZC4(3)=XYZC4(2)+XYZC4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZC4(4)=XYZC4(3)+XYZC4(2)
   30 CONTINUE
      DO 100 I=1,LAMAX
      DO 100 J=1,LBMAX
      DO 100 K=1,LCMAX
      DO 100 L=1,LDMAX
      IP=IP+1
      IND=IND+1
      XTEMP=X4(IP)
      YTEMP=Y4(IP)
      ZTEMP=Z4(IP)
      XIPA=AXCNST*XTEMP
      XIPC=CXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPC=CYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPC=CZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-IOFFST
      XTEMP=X4(IP64)
      YTEMP=Y4(IP64)
      ZTEMP=Z4(IP64)
      ATEMP=XYZA1(I)
      CTEMP=XYZC1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-JOFFST
      XTEMP=X4(IP16)
      YTEMP=Y4(IP16)
      ZTEMP=Z4(IP16)
      ATEMP=XYZA2(J)
      CTEMP=XYZC2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-KOFFST
      XTEMP=X4(IP4)
      YTEMP=Y4(IP4)
      ZTEMP=Z4(IP4)
      ATEMP=XYZA3(K)
      CTEMP=XYZC3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=X4(IP1)
      YTEMP=Y4(IP1)
      ZTEMP=Z4(IP1)
      ATEMP=XYZA4(L)
      CTEMP=XYZC4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   80 CONTINUE
      XIPI(IND)=XIPA
      YIPI(IND)=YIPA
      ZIPI(IND)=ZIPA
      XIPK(IND)=XIPC
      YIPK(IND)=YIPC
      ZIPK(IND)=ZIPC
  100 CONTINUE
  200 CONTINUE
C
      RETURN
      END
      SUBROUTINE F1DAC2(RHO,NZERO,TP)
C
C     CALCULATE DERIVATIVES OF XIP,YIP,ZIP WRT CENTERS I,K
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      COMMON/I2ECOM/LAMAX,LBMAX,LCMAX,LDMAX,LPMAX,LQMAX,LPQMAX,L2EFLL,
     1 EQ,PP,RHOT2,G(13),VALI2P(49),VALI3P(112),A(174)
      COMMON /IPDRV1/ EP2I,EQ2I,AIAB,BIAB,CICD,DICD,PQX,PQY,PQZ,
     $ D1ABX,D1ABY,D1ABZ,D1CDX,D1CDY,D1CDZ,
     $          XYZA1(4),XYZB1(4),XYZC1(4),
     $          XYZA2(4),XYZB2(4),XYZC2(4),
     $          XYZA3(4),XYZB3(4),XYZC3(4),
     $          XYZA4(4),XYZB4(4),XYZC4(4)
      COMMON/XYZIP1/XIP (580),YIP (580),ZIP (580),
     $              XIPI(405),YIPI(405),ZIPI(405),
     $              XIPJ(405),YIPJ(405),ZIPJ(405),
     $              XIPK(405),YIPK(405),ZIPK(405)
      COMMON/FST2D0/GX(45),GY(45),GZ(45),
     $              X2(125),Y2(125),Z2(125),
     $              X3(225),Y3(225),Z3(225),
     $              X4(405),Y4(405),Z4(405)
C
      DIMENSION TP(NZERO)
C
      KOFFST=LDMAX
      JOFFST=LCMAX*KOFFST
      IOFFST=LBMAX*JOFFST
C
      IP=0
      IND=0
      DO 200 IZERO=1,NZERO
C
      RHOT2=(RHO+RHO)*TP(IZERO)
      RHOT2A=RHOT2*AIAB
      RHOT2C=RHOT2*CICD
      AXCNST= D1ABX + PQX*RHOT2A
      AYCNST= D1ABY + PQY*RHOT2A
      AZCNST= D1ABZ + PQZ*RHOT2A
      CXCNST= D1CDX - PQX*RHOT2C
      CYCNST= D1CDY - PQY*RHOT2C
      CZCNST= D1CDZ - PQZ*RHOT2C
      IF(LPMAX.EQ.1) GO TO 20
      D2APR=RHOT2A*EP2I
      D2CPR=RHOT2C*EP2I
      IF(LAMAX.EQ.1) GO TO 15
      XYZA1(2)=-BIAB-D2APR
      XYZC1(2)=      D2CPR
      XYZA1(3)=XYZA1(2)+XYZA1(2)
      XYZC1(3)=XYZC1(2)+XYZC1(2)
      XYZA1(4)=XYZA1(3)+XYZA1(2)
      XYZC1(4)=XYZC1(3)+XYZC1(2)
   15 IF(LBMAX.EQ.1) GO TO 20
      XYZA2(2)= AIAB-D2APR
      XYZC2(2)=      D2CPR
      XYZA2(3)=XYZA2(2)+XYZA2(2)
      XYZC2(3)=XYZC2(2)+XYZC2(2)
      XYZA2(4)=XYZA2(3)+XYZA2(2)
      XYZC2(4)=XYZC2(3)+XYZC2(2)
   20 IF(LQMAX.EQ.1) GO TO 30
      D2AQR=RHOT2A*EQ2I
      D2CQR=RHOT2C*EQ2I
      IF(LCMAX.EQ.1) GO TO 25
      XYZA3(2)=      D2AQR
      XYZC3(2)=-DICD-D2CQR
      XYZA3(3)=XYZA3(2)+XYZA3(2)
      XYZC3(3)=XYZC3(2)+XYZC3(2)
      XYZA3(4)=XYZA3(3)+XYZA3(2)
      XYZC3(4)=XYZC3(3)+XYZC3(2)
   25 IF(LDMAX.EQ.1) GO TO 30
      XYZA4(2)=      D2AQR
      XYZC4(2)=+CICD-D2CQR
      XYZA4(3)=XYZA4(2)+XYZA4(2)
      XYZC4(3)=XYZC4(2)+XYZC4(2)
      XYZA4(4)=XYZA4(3)+XYZA4(2)
      XYZC4(4)=XYZC4(3)+XYZC4(2)
   30 CONTINUE
      DO 100 I=1,LAMAX
      DO 100 J=1,LBMAX
      DO 100 K=1,LCMAX
      DO 100 L=1,LDMAX
      IP=IP+1
      IND=IND+1
      XTEMP=X4(IP)
      YTEMP=Y4(IP)
      ZTEMP=Z4(IP)
      XIPA=AXCNST*XTEMP
      XIPC=CXCNST*XTEMP
      YIPA=AYCNST*YTEMP
      YIPC=CYCNST*YTEMP
      ZIPA=AZCNST*ZTEMP
      ZIPC=CZCNST*ZTEMP
      IF(I.EQ.1) GO TO 50
      IP64=IP-IOFFST
      XTEMP=X4(IP64)
      YTEMP=Y4(IP64)
      ZTEMP=Z4(IP64)
      ATEMP=XYZA1(I)
      CTEMP=XYZC1(I)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   50 IF(J.EQ.1) GO TO 60
      IP16=IP-JOFFST
      XTEMP=X4(IP16)
      YTEMP=Y4(IP16)
      ZTEMP=Z4(IP16)
      ATEMP=XYZA2(J)
      CTEMP=XYZC2(J)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   60 IF(K.EQ.1) GO TO 70
      IP4=IP-KOFFST
      XTEMP=X4(IP4)
      YTEMP=Y4(IP4)
      ZTEMP=Z4(IP4)
      ATEMP=XYZA3(K)
      CTEMP=XYZC3(K)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   70 IF(L.EQ.1) GO TO 80
      IP1=IP-1
      XTEMP=X4(IP1)
      YTEMP=Y4(IP1)
      ZTEMP=Z4(IP1)
      ATEMP=XYZA4(L)
      CTEMP=XYZC4(L)
      XIPA=XIPA+ATEMP*XTEMP
      XIPC=XIPC+CTEMP*XTEMP
      YIPA=YIPA+ATEMP*YTEMP
      YIPC=YIPC+CTEMP*YTEMP
      ZIPA=ZIPA+ATEMP*ZTEMP
      ZIPC=ZIPC+CTEMP*ZTEMP
   80 CONTINUE
      XIPI(IND)=XIPA+XIPC
      YIPI(IND)=YIPA+YIPC
      ZIPI(IND)=ZIPA+ZIPC
  100 CONTINUE
  200 CONTINUE
C
      RETURN
      END
      SUBROUTINE RAWST(S,T,LAX,LAY,LAZ,LBX,LBY,LBZ,AS,TWOASQ,SX,SY,SZ)
C*
C     ----------------
C     GAUSSIAN 82
C     FEBRUARY 1987
C     ----------------
C*
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DIMENSION SX(32),SY(32),SZ(32),CNST(6)
C*
      DATA CNST/0.0D0,0.0D0,1.0D0,3.0D0,6.0D0,10.0D0/
C*
      IJX=4*(LAX-1)+LBX
      IJY=4*(LAY-1)+LBY
      IJZ=4*(LAZ-1)+LBZ
      SXY=SX(IJX)*SY(IJY)
      SXZ=SX(IJX)*SZ(IJZ)
      SYZ=SY(IJY)*SZ(IJZ)
      S=SXY*SZ(IJZ)
      T=DFLOAT(2*(LAX+LAY+LAZ)-3)*AS*S
     1 -TWOASQ*(SX(IJX+8)*SYZ+SY(IJY+8)*SXZ+SZ(IJZ+8)*SXY)
      IF(LAX.GT.2) T=T-CNST(LAX)*SX(IJX-8)*SYZ
      IF(LAY.GT.2) T=T-CNST(LAY)*SY(IJY-8)*SXZ
      IF(LAZ.GT.2) T=T-CNST(LAZ)*SZ(IJZ-8)*SXY
      RETURN
      END
