*     GLASMCDC     07 JUL 88                                         MRP
      SUBROUTINE UNPACK
C
C     INTEGRAL LABEL UNPACK ROUTINE FOR CDC SYSTEMS.
C
C     AUTHOR: JACKY LIEVEN, UNIV LIBRE DE BRUXELLES, BRUSSELS.
C     MODIFIED: MIKE PETERSON, UNIV OF TORONTO CHEMISTRY DEPT,
C               TORONTO, ONTARIO, CANADA.
C
C     THE INTEGRAL LABEL IS CONTAINED IN JA, AND IS UNPACKED
C     INTO 4 INDICES, I, J, K AND L.
C     ALL VARIABLES ARE CONTAINED IN COMMON /PACKED/:
C     COMMON /PACKED/ I, J, K, L, JA
C     EACH INDEX OCCUPIES 10 BITS.
C
      COMMON /PACKED/ I, J, K, L, JA
C
      L = AND (JA, 1023)
      JA = SHIFT (JA, -10)
      K = AND (JA, 1023)
      JA = SHIFT (JA, -10)
      J = AND (JA, 1023)
      I = SHIFT (JA, -10)
      RETURN
      END
