C/    GLASMVAX     05 JAN 86                                         MRP
      SUBROUTINE UNPACK
C*
C     UNPACK INTEGRAL LABELS FOR VAX COMPUTERS.
C
C     AUTHOR: RAY POIRIER, CHEMISTRY DEPT, MEMORIAL UNIVERSITY OF NFLD,
C             ST. JOHN'S, NEWFOUNDLAND, CANADA.
C
C     UNPACK UNPACKS THE INTEGRAL LABEL JA INTO THE FOUR
C     MOLECULAR ORBITAL INDICES I, J, K AND L. ALL VARIABLES ARE
C     INTEGER, AND ARE IN COMMON /PACKED/:
C     COMMON/PACKED/I,J,K,L,JA
C     EACH INDEX OCCUPIES 7 BITS IN THE LABEL.
C*
      COMMON/PACKED/I,J,K,L,JA
C
      I = ISHFT (JA, -24)
      J = ISHFT (JA, 8)
      J = ISHFT (J, -24)
      K = ISHFT (JA, 16)
      K = ISHFT (K, -24)
      L = ISHFT (JA, 24)
      L = ISHFT (L, -24)
      RETURN
      END
