C/    GLASMGLD     05 JAN 86                                         MRP
      SUBROUTINE UNPACK
C
C     AUTHOR: MIKE PETERSON, UNIV OF TORONTO CHEMISTRY DEPT,
C             TORONTO, ONTARIO, CANADA.
C
C     UNPACK UNPACKS THE INTEGRAL LABEL JA INTO THE FOUR
C     MOLECULAR ORBITAL INDICES I, J, K AND L. ALL VARIABLES ARE
C     INTEGER, AND ARE IN COMMON /PACKED/:
C     COMMON /PACKED/ I, J, K, L, JA
C     EACH INDEX OCCUPIES 7 BITS IN THE LABEL.
C
C     THIS ROUTINE IS USED ONLY IN THE GOULD FORTRAN 77+ VERSION.
C
      INTEGER*1 JA1(4)
C
      COMMON /PACKED/ I, J, K, L, JA
C
      EQUIVALENCE (JA,JA1(1))
C
      I = JA1(1)
      J = JA1(2)
      K = JA1(3)
      L = JA1(4)
      RETURN
      END
